package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"
)

// FindOrderByID is the resolver for the findOrderByID field. Federation entity
// resolvers perform NO authorization (the gateway-federated fetch path is
// trusted). findOne(orders, {_id: id}); error if missing.
func (r *entityResolver) FindOrderByID(ctx context.Context, id uuid.UUID) (*Order, error) {
	order, err := r.Store.GetOrder(ctx, id)
	if err != nil {
		return nil, orderNotFound(id)
	}
	return toOrderModel(order), nil
}

// FindOrderItemByID is the resolver for the findOrderItemByID field. Reads the
// (never-written) order_items collection → generally 404. No authorization.
func (r *entityResolver) FindOrderItemByID(ctx context.Context, id uuid.UUID) (*OrderItem, error) {
	item, err := r.Store.GetOrderItemFromCollection(ctx, id)
	if err != nil {
		return nil, orderItemNotFound(id)
	}
	return toOrderItemModel(item), nil
}

// FindUserByID is the resolver for the findUserByID field. findOne(users, {_id:
// id}); error if missing. No authorization. Returns the local User read model.
func (r *entityResolver) FindUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	user, err := r.Store.GetUser(ctx, id)
	if err != nil {
		return nil, userNotFound(id)
	}
	return toUserModel(user), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
