// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// Specifies the order of foreign types.
type CommonOrderInput struct {
	// Order direction of orders.
	Direction *OrderDirection `json:"direction,omitempty"`
	// Field that orders should be ordered by.
	Field *CommonOrderField `json:"field,omitempty"`
}

type CreateOrderInput struct {
	// UUID of user owning the order.
	UserID uuid.UUID `json:"userId"`
	// OrderItems of order.
	OrderItemInputs []OrderItemInput `json:"orderItemInputs"`
	// UUID of address to where the order should be shipped to.
	ShipmentAddressID uuid.UUID `json:"shipmentAddressId"`
	// UUID of address of invoice.
	InvoiceAddressID uuid.UUID `json:"invoiceAddressId"`
	// UUID of payment information that the order should be processed with.
	PaymentInformationID uuid.UUID `json:"paymentInformationId"`
	// Optional VAT number.
	VatNumber *string `json:"vatNumber,omitempty"`
}

// Foreign type of a discount.
type Discount struct {
	// UUID of the discount.
	ID uuid.UUID `json:"id"`
}

func (Discount) IsEntity() {}

// A connection of discounts.
type DiscountConnection struct {
	// The resulting entities.
	Nodes []Discount `json:"nodes"`
	// Whether this connection has a next page.
	HasNextPage bool `json:"hasNextPage"`
	// The total amount of items in this connection.
	TotalCount int `json:"totalCount"`
}

type Mutation struct {
}

// The order of a user.
type Order struct {
	// Order UUID.
	ID uuid.UUID `json:"id"`
	// User owning order.
	User *User `json:"user"`
	// Timestamp when order was created.
	CreatedAt time.Time `json:"createdAt"`
	// The status of the order.
	OrderStatus OrderStatus `json:"orderStatus"`
	// Timestamp of order placement. `None` until order is placed.
	PlacedAt *time.Time `json:"placedAt,omitempty"`
	// The rejection reason if status of the order is `OrderStatus::Rejected`.
	RejectionReason *RejectionReason `json:"rejectionReason,omitempty"`
	// Address of invoice.
	InvoiceAddress *UserAddress `json:"invoiceAddress"`
	// Total compensatable amount of order.
	CompensatableOrderAmount int `json:"compensatableOrderAmount"`
	// UUID of payment information that the order should be processed with.
	PaymentInformationID uuid.UUID `json:"paymentInformationId"`
	// Retrieves order items.
	OrderItems         *OrderItemConnection `json:"orderItems"`
	InternalOrderItems []*OrderItem         `json:"-"`
	InvoiceAddressID   uuid.UUID            `json:"-"`
	UserID             uuid.UUID            `json:"-"`
}

func (Order) IsEntity() {}

// A connection of orders.
type OrderConnection struct {
	// The resulting entities.
	Nodes []Order `json:"nodes"`
	// Whether this connection has a next page.
	HasNextPage bool `json:"hasNextPage"`
	// The total amount of items in this connection.
	TotalCount int `json:"totalCount"`
}

// Describes an order item of an order.
type OrderItem struct {
	// order item UUID.
	ID uuid.UUID `json:"id"`
	// Timestamp when order item was created.
	CreatedAt time.Time `json:"createdAt"`
	// Product variant associated with order item.
	ProductVariant *ProductVariant `json:"productVariant"`
	// Product variant version associated with order item.
	ProductVariantVersion *ProductVariantVersion `json:"productVariantVersion"`
	// Tax rate version associated with order item.
	TaxRateVersion *TaxRateVersion `json:"taxRateVersion"`
	// Shopping cart item associated with order item.
	ShoppingCartItem *ShoppingCartItem `json:"shoppingCartItem"`
	// Specifies the quantity of the order item.
	Count int `json:"count"`
	// Total cost of product item, which can also be refunded.
	CompensatableAmount int `json:"compensatableAmount"`
	// Shipment method of order item.
	ShipmentMethod *ShipmentMethod `json:"shipmentMethod"`
	// Retrieves discounts.
	Discounts               *DiscountConnection `json:"discounts"`
	InternalDiscounts       []uuid.UUID         `json:"-"`
	ProductVariantID        uuid.UUID           `json:"-"`
	ProductVariantVersionID uuid.UUID           `json:"-"`
	ShipmentMethodID        uuid.UUID           `json:"-"`
	ShoppingCartItemID      uuid.UUID           `json:"-"`
	TaxRateVersionID        uuid.UUID           `json:"-"`
}

func (OrderItem) IsEntity() {}

// A connection of order items.
type OrderItemConnection struct {
	// The resulting entities.
	Nodes []OrderItem `json:"nodes"`
	// Whether this connection has a next page.
	HasNextPage bool `json:"hasNextPage"`
	// The total amount of items in this connection.
	TotalCount int `json:"totalCount"`
}

type OrderItemInput struct {
	// UUID of shopping cart item associated with order item.
	ShoppingCartItemID uuid.UUID `json:"shoppingCartItemId"`
	// UUID of shipment method to use with order item.
	ShipmentMethodID uuid.UUID `json:"shipmentMethodId"`
	// UUIDs of coupons to use with order item.
	CouponIds []uuid.UUID `json:"couponIds"`
}

// Specifies the order of orders.
type OrderOrderInput struct {
	// Order direction of orders.
	Direction *OrderDirection `json:"direction,omitempty"`
	// Field that orders should be ordered by.
	Field *OrderOrderField `json:"field,omitempty"`
}

type PaymentAuthorizationInput struct {
	// CVC/CVV number of 3-4 digits.
	Cvc *int `json:"cvc,omitempty"`
}

type PlaceOrderInput struct {
	// UUID of order to place.
	ID uuid.UUID `json:"id"`
	// Optional payment authorization data.
	PaymentAuthorization *PaymentAuthorizationInput `json:"paymentAuthorization,omitempty"`
}

// Foreign type of a product variant.
type ProductVariant struct {
	// UUID of the product variant.
	ID uuid.UUID `json:"id"`
}

func (ProductVariant) IsEntity() {}

// Foreign type of a product variant.
type ProductVariantVersion struct {
	// UUID of the product variant version.
	ID uuid.UUID `json:"id"`
}

func (ProductVariantVersion) IsEntity() {}

type Query struct {
}

// Describes the method/provider that the shipment uses.
type ShipmentMethod struct {
	// UUID of the shipment method.
	ID uuid.UUID `json:"id"`
}

func (ShipmentMethod) IsEntity() {}

// Foreign type of a shopping cart item.
type ShoppingCartItem struct {
	// UUID of the shopping cart item.
	ID uuid.UUID `json:"id"`
}

func (ShoppingCartItem) IsEntity() {}

// Foreign type of a tax rate version.
type TaxRateVersion struct {
	// UUID of the tax rate.
	ID uuid.UUID `json:"id"`
}

func (TaxRateVersion) IsEntity() {}

// Type of a user owning orders.
type User struct {
	// UUID of user.
	ID uuid.UUID `json:"id"`
	// Retrieves orders of user.
	Orders *OrderConnection `json:"orders"`
}

func (User) IsEntity() {}

// Foreign type of an user address.
type UserAddress struct {
	// UUID of the product item.
	ID uuid.UUID `json:"id"`
}

func (UserAddress) IsEntity() {}

// Describes the fields that a foreign types can be ordered by.
//
// Only the id valid at the moment.
type CommonOrderField string

const (
	// Orders by "id".
	CommonOrderFieldID CommonOrderField = "ID"
)

var AllCommonOrderField = []CommonOrderField{
	CommonOrderFieldID,
}

func (e CommonOrderField) IsValid() bool {
	switch e {
	case CommonOrderFieldID:
		return true
	}
	return false
}

func (e CommonOrderField) String() string {
	return string(e)
}

func (e *CommonOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommonOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommonOrderField", str)
	}
	return nil
}

func (e CommonOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommonOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommonOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// GraphQL order direction.
type OrderDirection string

const (
	// Ascending order direction.
	OrderDirectionAsc OrderDirection = "ASC"
	// Descending order direction.
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Describes the fields that a order can be ordered by.
type OrderOrderField string

const (
	// Orders by "id".
	OrderOrderFieldID OrderOrderField = "ID"
	// Orders by "user_id".
	OrderOrderFieldUserID OrderOrderField = "USER_ID"
	// Orders by "name".
	OrderOrderFieldName OrderOrderField = "NAME"
	// Orders by "created_at".
	OrderOrderFieldCreatedAt OrderOrderField = "CREATED_AT"
	// Orders by "last_updated_at".
	OrderOrderFieldLastUpdatedAt OrderOrderField = "LAST_UPDATED_AT"
)

var AllOrderOrderField = []OrderOrderField{
	OrderOrderFieldID,
	OrderOrderFieldUserID,
	OrderOrderFieldName,
	OrderOrderFieldCreatedAt,
	OrderOrderFieldLastUpdatedAt,
}

func (e OrderOrderField) IsValid() bool {
	switch e {
	case OrderOrderFieldID, OrderOrderFieldUserID, OrderOrderFieldName, OrderOrderFieldCreatedAt, OrderOrderFieldLastUpdatedAt:
		return true
	}
	return false
}

func (e OrderOrderField) String() string {
	return string(e)
}

func (e *OrderOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderOrderField", str)
	}
	return nil
}

func (e OrderOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Describes if order is placed, or yet pending. An order can be rejected during its lifetime.
type OrderStatus string

const (
	// Order is saved a a template, this status can only last for max. 1 hour.
	OrderStatusPending OrderStatus = "PENDING"
	// Order is placed, which means SAGA for payment, fullfill and other validity checks need to be triggered.
	OrderStatusPlaced OrderStatus = "PLACED"
	// Something went wrong with the order and it was compensated in all relevant serivces.
	OrderStatusRejected OrderStatus = "REJECTED"
)

var AllOrderStatus = []OrderStatus{
	OrderStatusPending,
	OrderStatusPlaced,
	OrderStatusRejected,
}

func (e OrderStatus) IsValid() bool {
	switch e {
	case OrderStatusPending, OrderStatusPlaced, OrderStatusRejected:
		return true
	}
	return false
}

func (e OrderStatus) String() string {
	return string(e)
}

func (e *OrderStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderStatus", str)
	}
	return nil
}

func (e OrderStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Describes the reason why an order was rejected, in case of rejection: `OrderStatus::Rejected`.
type RejectionReason string

const (
	// The order was rejected due to its invalid content.
	RejectionReasonInvalidOrderData RejectionReason = "INVALID_ORDER_DATA"
	// The inventory service was not able to reserve inventory items according to the order.
	RejectionReasonInventoryReservationFailed RejectionReason = "INVENTORY_RESERVATION_FAILED"
)

var AllRejectionReason = []RejectionReason{
	RejectionReasonInvalidOrderData,
	RejectionReasonInventoryReservationFailed,
}

func (e RejectionReason) IsValid() bool {
	switch e {
	case RejectionReasonInvalidOrderData, RejectionReasonInventoryReservationFailed:
		return true
	}
	return false
}

func (e RejectionReason) String() string {
	return string(e)
}

func (e *RejectionReason) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RejectionReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RejectionReason", str)
	}
	return nil
}

func (e RejectionReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RejectionReason) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RejectionReason) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
