package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"errors"
	"misarch/order/store"
	"time"

	"github.com/google/uuid"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input CreateOrderInput) (*Order, error) {
	// Authorization: caller must be input.userId or a permissive role.
	if err := authorizeUser(ctx, input.UserID); err != nil {
		return nil, err
	}
	// The Authorized-User header is required (forwarded to shoppingcart).
	authHeader, err := authorizedUserHeaderJSON(ctx)
	if err != nil {
		return nil, err
	}

	// Dedupe order-item inputs by shoppingCartItemId (BTreeSet semantics), then
	// sort ascending by that id.
	inputs := dedupeOrderItemInputs(input.OrderItemInputs)

	// validate_order_input: user exists, shipment methods + coupons present,
	// addresses (user-existence only) — all against LOCAL read models.
	if err := r.validateOrderInput(ctx, input, inputs); err != nil {
		return nil, err
	}

	// A single timestamp captured at the start, reused for the order and items.
	now := time.Now().UTC()

	items, err := r.createInternalOrderItems(ctx, input.UserID, inputs, authHeader, now)
	if err != nil {
		return nil, err
	}

	var compensatableOrderAmount uint64
	for i := range items {
		compensatableOrderAmount += items[i].CompensatableAmount
	}

	order := store.Order{
		ID:                       uuid.New(),
		User:                     store.User{ID: input.UserID, UserAddressIDs: []uuid.UUID{}},
		CreatedAt:                now,
		OrderStatus:              "PENDING",
		PlacedAt:                 nil,
		RejectionReason:          nil,
		InternalOrderItems:       items,
		ShipmentAddress:          store.UUIDRef{ID: input.ShipmentAddressID},
		InvoiceAddress:           store.UUIDRef{ID: input.InvoiceAddressID},
		CompensatableOrderAmount: compensatableOrderAmount,
		PaymentInformationID:     input.PaymentInformationID,
		VatNumber:                input.VatNumber,
	}

	inserted, err := r.Store.InsertOrder(ctx, order)
	if err != nil {
		return nil, errors.New("Adding order failed in MongoDB.")
	}
	return toOrderModel(inserted), nil
}

// PlaceOrder is the resolver for the placeOrder field.
func (r *mutationResolver) PlaceOrder(ctx context.Context, input PlaceOrderInput) (*Order, error) {
	order, err := r.Store.GetOrder(ctx, input.ID)
	if err != nil {
		return nil, orderNotFound(input.ID)
	}
	if err := authorizeUser(ctx, order.User.ID); err != nil {
		return nil, err
	}

	paymentAuthorization := buildPaymentAuthorization(input.PaymentAuthorization)

	if err := r.setStatusPlaced(ctx, input.ID); err != nil {
		return nil, err
	}

	placed, err := r.Store.GetOrder(ctx, input.ID)
	if err != nil {
		return nil, orderNotFound(input.ID)
	}

	dto, err := toOrderDTO(placed, paymentAuthorization)
	if err != nil {
		return nil, err
	}
	if err := r.Publisher.PublishOrderCreated(ctx, dto); err != nil {
		return nil, err
	}
	return toOrderModel(placed), nil
}

// User is the resolver for the user field (in-memory; no auth, no DB).
func (r *orderResolver) User(ctx context.Context, obj *Order) (*User, error) {
	return &User{ID: obj.UserID}, nil
}

// InvoiceAddress is the resolver for the invoiceAddress field (in-memory).
func (r *orderResolver) InvoiceAddress(ctx context.Context, obj *Order) (*UserAddress, error) {
	return &UserAddress{ID: obj.InvoiceAddressID}, nil
}

// OrderItems is the resolver for the orderItems field. In-memory pagination over
// the embedded items, sorted by _id per direction. No DB call, no auth.
func (r *orderResolver) OrderItems(ctx context.Context, obj *Order, first *int, skip *int, orderBy *CommonOrderInput) (*OrderItemConnection, error) {
	if err := checkPagination(first, skip); err != nil {
		return nil, err
	}
	nodes, hasNext, total := paginateInMemory(obj.InternalOrderItems, first, skip, orderBy, func(oi *OrderItem) uuid.UUID { return oi.ID })
	out := make([]OrderItem, len(nodes))
	for i := range nodes {
		out[i] = *nodes[i]
	}
	return &OrderItemConnection{Nodes: out, HasNextPage: hasNext, TotalCount: total}, nil
}

// ProductVariant is the resolver for the productVariant field (in-memory).
func (r *orderItemResolver) ProductVariant(ctx context.Context, obj *OrderItem) (*ProductVariant, error) {
	return &ProductVariant{ID: obj.ProductVariantID}, nil
}

// ProductVariantVersion is the resolver for the productVariantVersion field.
func (r *orderItemResolver) ProductVariantVersion(ctx context.Context, obj *OrderItem) (*ProductVariantVersion, error) {
	return &ProductVariantVersion{ID: obj.ProductVariantVersionID}, nil
}

// TaxRateVersion is the resolver for the taxRateVersion field.
func (r *orderItemResolver) TaxRateVersion(ctx context.Context, obj *OrderItem) (*TaxRateVersion, error) {
	return &TaxRateVersion{ID: obj.TaxRateVersionID}, nil
}

// ShoppingCartItem is the resolver for the shoppingCartItem field.
func (r *orderItemResolver) ShoppingCartItem(ctx context.Context, obj *OrderItem) (*ShoppingCartItem, error) {
	return &ShoppingCartItem{ID: obj.ShoppingCartItemID}, nil
}

// ShipmentMethod is the resolver for the shipmentMethod field.
func (r *orderItemResolver) ShipmentMethod(ctx context.Context, obj *OrderItem) (*ShipmentMethod, error) {
	return &ShipmentMethod{ID: obj.ShipmentMethodID}, nil
}

// Discounts is the resolver for the discounts field. In-memory pagination over
// the applied-discount ids, sorted by _id per direction.
func (r *orderItemResolver) Discounts(ctx context.Context, obj *OrderItem, first *int, skip *int, orderBy *CommonOrderInput) (*DiscountConnection, error) {
	if err := checkPagination(first, skip); err != nil {
		return nil, err
	}
	nodes, hasNext, total := paginateInMemory(obj.InternalDiscounts, first, skip, orderBy, func(id uuid.UUID) uuid.UUID { return id })
	out := make([]Discount, len(nodes))
	for i := range nodes {
		out[i] = Discount{ID: nodes[i]}
	}
	return &DiscountConnection{Nodes: out, HasNextPage: hasNext, TotalCount: total}, nil
}

// Order is the resolver for the order field. Fetch by id (error if missing),
// then authorize as the owner or a permissive role.
func (r *queryResolver) Order(ctx context.Context, id uuid.UUID) (*Order, error) {
	order, err := r.Store.GetOrder(ctx, id)
	if err != nil {
		return nil, orderNotFound(id)
	}
	if err := authorizeUser(ctx, order.User.ID); err != nil {
		return nil, err
	}
	return toOrderModel(order), nil
}

// OrderItem is the resolver for the orderItem field. It reads the (never-written)
// order_items collection first — which typically 404s — then looks up the owning
// order (via the embedded array) for authorization. Reproduced verbatim.
func (r *queryResolver) OrderItem(ctx context.Context, id uuid.UUID) (*OrderItem, error) {
	item, err := r.Store.GetOrderItemFromCollection(ctx, id)
	if err != nil {
		return nil, orderItemNotFound(id)
	}
	owner, err := r.Store.GetOrderByEmbeddedItemID(ctx, id)
	if err != nil {
		return nil, orderItemNotFound(id)
	}
	if err := authorizeUser(ctx, owner.User.ID); err != nil {
		return nil, err
	}
	return toOrderItemModel(item), nil
}

// Orders is the resolver for the orders field (User.orders). DB-backed
// pagination; authorization runs FIRST (before any DB access).
func (r *userResolver) Orders(ctx context.Context, obj *User, first *int, skip *int, orderBy *OrderOrderInput) (*OrderConnection, error) {
	if err := authorizeUser(ctx, obj.ID); err != nil {
		return nil, err
	}
	if err := checkPagination(first, skip); err != nil {
		return nil, err
	}

	var field *OrderOrderField
	var direction *OrderDirection
	if orderBy != nil {
		field = orderBy.Field
		direction = orderBy.Direction
	}
	sortField := orderOrderField(field)
	sortDir := orderDirectionInt(direction)

	var skip64, first64 *int64
	if skip != nil {
		v := int64(*skip)
		skip64 = &v
	}
	if first != nil {
		v := int64(*first)
		first64 = &v
	}

	page, err := r.Store.ListOrdersByUser(ctx, obj.ID, sortField, sortDir, skip64, first64)
	if err != nil {
		return nil, errors.New("Retrieving orders failed in MongoDB.")
	}

	nodes := make([]Order, len(page.Nodes))
	for i := range page.Nodes {
		nodes[i] = *toOrderModel(page.Nodes[i])
	}
	return &OrderConnection{Nodes: nodes, HasNextPage: page.HasNextPage, TotalCount: int(page.TotalCount)}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

// OrderItem returns OrderItemResolver implementation.
func (r *Resolver) OrderItem() OrderItemResolver { return &orderItemResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type (
	mutationResolver  struct{ *Resolver }
	orderResolver     struct{ *Resolver }
	orderItemResolver struct{ *Resolver }
	queryResolver     struct{ *Resolver }
	userResolver      struct{ *Resolver }
)
