package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"
)

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	// UserResolver constructs User(uuid) directly: no DB lookup, no existence
	// check, no authorization (the gateway path is trusted). All other User
	// fields resolve in the user subgraph.
	return &User{ID: id}, nil
}

// FindUserAddressByID is the resolver for the findUserAddressByID field.
func (r *entityResolver) FindUserAddressByID(ctx context.Context, id uuid.UUID) (*UserAddress, error) {
	// UserAddressResolver loads via the address data loader and returns the row
	// only if it is a user address (`as? UserAddress`), else null. An unknown id
	// surfaces as an error (the loader asserted non-null). No authorization.
	address, err := r.Store.GetAddress(ctx, id)
	if err != nil {
		return nil, err
	}
	if address.IsVendor() {
		return nil, nil
	}
	return toUserAddress(address), nil
}

// FindVendorAddressByID is the resolver for the findVendorAddressByID field.
func (r *entityResolver) FindVendorAddressByID(ctx context.Context, id uuid.UUID) (*VendorAddress, error) {
	// VendorAddressResolver: same as above but returns the row only if it is a
	// vendor address (`as? VendorAddress`), else null.
	address, err := r.Store.GetAddress(ctx, id)
	if err != nil {
		return nil, err
	}
	if !address.IsVendor() {
		return nil, nil
	}
	return toVendorAddress(address), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
