// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// An address.
type Address interface {
	IsNode()
	IsAddress()
}

// An object with an ID.
type Node interface {
	IsNode()
}

// Input for the archiveUserAddress mutation.
type ArchiveUserAddressInput struct {
	// The id of the user address to archive.
	ID uuid.UUID `json:"id"`
}

// Input for the createUserAddress mutation.
type CreateUserAddressInput struct {
	// The city part of the address to create
	City string `json:"city"`
	// The company name part of the address to create
	CompanyName *string `json:"companyName,omitempty"`
	// The country part of the address to create
	Country string `json:"country"`
	// The name of the address to create
	Name *NameInput `json:"name,omitempty"`
	// The postal code part of the address to create
	PostalCode string `json:"postalCode"`
	// The first part of the street part of the address to create
	Street1 string `json:"street1"`
	// The second part of the street part of the address to create
	Street2 string `json:"street2"`
	// The id of the user to create the address for.
	UserID uuid.UUID `json:"userId"`
}

// Input for the createVendorAddress mutation.
type CreateVendorAddressInput struct {
	// The city part of the address to create
	City string `json:"city"`
	// The company name part of the address to create
	CompanyName *string `json:"companyName,omitempty"`
	// The country part of the address to create
	Country string `json:"country"`
	// The name of the address to create
	Name *NameInput `json:"name,omitempty"`
	// The postal code part of the address to create
	PostalCode string `json:"postalCode"`
	// The first part of the street part of the address to create
	Street1 string `json:"street1"`
	// The second part of the street part of the address to create
	Street2 string `json:"street2"`
}

type Mutation struct {
}

// A name consisting of a firstName and lastName.
type Name struct {
	// The first name of the user
	FirstName string `json:"firstName"`
	// The last name of the user
	LastName string `json:"lastName"`
}

// A name consisting of a firstName and lastName.
type NameInput struct {
	// The first name of the user
	FirstName string `json:"firstName"`
	// The last name of the user
	LastName string `json:"lastName"`
}

type Query struct {
}

// A user.
type User struct {
	// Get all address the user received
	Addresses *UserAddressConnection `json:"addresses"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
}

func (User) IsNode() {}

func (User) IsEntity() {}

// A address associated with a user.
type UserAddress struct {
	// If this address is archived, the datetime it was archived.
	ArchivedAt *time.Time `json:"archivedAt,omitempty"`
	// The city part of the address
	City string `json:"city"`
	// The company name part of the address
	CompanyName *string `json:"companyName,omitempty"`
	// The country part of the address
	Country string `json:"country"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// If true, this address is archived and can no longer be used.
	IsArchived bool `json:"isArchived"`
	// The name of the address
	Name *Name `json:"name,omitempty"`
	// The postal code part of the address
	PostalCode string `json:"postalCode"`
	// The first part of the street part of the address
	Street1 string `json:"street1"`
	// The second part of the street part of the address
	Street2 string `json:"street2"`
	// The user this address belongs to.
	User   *User     `json:"user"`
	UserID uuid.UUID `json:"-"`
}

func (UserAddress) IsAddress() {}

func (UserAddress) IsNode() {}

func (UserAddress) IsEntity() {}

// A connection to a list of `Address` values.
type UserAddressConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []UserAddress `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// User address filter
type UserAddressFilterInput struct {
	IsArchived *bool `json:"isArchived,omitempty"`
}

// User address order
type UserAddressOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *UserAddressOrderField `json:"field,omitempty"`
}

// An address associated with the vendor.
type VendorAddress struct {
	// The city part of the address
	City string `json:"city"`
	// The company name part of the address
	CompanyName *string `json:"companyName,omitempty"`
	// The country part of the address
	Country string `json:"country"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The name of the address
	Name *Name `json:"name,omitempty"`
	// The postal code part of the address
	PostalCode string `json:"postalCode"`
	// The first part of the street part of the address
	Street1 string `json:"street1"`
	// The second part of the street part of the address
	Street2 string `json:"street2"`
}

func (VendorAddress) IsAddress() {}

func (VendorAddress) IsNode() {}

func (VendorAddress) IsEntity() {}

// Order direction
type OrderDirection string

const (
	// Ascending order
	OrderDirectionAsc OrderDirection = "ASC"
	// Descending order
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// User address order fields
type UserAddressOrderField string

const (
	// Order addresss by their id
	UserAddressOrderFieldID UserAddressOrderField = "ID"
)

var AllUserAddressOrderField = []UserAddressOrderField{
	UserAddressOrderFieldID,
}

func (e UserAddressOrderField) IsValid() bool {
	switch e {
	case UserAddressOrderFieldID:
		return true
	}
	return false
}

func (e UserAddressOrderField) String() string {
	return string(e)
}

func (e *UserAddressOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserAddressOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserAddressOrderField", str)
	}
	return nil
}

func (e UserAddressOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserAddressOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserAddressOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
