package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"misarch/address/events"
	"time"

	"github.com/google/uuid"
)

// ArchiveUserAddress is the resolver for the archiveUserAddress field.
func (r *mutationResolver) ArchiveUserAddress(ctx context.Context, input ArchiveUserAddressInput) (*UserAddress, error) {
	// Order matters (UserAddressService.archiveUserAddress): load first, so a
	// missing id errors before any auth check.
	address, err := r.Store.GetAddress(ctx, input.ID)
	if err != nil {
		return nil, err
	}
	// Require a header; if the caller is not the owner, require employee/admin.
	// A vendor row (userid IS NULL) can never match the caller, so this always
	// demands employee/admin for it.
	u, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if address.UserID == nil || *address.UserID != u.ID {
		if err := checkIsEmployee(u); err != nil {
			return nil, err
		}
	}
	// Vendor id: the original updated the row then crashed building the event
	// (userId!!), rolling the transaction back — net effect is a GraphQL error
	// with no DB change and no event. Reproduce that by erroring before any
	// write or publish.
	if address.UserID == nil {
		return nil, fmt.Errorf("cannot archive a vendor address")
	}

	archivedAt := time.Now()
	if err := r.Store.ArchiveAddress(ctx, address.ID, archivedAt); err != nil {
		return nil, err
	}
	address.ArchivedAt = &archivedAt

	if err := events.PublishUserAddressArchived(ctx, r.Dapr, events.UserAddressArchived{
		ID:     address.ID,
		UserID: *address.UserID,
	}); err != nil {
		return nil, err
	}

	return toUserAddress(address), nil
}

// CreateUserAddress is the resolver for the createUserAddress field.
func (r *mutationResolver) CreateUserAddress(ctx context.Context, input CreateUserAddressInput) (*UserAddress, error) {
	// Auth precedes the user-existence check (Mutation.createUserAddress checks
	// permissions before the service touches the repository).
	if _, err := requireSelfOrEmployee(ctx, input.UserID); err != nil {
		return nil, err
	}

	exists, err := r.Store.UserExists(ctx, input.UserID)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, fmt.Errorf("User with id %s does not exist", input.UserID)
	}

	var first, last *string
	if input.Name != nil {
		first = &input.Name.FirstName
		last = &input.Name.LastName
	}
	userID := input.UserID
	address, err := r.Store.CreateAddress(
		ctx, first, last, input.Street1, input.Street2, input.City,
		input.PostalCode, input.Country, input.CompanyName, &userID,
	)
	if err != nil {
		return nil, err
	}

	if err := events.PublishUserAddressCreated(ctx, r.Dapr, events.UserAddressCreated{
		ID:          address.ID,
		Name:        eventName(address.FirstName, address.LastName),
		Street1:     address.Street1,
		Street2:     address.Street2,
		City:        address.City,
		PostalCode:  address.PostalCode,
		Country:     address.Country,
		CompanyName: address.CompanyName,
		UserID:      *address.UserID,
	}); err != nil {
		return nil, err
	}

	return toUserAddress(address), nil
}

// CreateVendorAddress is the resolver for the createVendorAddress field.
func (r *mutationResolver) CreateVendorAddress(ctx context.Context, input CreateVendorAddressInput) (*VendorAddress, error) {
	// Requires a header AND employee/admin (dfe.authorizedUser.checkIsEmployee()).
	u, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := checkIsEmployee(u); err != nil {
		return nil, err
	}

	var first, last *string
	if input.Name != nil {
		first = &input.Name.FirstName
		last = &input.Name.LastName
	}
	address, err := r.Store.CreateAddress(
		ctx, first, last, input.Street1, input.Street2, input.City,
		input.PostalCode, input.Country, input.CompanyName, nil,
	)
	if err != nil {
		return nil, err
	}

	if err := events.PublishVendorAddressCreated(ctx, r.Dapr, events.VendorAddressCreated{
		ID:          address.ID,
		Name:        eventName(address.FirstName, address.LastName),
		Street1:     address.Street1,
		Street2:     address.Street2,
		City:        address.City,
		PostalCode:  address.PostalCode,
		Country:     address.Country,
		CompanyName: address.CompanyName,
	}); err != nil {
		return nil, err
	}

	return toVendorAddress(address), nil
}

// Address is the resolver for the address field.
func (r *queryResolver) Address(ctx context.Context, id uuid.UUID) (Address, error) {
	address, err := r.Store.GetAddress(ctx, id)
	if err != nil {
		return nil, err
	}
	// Vendor addresses need no authorization. For a user address, require the
	// header and — unless the caller owns it — employee/admin.
	if !address.IsVendor() {
		u, err := requireUser(ctx)
		if err != nil {
			return nil, err
		}
		if address.UserID == nil || *address.UserID != u.ID {
			if err := checkIsEmployee(u); err != nil {
				return nil, err
			}
		}
	}
	return toAddress(address), nil
}

// VendorAddress is the resolver for the vendorAddress field.
func (r *queryResolver) VendorAddress(ctx context.Context) (*VendorAddress, error) {
	// No authorization. Returns the highest-version vendor row, or null when no
	// vendor address exists yet.
	address, ok, err := r.Store.CurrentVendorAddress(ctx)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	return toVendorAddress(address), nil
}

// Addresses is the resolver for the addresses field.
func (r *userResolver) Addresses(ctx context.Context, obj *User, filter *UserAddressFilterInput, first *int, orderBy *UserAddressOrderInput, skip *int) (*UserAddressConnection, error) {
	// Require the header; unless the caller is this user, require employee/admin.
	if _, err := requireSelfOrEmployee(ctx, obj.ID); err != nil {
		return nil, err
	}
	col, asc := addressOrder(orderBy)
	conn, err := r.Store.ListUserAddresses(ctx, obj.ID, archivedFilter(filter), first, skip, col, asc)
	if err != nil {
		return nil, err
	}
	return toUserAddressConnection(conn), nil
}

// User is the resolver for the user field.
func (r *userAddressResolver) User(ctx context.Context, obj *UserAddress) (*User, error) {
	// The original loaded the UserEntity via a data loader whose DTO is just
	// User(id); every other User field is resolved by the user subgraph. No
	// authorization beyond how the parent address was obtained. Construct the
	// entity reference directly from the FK the parent carries.
	return &User{ID: obj.UserID}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

// UserAddress returns UserAddressResolver implementation.
func (r *Resolver) UserAddress() UserAddressResolver { return &userAddressResolver{r} }

type (
	mutationResolver    struct{ *Resolver }
	queryResolver       struct{ *Resolver }
	userResolver        struct{ *Resolver }
	userAddressResolver struct{ *Resolver }
)
