package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"

	"github.com/google/uuid"
)

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	panic(fmt.Errorf("not implemented: FindUserByID - findUserByID"))
}

// FindWishlistByID is the resolver for the findWishlistByID field.
func (r *entityResolver) FindWishlistByID(ctx context.Context, id uuid.UUID) (*Wishlist, error) {
	panic(fmt.Errorf("not implemented: FindWishlistByID - findWishlistByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
