// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// Specifies the order of foreign types.
type CommonOrderInput struct {
	// Order direction of wishlists.
	Direction *OrderDirection `json:"direction,omitempty"`
	// Field that wishlists should be ordered by.
	Field *CommonOrderField `json:"field,omitempty"`
}

type CreateWishlistInput struct {
	// UUID of user owning the wishlist.
	UserID uuid.UUID `json:"userId"`
	// UUIDs of product variants in wishlist.
	ProductVariantIds []uuid.UUID `json:"productVariantIds"`
	// Wishlist name.
	Name string `json:"name"`
}

type Mutation struct {
}

// Foreign type of a product variant.
type ProductVariant struct {
	// UUID of the product variant.
	ID uuid.UUID `json:"id"`
}

func (ProductVariant) IsEntity() {}

// A connection of product variants.
type ProductVariantConnection struct {
	// The resulting entities.
	Nodes []ProductVariant `json:"nodes"`
	// Whether this connection has a next page.
	HasNextPage bool `json:"hasNextPage"`
	// The total amount of items in this connection.
	TotalCount int `json:"totalCount"`
}

type Query struct {
}

type UpdateWishlistInput struct {
	// UUID of wishlist to update.
	ID uuid.UUID `json:"id"`
	// product variant UUIDs of wishlist to update
	ProductVariantIds []uuid.UUID `json:"productVariantIds,omitempty"`
	// Wishlist name to update
	Name *string `json:"name,omitempty"`
}

// Type of a user owning wishlists.
type User struct {
	// UUID of the user.
	ID uuid.UUID `json:"id"`
	// Retrieves wishlists of user.
	Wishlists *WishlistConnection `json:"wishlists"`
}

func (User) IsEntity() {}

// The wishlist of a user.
type Wishlist struct {
	// Wishlist UUID.
	ID uuid.UUID `json:"id"`
	// User.
	User *User `json:"user"`
	// Name of wishlist.
	Name string `json:"name"`
	// Timestamp when wishlist was created.
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when wishlist was last updated.
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`
	// Retrieves product variants.
	ProductVariants   *ProductVariantConnection `json:"productVariants"`
	ProductVariantIDs []uuid.UUID               `json:"-"`
	UserID            uuid.UUID                 `json:"-"`
}

func (Wishlist) IsEntity() {}

// A connection of wishlists.
type WishlistConnection struct {
	// The resulting entities.
	Nodes []Wishlist `json:"nodes"`
	// Whether this connection has a next page.
	HasNextPage bool `json:"hasNextPage"`
	// The total amount of items in this connection.
	TotalCount int `json:"totalCount"`
}

// Specifies the order of wishlists.
type WishlistOrderInput struct {
	// Order direction of wishlists.
	Direction *OrderDirection `json:"direction,omitempty"`
	// Field that wishlists should be ordered by.
	Field *WishlistOrderField `json:"field,omitempty"`
}

// Describes the fields that a foreign types can be ordered by.
type CommonOrderField string

const (
	// Orders by "id".
	CommonOrderFieldID CommonOrderField = "ID"
)

var AllCommonOrderField = []CommonOrderField{
	CommonOrderFieldID,
}

func (e CommonOrderField) IsValid() bool {
	switch e {
	case CommonOrderFieldID:
		return true
	}
	return false
}

func (e CommonOrderField) String() string {
	return string(e)
}

func (e *CommonOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommonOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommonOrderField", str)
	}
	return nil
}

func (e CommonOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommonOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommonOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// GraphQL order direction.
type OrderDirection string

const (
	// Ascending order direction.
	OrderDirectionAsc OrderDirection = "ASC"
	// Descending order direction.
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Describes the fields that a wishlist can be ordered by.
type WishlistOrderField string

const (
	// Orders by "id".
	WishlistOrderFieldID WishlistOrderField = "ID"
	// Orders by "user_id".
	WishlistOrderFieldUserID WishlistOrderField = "USER_ID"
	// Orders by "name".
	WishlistOrderFieldName WishlistOrderField = "NAME"
	// Orders by "created_at".
	WishlistOrderFieldCreatedAt WishlistOrderField = "CREATED_AT"
	// Orders by "last_updated_at".
	WishlistOrderFieldLastUpdatedAt WishlistOrderField = "LAST_UPDATED_AT"
)

var AllWishlistOrderField = []WishlistOrderField{
	WishlistOrderFieldID,
	WishlistOrderFieldUserID,
	WishlistOrderFieldName,
	WishlistOrderFieldCreatedAt,
	WishlistOrderFieldLastUpdatedAt,
}

func (e WishlistOrderField) IsValid() bool {
	switch e {
	case WishlistOrderFieldID, WishlistOrderFieldUserID, WishlistOrderFieldName, WishlistOrderFieldCreatedAt, WishlistOrderFieldLastUpdatedAt:
		return true
	}
	return false
}

func (e WishlistOrderField) String() string {
	return string(e)
}

func (e *WishlistOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WishlistOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WishlistOrderField", str)
	}
	return nil
}

func (e WishlistOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WishlistOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WishlistOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
