package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"

	"github.com/google/uuid"
)

// CreateWishlist is the resolver for the createWishlist field.
func (r *mutationResolver) CreateWishlist(ctx context.Context, input CreateWishlistInput) (*Wishlist, error) {
	panic(fmt.Errorf("not implemented: CreateWishlist - createWishlist"))
}

// UpdateWishlist is the resolver for the updateWishlist field.
func (r *mutationResolver) UpdateWishlist(ctx context.Context, input UpdateWishlistInput) (*Wishlist, error) {
	panic(fmt.Errorf("not implemented: UpdateWishlist - updateWishlist"))
}

// DeleteWishlist is the resolver for the deleteWishlist field.
func (r *mutationResolver) DeleteWishlist(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteWishlist - deleteWishlist"))
}

// Wishlist is the resolver for the wishlist field.
func (r *queryResolver) Wishlist(ctx context.Context, id uuid.UUID) (*Wishlist, error) {
	panic(fmt.Errorf("not implemented: Wishlist - wishlist"))
}

// Wishlists is the resolver for the wishlists field.
func (r *userResolver) Wishlists(ctx context.Context, obj *User, first *int, skip *int, orderBy *WishlistOrderInput) (*WishlistConnection, error) {
	panic(fmt.Errorf("not implemented: Wishlists - wishlists"))
}

// User is the resolver for the user field.
func (r *wishlistResolver) User(ctx context.Context, obj *Wishlist) (*User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// ProductVariants is the resolver for the productVariants field.
func (r *wishlistResolver) ProductVariants(ctx context.Context, obj *Wishlist, first *int, skip *int, orderBy *CommonOrderInput) (*ProductVariantConnection, error) {
	panic(fmt.Errorf("not implemented: ProductVariants - productVariants"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

// Wishlist returns WishlistResolver implementation.
func (r *Resolver) Wishlist() WishlistResolver { return &wishlistResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	userResolver     struct{ *Resolver }
	wishlistResolver struct{ *Resolver }
)
