package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"
)

// FindProductByID is the resolver for the findProductByID field.
func (r *entityResolver) FindProductByID(ctx context.Context, id uuid.UUID) (*Product, error) {
	// query_object_optional: a miss returns nil (entities are nullable in the
	// _Entity union); only a Mongo transport error surfaces as an error.
	p, found, err := r.Store.FindProduct(ctx, id)
	if err != nil {
		return nil, errNotFound("Product", id)
	}
	if !found {
		return nil, nil
	}
	return &Product{ID: p.ID}, nil
}

// FindProductVariantByID is the resolver for the findProductVariantByID field.
func (r *entityResolver) FindProductVariantByID(ctx context.Context, id uuid.UUID) (*ProductVariant, error) {
	pv, found, err := r.Store.GetProductVariant(ctx, id)
	if err != nil {
		return nil, errProductVariantNotFound(id)
	}
	if !found {
		return nil, nil
	}
	return &ProductVariant{ID: pv.ID}, nil
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	u, found, err := r.Store.FindUser(ctx, id)
	if err != nil {
		return nil, errUserNotFound(id)
	}
	if !found {
		return nil, nil
	}
	return &User{ID: u.ID}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
