// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type CreateReviewInput struct {
	// UUID of user owning the review.
	UserID uuid.UUID `json:"userId"`
	// UUID of product variant in review.
	ProductVariantID uuid.UUID `json:"productVariantId"`
	// Body of review.
	Body string `json:"body"`
	// Rating of review in 1-5 stars.
	Rating Rating `json:"rating"`
	// Flag if review is visible, by default set to true.
	IsVisible *bool `json:"isVisible,omitempty"`
}

type Mutation struct {
}

type Product struct {
	// UUID of the product.
	ID uuid.UUID `json:"id"`
	// Retrieves reviews of product.
	Reviews *ReviewConnection `json:"reviews"`
	// Retrieves average rating of product.
	AverageRating float64 `json:"averageRating"`
}

func (Product) IsEntity() {}

type ProductVariant struct {
	// Product variant UUID.
	ID uuid.UUID `json:"id"`
	// Retrieves reviews of product variant.
	Reviews *ReviewConnection `json:"reviews"`
	// Retrieves average rating of product variant.
	AverageRating float64 `json:"averageRating"`
}

func (ProductVariant) IsEntity() {}

type Query struct {
}

// The review of a user.
type Review struct {
	// review UUID.
	ID uuid.UUID `json:"id"`
	// User.
	User *User `json:"user"`
	// Product variant that review is about.
	ProductVariant *ProductVariant `json:"productVariant"`
	// Body of review.
	Body string `json:"body"`
	// Rating of review in 1-5 stars.
	Rating Rating `json:"rating"`
	// Timestamp when review was created.
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when review was created.
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`
	// Flag if review is visible,
	IsVisible        bool      `json:"isVisible"`
	ProductID        uuid.UUID `json:"-"`
	ProductVariantID uuid.UUID `json:"-"`
	UserID           uuid.UUID `json:"-"`
}

// A connection of reviews.
type ReviewConnection struct {
	// The resulting entities.
	Nodes []Review `json:"nodes"`
	// Whether this connection has a next page.
	HasNextPage bool `json:"hasNextPage"`
	// The total amount of items in this connection.
	TotalCount int `json:"totalCount"`
}

// Specifies the order of reviews.
type ReviewOrderInput struct {
	// Order direction of reviews.
	Direction *OrderDirection `json:"direction,omitempty"`
	// Field that reviews should be ordered by.
	Field *ReviewOrderField `json:"field,omitempty"`
}

type UpdateReviewInput struct {
	// UUID of review to update.
	ID uuid.UUID `json:"id"`
	// Body of review to update.
	Body *string `json:"body,omitempty"`
	// Rating of review in 1-5 stars to update.
	Rating *Rating `json:"rating,omitempty"`
	// Flag if review is visible.
	IsVisible *bool `json:"isVisible,omitempty"`
}

// Type of a user owning reviews.
type User struct {
	// UUID of the user.
	ID uuid.UUID `json:"id"`
	// Retrieves reviews of user.
	Reviews *ReviewConnection `json:"reviews"`
}

func (User) IsEntity() {}

// GraphQL order direction.
type OrderDirection string

const (
	// Ascending order direction.
	OrderDirectionAsc OrderDirection = "ASC"
	// Descending order direction.
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Rating string

const (
	RatingOneStars   Rating = "ONE_STARS"
	RatingTwoStars   Rating = "TWO_STARS"
	RatingThreeStars Rating = "THREE_STARS"
	RatingFourStars  Rating = "FOUR_STARS"
	RatingFiveStars  Rating = "FIVE_STARS"
)

var AllRating = []Rating{
	RatingOneStars,
	RatingTwoStars,
	RatingThreeStars,
	RatingFourStars,
	RatingFiveStars,
}

func (e Rating) IsValid() bool {
	switch e {
	case RatingOneStars, RatingTwoStars, RatingThreeStars, RatingFourStars, RatingFiveStars:
		return true
	}
	return false
}

func (e Rating) String() string {
	return string(e)
}

func (e *Rating) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Rating(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Rating", str)
	}
	return nil
}

func (e Rating) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Rating) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Rating) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Describes the fields that a review can be ordered by.
type ReviewOrderField string

const (
	// Orders by "id".
	ReviewOrderFieldID ReviewOrderField = "ID"
	// Orders by "user_id".
	ReviewOrderFieldUserID ReviewOrderField = "USER_ID"
	// Orders by "product_variant".
	ReviewOrderFieldProductVariant ReviewOrderField = "PRODUCT_VARIANT"
	// Orders by "rating".
	ReviewOrderFieldRating ReviewOrderField = "RATING"
	// Orders by "created_at".
	ReviewOrderFieldCreatedAt ReviewOrderField = "CREATED_AT"
)

var AllReviewOrderField = []ReviewOrderField{
	ReviewOrderFieldID,
	ReviewOrderFieldUserID,
	ReviewOrderFieldProductVariant,
	ReviewOrderFieldRating,
	ReviewOrderFieldCreatedAt,
}

func (e ReviewOrderField) IsValid() bool {
	switch e {
	case ReviewOrderFieldID, ReviewOrderFieldUserID, ReviewOrderFieldProductVariant, ReviewOrderFieldRating, ReviewOrderFieldCreatedAt:
		return true
	}
	return false
}

func (e ReviewOrderField) String() string {
	return string(e)
}

func (e *ReviewOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReviewOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReviewOrderField", str)
	}
	return nil
}

func (e ReviewOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReviewOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReviewOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
