package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"

	"misarch/review/store"
)

// CreateReview is the resolver for the createReview field.
func (r *mutationResolver) CreateReview(ctx context.Context, input CreateReviewInput) (*Review, error) {
	// 1. Authorize first (before touching the DB): admin/employee, or caller is
	//    input.userId.
	if err := authorizeUser(ctx, &input.UserID); err != nil {
		return nil, err
	}

	// 3a. Validate the product variant exists locally (shadow collection).
	pvExists, err := r.Store.ProductVariantExists(ctx, input.ProductVariantID)
	if err != nil || !pvExists {
		return nil, errProductVariantNotPresent(input.ProductVariantID)
	}
	// 3b. Validate the user exists locally.
	userExists, err := r.Store.UserExists(ctx, input.UserID)
	if err != nil || !userExists {
		return nil, errUserNotFound(input.UserID)
	}

	// 4. Server timestamp (UTC, ms precision on write).
	currentTimestamp := store.Now()

	// 5. Re-fetch the full product variant to embed its product_id.
	pv, found, err := r.Store.GetProductVariant(ctx, input.ProductVariantID)
	if err != nil || !found {
		return nil, errProductVariantNotFound(input.ProductVariantID)
	}

	// 6. Build the review with a fresh v4 UUID; isVisible defaults to true.
	isVisible := true
	if input.IsVisible != nil {
		isVisible = *input.IsVisible
	}
	doc := store.Review{
		ID:             uuid.New(),
		User:           store.EmbeddedUser{ID: input.UserID},
		ProductVariant: store.EmbeddedProductVariant{ID: pv.ID, ProductID: pv.ProductID},
		Body:           input.Body,
		Rating:         ratingToStored(input.Rating),
		CreatedAt:      currentTimestamp,
		LastUpdatedAt:  currentTimestamp,
		IsVisible:      isVisible,
	}

	// 7 + 8. Uniqueness check then insert then re-fetch.
	created, err := r.Store.InsertReview(ctx, doc)
	if err != nil {
		if err == store.ErrReviewAlreadyExists {
			return nil, errAlreadyReviewed(input.UserID, input.ProductVariantID)
		}
		return nil, errAddingReview()
	}
	return toReview(created)
}

// UpdateReview is the resolver for the updateReview field.
func (r *mutationResolver) UpdateReview(ctx context.Context, input UpdateReviewInput) (*Review, error) {
	currentTimestamp := store.Now()

	// 2. Fetch BEFORE authorization so a non-existent id yields "not found"
	//    rather than an auth error.
	review, found, err := r.Store.FindReview(ctx, input.ID)
	if err != nil || !found {
		return nil, errReviewNotFound(input.ID)
	}

	// 3. Authorize against the owner of the existing review.
	owner := review.User.ID
	if err := authorizeUser(ctx, &owner); err != nil {
		return nil, err
	}

	// 4-6. Per-field updates: each provided field is its own $set that also
	//      bumps last_updated_at. No provided field => no writes (no-op).
	if input.Body != nil {
		if err := r.Store.SetReviewField(ctx, input.ID, "body", *input.Body, currentTimestamp); err != nil {
			return nil, errUpdatingBody(input.ID)
		}
	}
	if input.Rating != nil {
		if err := r.Store.SetReviewField(ctx, input.ID, "rating", ratingToStored(*input.Rating), currentTimestamp); err != nil {
			return nil, errUpdatingRating(input.ID)
		}
	}
	if input.IsVisible != nil {
		if err := r.Store.SetReviewField(ctx, input.ID, "is_visible", *input.IsVisible, currentTimestamp); err != nil {
			return nil, errUpdatingVisibility(input.ID)
		}
	}

	// 7. Re-fetch and return.
	updated, found, err := r.Store.FindReview(ctx, input.ID)
	if err != nil || !found {
		return nil, errReviewNotFound(input.ID)
	}
	return toReview(updated)
}

// DeleteReview is the resolver for the deleteReview field.
func (r *mutationResolver) DeleteReview(ctx context.Context, id uuid.UUID) (bool, error) {
	// 1. Fetch (not found before auth).
	review, found, err := r.Store.FindReview(ctx, id)
	if err != nil || !found {
		return false, errReviewNotFound(id)
	}
	// 2. Authorize against the owner.
	owner := review.User.ID
	if err := authorizeUser(ctx, &owner); err != nil {
		return false, err
	}
	// 3. Hard delete.
	if err := r.Store.DeleteReview(ctx, id); err != nil {
		return false, errDeletingReview(id)
	}
	return true, nil
}

// Reviews is the resolver for the reviews field.
func (r *productResolver) Reviews(ctx context.Context, obj *Product, first *int, skip *int, orderBy *ReviewOrderInput) (*ReviewConnection, error) {
	conn, err := r.Store.ListReviewsByProduct(ctx, obj.ID, reviewSort(orderBy), store.Page{First: first, Skip: skip})
	if err != nil {
		return nil, errRetrievingReviews()
	}
	return toReviewConnection(conn)
}

// AverageRating is the resolver for the averageRating field.
func (r *productResolver) AverageRating(ctx context.Context, obj *Product) (float64, error) {
	reviews, err := r.Store.AllReviewsByProduct(ctx, obj.ID)
	if err != nil {
		// The Rust average_rating swallows the reviews error into None, which
		// on a non-null field surfaces as a null-violation GraphQL error.
		return 0, errNoVisibleReviews("Product.averageRating")
	}
	return averageRating(reviews, "Product.averageRating")
}

// Reviews is the resolver for the reviews field.
func (r *productVariantResolver) Reviews(ctx context.Context, obj *ProductVariant, first *int, skip *int, orderBy *ReviewOrderInput) (*ReviewConnection, error) {
	conn, err := r.Store.ListReviewsByProductVariant(ctx, obj.ID, reviewSort(orderBy), store.Page{First: first, Skip: skip})
	if err != nil {
		return nil, errRetrievingReviews()
	}
	return toReviewConnection(conn)
}

// AverageRating is the resolver for the averageRating field.
func (r *productVariantResolver) AverageRating(ctx context.Context, obj *ProductVariant) (float64, error) {
	reviews, err := r.Store.AllReviewsByProductVariant(ctx, obj.ID)
	if err != nil {
		return 0, errNoVisibleReviews("ProductVariant.averageRating")
	}
	return averageRating(reviews, "ProductVariant.averageRating")
}

// Reviews is the resolver for the reviews field.
func (r *queryResolver) Reviews(ctx context.Context, first *int, skip *int, orderBy *ReviewOrderInput) (*ReviewConnection, error) {
	// Public: no authorization. Returns invisible reviews too.
	conn, err := r.Store.ListReviews(ctx, reviewSort(orderBy), store.Page{First: first, Skip: skip})
	if err != nil {
		return nil, errRetrievingReviews()
	}
	return toReviewConnection(conn)
}

// Review is the resolver for the review field.
func (r *queryResolver) Review(ctx context.Context, id uuid.UUID) (*Review, error) {
	// Public. query_object_optional: a miss returns Ok(None) (no error); the
	// non-null SDL field then makes gqlgen emit the null-violation error.
	// A Mongo transport error surfaces as "Review with UUID: `<id>` not found."
	review, found, err := r.Store.FindReview(ctx, id)
	if err != nil {
		return nil, errReviewNotFound(id)
	}
	if !found {
		return nil, nil
	}
	return toReview(review)
}

// User is the resolver for the user field.
func (r *reviewResolver) User(ctx context.Context, obj *Review) (*User, error) {
	// The review embeds only the user's id; resolve to a User entity stub.
	return &User{ID: obj.UserID}, nil
}

// ProductVariant is the resolver for the productVariant field.
func (r *reviewResolver) ProductVariant(ctx context.Context, obj *Review) (*ProductVariant, error) {
	// The review embeds {_id, product_id}; only _id is a GraphQL field. The
	// product_id rides along on the model (used for the Product join) but is
	// not exposed. Resolve to a ProductVariant entity stub.
	return &ProductVariant{ID: obj.ProductVariantID}, nil
}

// Reviews is the resolver for the reviews field.
func (r *userResolver) Reviews(ctx context.Context, obj *User, first *int, skip *int, orderBy *ReviewOrderInput) (*ReviewConnection, error) {
	conn, err := r.Store.ListReviewsByUser(ctx, obj.ID, reviewSort(orderBy), store.Page{First: first, Skip: skip})
	if err != nil {
		return nil, errRetrievingReviews()
	}
	return toReviewConnection(conn)
}

// averageRating computes the arithmetic mean of the numeric ratings (1..5) of
// the visible reviews. Zero visible reviews returns an error so the non-null
// GraphQL field surfaces the null-violation error (matching the original None).
func averageRating(reviews []store.Review, fieldPath string) (float64, error) {
	sum := 0
	count := 0
	for _, rv := range reviews {
		if !rv.IsVisible {
			continue
		}
		rating, err := ratingFromStored(rv.Rating)
		if err != nil {
			// A document whose rating cannot be read fails the whole field,
			// mirroring the Rust deserialization failure.
			return 0, err
		}
		sum += ratingDiscriminant(rating)
		count++
	}
	if count == 0 {
		return 0, errNoVisibleReviews(fieldPath)
	}
	return float64(sum) / float64(count), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

// ProductVariant returns ProductVariantResolver implementation.
func (r *Resolver) ProductVariant() ProductVariantResolver { return &productVariantResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Review returns ReviewResolver implementation.
func (r *Resolver) Review() ReviewResolver { return &reviewResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type (
	mutationResolver       struct{ *Resolver }
	productResolver        struct{ *Resolver }
	productVariantResolver struct{ *Resolver }
	queryResolver          struct{ *Resolver }
	reviewResolver         struct{ *Resolver }
	userResolver           struct{ *Resolver }
)
