extend schema @link(url: "https://specs.apollo.dev/federation/v2.5", import: ["@key", "@shareable", "@inaccessible"])

"""
Media object with associated path and id.
"""
type Media @key(fields: "id") {
	"""
	Media UUID.
	"""
	id: UUID!
	"""
	Pre-signed path for the media.
	"""
	path: String!
}
"""
A connection of medias.
"""
type MediaConnection @shareable {
	"""
	The resulting entities.
	"""
	nodes: [Media!]!
	"""
	Whether this connection has a next page.
	"""
	hasNextPage: Boolean!
	"""
	The total amount of items in this connection.
	"""
	totalCount: Int!
}
type Mutation {
	"""
	Uploads a media to MinIO.
	
	Saves the file under a new UUID with its suitable file extension in MinIO.
	Sends an event when a media file was uploaded.
	"""
	uploadMedia(
		"""
		Media file to upload.
		"""
		mediaFile: Upload!
	): UUID!
}
type Query {
	"""
	Returns all medias of the service.
	"""
	getMedias(
		"""
		Describes that the `first` N medias should be retrieved.
		"""
		first: Int

		"""
		Describes how many medias should be skipped at the beginning.
		"""
		skip: Int
	): MediaConnection!
}
scalar UUID
scalar Upload
