package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"errors"
	"misarch/invoice/store"

	"github.com/google/uuid"
)

// FindInvoiceByID is the resolver for the findInvoiceByID field.
func (r *entityResolver) FindInvoiceByID(ctx context.Context, id uuid.UUID) (*Invoice, error) {
	// Mirrors the Rust invoice_entity_resolver → query_object::<Invoice>: same
	// lookup and same not-found/driver-error message as Query.invoice.
	inv, err := r.Store.GetInvoice(ctx, id)
	if err != nil {
		return nil, invoiceNotFound(id)
	}
	return toInvoice(inv), nil
}

// FindOrderByID is the resolver for the findOrderByID field.
func (r *entityResolver) FindOrderByID(ctx context.Context, id uuid.UUID) (*Order, error) {
	// Mirrors the Rust order_entity_resolver → query_invoice_by_order_id:
	// find_one({order_id: id}) on invoices, wrap the invoice in Order{_id, invoice}.
	// Not found → the specific "order_id" message; a driver error propagates raw
	// (the original uses `?`, i.e. e.into(), for non-None errors here).
	inv, err := r.Store.GetInvoiceByOrderID(ctx, id)
	if err != nil {
		if errors.Is(err, store.ErrNoDocuments) {
			return nil, invoiceByOrderNotFound(id)
		}
		return nil, err
	}
	return &Order{ID: id, Invoice: toInvoice(inv)}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
