// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"

	"github.com/google/uuid"
)

// Invoice of an order.
type Invoice struct {
	ID            uuid.UUID      `json:"id"`
	OrderID       uuid.UUID      `json:"orderId"`
	IssuedAt      time.Time      `json:"issuedAt"`
	Content       string         `json:"content"`
	UserAddress   *UserAddress   `json:"userAddress"`
	VendorAddress *VendorAddress `json:"vendorAddress"`
	VatNumber     *string        `json:"vatNumber,omitempty"`
}

func (Invoice) IsEntity() {}

// Foreign type of an order.
type Order struct {
	// UUID of the order.
	ID uuid.UUID `json:"id"`
	// Invoice of the order.
	Invoice *Invoice `json:"invoice"`
}

func (Order) IsEntity() {}

type Query struct {
}

// Foreign type of a user address.
type UserAddress struct {
	ID uuid.UUID `json:"id"`
}

func (UserAddress) IsEntity() {}

// Foreign type of a vendor address.
type VendorAddress struct {
	ID uuid.UUID `json:"id"`
}

func (VendorAddress) IsEntity() {}
