package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"
)

// Invoice is the resolver for the invoice field.
func (r *queryResolver) Invoice(ctx context.Context, id uuid.UUID) (*Invoice, error) {
	// No auth (this subgraph is unauthenticated). Mirrors the Rust Query.invoice
	// → query_object::<Invoice>(collection, id): a find_one({_id: id}) whose
	// not-found AND driver errors both surface the same "... not found." message.
	inv, err := r.Store.GetInvoice(ctx, id)
	if err != nil {
		return nil, invoiceNotFound(id)
	}
	return toInvoice(inv), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
