package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
)

// FindProductItemByID is the resolver for the findProductItemByID field.
func (r *entityResolver) FindProductItemByID(ctx context.Context, id string) (*ProductItem, error) {
	// Entity resolution for ProductItem is unauthenticated in practice: the
	// original's @Roles decorator on @ResolveReference is not enforced by Nest's
	// enhancers (spec §3.2). Look the item up by _id; missing → the exact error
	// (that entity slot yields an error; other _entities slots still resolve).
	item, err := r.Store.FindByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if item == nil {
		return nil, fmt.Errorf("ProductItem with ID %q not found", id)
	}
	return toProductItem(*item), nil
}

// FindProductVariantByID is the resolver for the findProductVariantByID field.
func (r *entityResolver) FindProductVariantByID(ctx context.Context, id string) (*ProductVariant, error) {
	// No reference resolver existed in the original; Apollo returned the
	// representation itself, so resolution NEVER fails and does no DB check or
	// auth (spec §3.1). Unknown variants resolve with inventoryCount 0 / an empty
	// connection via the field resolvers.
	return &ProductVariant{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
