// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// The input of a product item batch creation
type CreateProductItemBatchInput struct {
	// The product variant id of the product item
	ProductVariantID string `json:"productVariantId"`
	// The number of products to add
	Number int `json:"number"`
}

type Mutation struct {
}

// A product Item of a product variant
type ProductItem struct {
	// The uuid identifier of the product item
	ID string `json:"id"`
	// The corresponding product variant
	ProductVariant *ProductVariant `json:"productVariant"`
	// Describes the inventory status of the product item
	InventoryStatus ProductItemStatus `json:"inventoryStatus"`
	// Reference to the order that reserved the product item
	OrderID          *string `json:"orderId,omitempty"`
	ProductVariantID string  `json:"-"`
}

func (ProductItem) IsEntity() {}

// A connection of product items
type ProductItemConnection struct {
	// The resulting items
	Nodes []ProductItem `json:"nodes,omitempty"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
}

// Filtering options for product items
type ProductItemFilter struct {
	// Linked product variant id
	ProductVariant *string `json:"productVariant,omitempty"`
	// Current product item status
	InventoryStatus *ProductItemStatus `json:"inventoryStatus,omitempty"`
}

// Filtering options for product items of product variants
type ProductItemOfProductVariantFilter struct {
	// Current product item status
	InventoryStatus *ProductItemStatus `json:"inventoryStatus,omitempty"`
}

// Ordering options for product items
type ProductItemOrder struct {
	// The field to order by
	Field *ProductItemOrderField `json:"field,omitempty"`
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
}

// Foreign type ProductVariant
type ProductVariant struct {
	// The uuid identifier of the product variant
	ID string `json:"id"`
	// A product item connection for referenced product items in stock
	ProductItems *ProductItemConnection `json:"productItems,omitempty"`
	// The number of product items in stock
	InventoryCount int `json:"inventoryCount"`
}

func (ProductVariant) IsEntity() {}

type Query struct {
}

// The input to reserve a batch of product items
type ReserveProductItemsBatchInput struct {
	// The product variant id of the product item
	ProductVariantID string `json:"productVariantId"`
	// The number of product items to reserve
	Number int `json:"number"`
	// The order id that reserves the product items
	OrderID string `json:"orderId"`
}

// The input of a product item update
type UpdateProductItemInput struct {
	// The product item identifier
	ID string `json:"id"`
	// The product variant id of the product item
	ProductVariantID string `json:"productVariantId"`
	// The inventory state of the product item
	InventoryStatus ProductItemStatus `json:"inventoryStatus"`
}

// The direction to order a list of items by
type OrderDirection string

const (
	// Ascending Order
	OrderDirectionAsc OrderDirection = "ASC"
	// Decending Order
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The field to order Product Items by
type ProductItemOrderField string

const (
	// Order Product Items by their ID
	ProductItemOrderFieldID ProductItemOrderField = "ID"
)

var AllProductItemOrderField = []ProductItemOrderField{
	ProductItemOrderFieldID,
}

func (e ProductItemOrderField) IsValid() bool {
	switch e {
	case ProductItemOrderFieldID:
		return true
	}
	return false
}

func (e ProductItemOrderField) String() string {
	return string(e)
}

func (e *ProductItemOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductItemOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductItemOrderField", str)
	}
	return nil
}

func (e ProductItemOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProductItemOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProductItemOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The status of an individual product item in the inventory
type ProductItemStatus string

const (
	// The item is in storage, not yet sold or reserved
	ProductItemStatusInStorage ProductItemStatus = "IN_STORAGE"
	// The item has been reserved for a customer but not yet sold
	ProductItemStatusReserved ProductItemStatus = "RESERVED"
	// The item is in the process of being fulfilled (packed, shipped)
	ProductItemStatusInFulfillment ProductItemStatus = "IN_FULFILLMENT"
	// The item has been shipped to the customer
	ProductItemStatusShipped ProductItemStatus = "SHIPPED"
	// The item has been delivered to the customer
	ProductItemStatusDelivered ProductItemStatus = "DELIVERED"
	// The item has been returned by the customer
	ProductItemStatusReturned ProductItemStatus = "RETURNED"
	// The item has been lost (e.g., during shipping or in the warehouse)
	ProductItemStatusLost ProductItemStatus = "LOST"
)

var AllProductItemStatus = []ProductItemStatus{
	ProductItemStatusInStorage,
	ProductItemStatusReserved,
	ProductItemStatusInFulfillment,
	ProductItemStatusShipped,
	ProductItemStatusDelivered,
	ProductItemStatusReturned,
	ProductItemStatusLost,
}

func (e ProductItemStatus) IsValid() bool {
	switch e {
	case ProductItemStatusInStorage, ProductItemStatusReserved, ProductItemStatusInFulfillment, ProductItemStatusShipped, ProductItemStatusDelivered, ProductItemStatusReturned, ProductItemStatusLost:
		return true
	}
	return false
}

func (e ProductItemStatus) String() string {
	return string(e)
}

func (e *ProductItemStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductItemStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductItemStatus", str)
	}
	return nil
}

func (e ProductItemStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProductItemStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProductItemStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
