package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"errors"
	"fmt"

	"misarch/inventory/store"
)

// CreateProductItemBatch is the resolver for the createProductItemBatch field.
func (r *mutationResolver) CreateProductItemBatch(ctx context.Context, input CreateProductItemBatchInput) ([]ProductItem, error) {
	if err := requireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}

	// Validate the product variant exists in the local replica first (spec §3.4
	// step 1); missing → GraphQL error with the exact message.
	exists, err := r.Store.VariantExists(ctx, input.ProductVariantID)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, fmt.Errorf("ProductVariant with ID %q not found", input.ProductVariantID)
	}

	// Insert `number` documents in one transaction (number <= 0 → [] with no
	// inserts, matching the original's lack of validation on number).
	items, err := r.Store.CreateBatch(ctx, input.ProductVariantID, input.Number)
	if err != nil {
		return nil, err
	}
	return toProductItems(items), nil
}

// UpdateProductItem is the resolver for the updateProductItem field.
func (r *mutationResolver) UpdateProductItem(ctx context.Context, input UpdateProductItemInput) (*ProductItem, error) {
	if err := requireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}

	// Validate the product variant exists (spec §3.4 step 1).
	exists, err := r.Store.VariantExists(ctx, input.ProductVariantID)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, fmt.Errorf("ProductVariant with ID %q not found", input.ProductVariantID)
	}

	// $set {productVariant, inventoryStatus} only; orderId is preserved
	// (spec §3.4 [BUG-COMPAT update-not-overwrite]). Returns the post-update doc.
	item, err := r.Store.Update(ctx, input.ID, input.ProductVariantID, string(input.InventoryStatus))
	if err != nil {
		return nil, err
	}
	if item == nil {
		return nil, fmt.Errorf("ProductItem with ID %q not found", input.ID)
	}
	return toProductItem(*item), nil
}

// DeleteProductItem is the resolver for the deleteProductItem field.
func (r *mutationResolver) DeleteProductItem(ctx context.Context, id string) (*ProductItem, error) {
	// deleteProductItem is admin-only (spec §6).
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	// Hard delete, returning the deleted document. Missing id → nil, and gqlgen
	// produces the non-null field error for Mutation.deleteProductItem
	// (spec §3.4 [BUG-COMPAT delete-missing]: the original service returned null
	// and Apollo raised the non-null violation).
	item, err := r.Store.Delete(ctx, id)
	if err != nil {
		return nil, err
	}
	if item == nil {
		return nil, nil
	}
	return toProductItem(*item), nil
}

// ReserveProductItemBatch is the resolver for the reserveProductItemBatch field.
func (r *mutationResolver) ReserveProductItemBatch(ctx context.Context, input ReserveProductItemsBatchInput) ([]ProductItem, error) {
	if err := requireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}

	items, err := r.Store.ReserveBatch(ctx, input.ProductVariantID, input.Number, input.OrderID)
	if err != nil {
		if errors.Is(err, store.ErrNotEnoughItems) {
			return nil, fmt.Errorf("Not enough product items available for product variant %q", input.ProductVariantID)
		}
		return nil, err
	}
	// ReserveBatch returns an empty slice on success (spec §3.4
	// [BUG-COMPAT reserve-returns-empty]); the reservation is persisted.
	return toProductItems(items), nil
}

// ProductVariant is the resolver for the productVariant field.
func (r *productItemResolver) ProductVariant(ctx context.Context, obj *ProductItem) (*ProductVariant, error) {
	// No auth check and no DB call (spec §3.2): returns the foreign entity stub
	// built from the stored variant id. Sub-selections (inventoryCount,
	// productItems) execute this service's own ProductVariant resolvers.
	return &ProductVariant{ID: obj.ProductVariantID}, nil
}

// ProductItems is the resolver for the productItems field.
func (r *productVariantResolver) ProductItems(ctx context.Context, obj *ProductVariant, skip *int, first *int, orderBy *ProductItemOrder, filter *ProductItemOfProductVariantFilter) (*ProductItemConnection, error) {
	if err := requireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}

	s, f, err := paginationArgs(skip, first)
	if err != nil {
		return nil, err
	}

	// [BUG-COMPAT variant-filter-ignored] (spec §3.1): the user-supplied filter
	// is discarded; the resolver always filters solely on the parent variant id
	// (the original spread { ...args, filter: { productVariant: id } }).
	variantID := obj.ID
	sf := &store.Filter{ProductVariant: &variantID}

	return buildConnection(ctx, r.Store, sf, s, f, orderAscending(orderBy))
}

// InventoryCount is the resolver for the inventoryCount field.
func (r *productVariantResolver) InventoryCount(ctx context.Context, obj *ProductVariant) (int, error) {
	// No auth (spec §3.1 / §6): public so buyers see stock through the catalog.
	// Counts only IN_STORAGE items of the variant with the CORRECT field names.
	variantID := obj.ID
	status := store.StatusInStorage
	n, err := r.Store.Count(ctx, &store.Filter{ProductVariant: &variantID, InventoryStatus: &status})
	if err != nil {
		return 0, err
	}
	return int(n), nil
}

// ProductItems is the resolver for the productItems field.
func (r *queryResolver) ProductItems(ctx context.Context, skip *int, first *int, orderBy *ProductItemOrder, filter *ProductItemFilter) (*ProductItemConnection, error) {
	if err := requireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}

	s, f, err := paginationArgs(skip, first)
	if err != nil {
		return nil, err
	}

	// The store applies the correct translation for totalCount and the buggy
	// translation for nodes (spec §3.3 [BUG-COMPAT nodes-filter]).
	return buildConnection(ctx, r.Store, storeFilter(filter), s, f, orderAscending(orderBy))
}

// ProductItem is the resolver for the productItem field.
func (r *queryResolver) ProductItem(ctx context.Context, id string) (*ProductItem, error) {
	if err := requireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}

	item, err := r.Store.FindByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if item == nil {
		return nil, fmt.Errorf("ProductItem with ID %q not found", id)
	}
	return toProductItem(*item), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// ProductItem returns ProductItemResolver implementation.
func (r *Resolver) ProductItem() ProductItemResolver { return &productItemResolver{r} }

// ProductVariant returns ProductVariantResolver implementation.
func (r *Resolver) ProductVariant() ProductVariantResolver { return &productVariantResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver       struct{ *Resolver }
	productItemResolver    struct{ *Resolver }
	productVariantResolver struct{ *Resolver }
	queryResolver          struct{ *Resolver }
)
