package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"
)

// FindOrderByID is the resolver for the findOrderByID field.
//
// Mirrors OrderResolver: a bare federated Order stub, no DB read. gqlgen has
// already parsed the UUID from the representation.
func (r *entityResolver) FindOrderByID(ctx context.Context, id uuid.UUID) (*Order, error) {
	return &Order{ID: id}, nil
}

// FindOrderItemByID is the resolver for the findOrderItemByID field.
//
// Mirrors OrderItemResolver: load by id; if found, map it (id + returnedWithId);
// if NOT found locally, return a stub {id, returnedWith:null} rather than an
// error, so the gateway can attach returnedWith to an order item this service
// has never heard of (reporting "not returned").
func (r *entityResolver) FindOrderItemByID(ctx context.Context, id uuid.UUID) (*OrderItem, error) {
	oi, found, err := r.Store.GetOrderItem(ctx, id)
	if err != nil {
		return nil, err
	}
	if !found {
		return &OrderItem{ID: id}, nil
	}
	return toOrderItem(oi), nil
}

// FindReturnByID is the resolver for the findReturnByID field.
//
// The original has no dedicated Return entity resolver (Return is only ever
// produced, never resolved as an external reference), but the @key is
// resolvable:true, so a DB-backed resolver is provided for gqlgen conformance;
// a not-found id errors. This path is effectively unused in practice.
func (r *entityResolver) FindReturnByID(ctx context.Context, id uuid.UUID) (*Return, error) {
	ret, err := r.Store.GetReturn(ctx, id)
	if err != nil {
		return nil, err
	}
	return toReturn(ret), nil
}

// FindUserByID is the resolver for the findUserByID field.
//
// Mirrors UserResolver: a bare federated User stub, no DB read.
func (r *entityResolver) FindUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	return &User{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
