// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// An object with an ID.
type Node interface {
	IsNode()
}

// Discount order
type CommonOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *CommonOrderField `json:"field,omitempty"`
}

// Input for the createReturn mutation
type CreateReturnInput struct {
	// The order items to return, must belong to the same order and must not be already returned.
	OrderItemIds []uuid.UUID `json:"orderItemIds"`
	// The reason for the return.
	Reason string `json:"reason"`
}

type Mutation struct {
}

// An order.
type Order struct {
	// The ID of the node.
	ID uuid.UUID `json:"id"`
}

func (Order) IsNode() {}

func (Order) IsEntity() {}

// An order item.
type OrderItem struct {
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The return this order item was returned with.
	ReturnedWith   *Return    `json:"returnedWith,omitempty"`
	ReturnedWithID *uuid.UUID `json:"-"`
}

func (OrderItem) IsNode() {}

func (OrderItem) IsEntity() {}

// A connection to a list of `OrderItem` values.
type OrderItemConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []OrderItem `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

type Query struct {
}

// A return.
type Return struct {
	// The time the return was created.
	CreatedAt time.Time `json:"createdAt"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The order this return is for.
	Order *Order `json:"order"`
	// The reason for the return.
	Reason string `json:"reason"`
	// The amount of money refunded.
	RefundedAmount int `json:"refundedAmount"`
	// Get all order items returned with this return
	ReturnedItems *OrderItemConnection `json:"returnedItems"`
	OrderID       uuid.UUID            `json:"-"`
}

func (Return) IsNode() {}

func (Return) IsEntity() {}

// A connection to a list of `Return` values.
type ReturnConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []Return `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// Direction to sort returns in
type ReturnOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *ReturnOrderField `json:"field,omitempty"`
}

// A user.
type User struct {
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// Get all returns of this user
	Returns *ReturnConnection `json:"returns"`
}

func (User) IsNode() {}

func (User) IsEntity() {}

// Common order fields
type CommonOrderField string

const (
	// Order entities by their id
	CommonOrderFieldID CommonOrderField = "ID"
)

var AllCommonOrderField = []CommonOrderField{
	CommonOrderFieldID,
}

func (e CommonOrderField) IsValid() bool {
	switch e {
	case CommonOrderFieldID:
		return true
	}
	return false
}

func (e CommonOrderField) String() string {
	return string(e)
}

func (e *CommonOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommonOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommonOrderField", str)
	}
	return nil
}

func (e CommonOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommonOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommonOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Order direction
type OrderDirection string

const (
	// Ascending order
	OrderDirectionAsc OrderDirection = "ASC"
	// Descending order
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Return order fields
type ReturnOrderField string

const (
	// Order returns by their id
	ReturnOrderFieldID ReturnOrderField = "ID"
)

var AllReturnOrderField = []ReturnOrderField{
	ReturnOrderFieldID,
}

func (e ReturnOrderField) IsValid() bool {
	switch e {
	case ReturnOrderFieldID:
		return true
	}
	return false
}

func (e ReturnOrderField) String() string {
	return string(e)
}

func (e *ReturnOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReturnOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReturnOrderField", str)
	}
	return nil
}

func (e ReturnOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReturnOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReturnOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
