package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"

	"misarch/return/events"
)

// CreateReturn is the resolver for the createReturn field.
//
// Mirrors Mutation.createReturn → ReturnService.createReturn: requires an
// authorized user (else "Unauthorized access"), runs the whole validate →
// insert return → link order items (triggers) sequence in a single transaction
// inside the store, then publishes return/return/created AFTER a successful
// commit. The event's orderItemIds are exactly the input ids in request order
// (not re-derived from the loaded entities), and refundedAmount is the full
// int64.
func (r *mutationResolver) CreateReturn(ctx context.Context, input CreateReturnInput) (*Return, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	saved, err := r.Store.CreateReturn(ctx, input.OrderItemIds, input.Reason, user.ID, time.Now().UTC())
	if err != nil {
		return nil, err
	}

	if err := events.PublishReturnCreated(ctx, r.Dapr, events.ReturnCreated{
		ID:             saved.ID,
		OrderID:        saved.OrderID,
		OrderItemIds:   input.OrderItemIds,
		Reason:         saved.Reason,
		RefundedAmount: saved.RefundedAmount,
		CreatedAt:      events.FormatEventCreatedAt(saved.CreatedAt),
	}); err != nil {
		return nil, err
	}

	return toReturn(saved), nil
}

// ReturnedWith is the resolver for the returnedWith field.
//
// Mirrors OrderItem.returnedWith: null returnedWithId → null; otherwise
// batch-load the Return by id (ReturnDataLoader). A dangling reference (the
// loader's entities[id]!!) surfaces as an error.
func (r *orderItemResolver) ReturnedWith(ctx context.Context, obj *OrderItem) (*Return, error) {
	if obj.ReturnedWithID == nil {
		return nil, nil
	}
	returns, err := r.Store.GetReturnsByIDs(ctx, []uuid.UUID{*obj.ReturnedWithID})
	if err != nil {
		return nil, err
	}
	ret, ok := returns[*obj.ReturnedWithID]
	if !ok {
		return nil, fmt.Errorf("return with id %s not found", *obj.ReturnedWithID)
	}
	return toReturn(ret), nil
}

// Return is the resolver for the return field.
//
// Mirrors Query.return: load the return (error if missing), load its order,
// require an authorized user, and (unless employee/admin) require the caller to
// own the order.
func (r *queryResolver) Return(ctx context.Context, id uuid.UUID) (*Return, error) {
	ret, err := r.Store.GetReturn(ctx, id)
	if err != nil {
		return nil, err
	}
	order, err := r.Store.GetOrder(ctx, ret.OrderID)
	if err != nil {
		return nil, err
	}
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if !isEmployee(user) && order.UserID != user.ID {
		return nil, errors.New("You are not authorized to view this return")
	}
	return toReturn(ret), nil
}

// Returns is the resolver for the returns field.
//
// Mirrors Query.returns: a ReturnConnection with no extra predicate; the
// connection's authorizedUserFilter restricts non-employees to their own
// returns and dereferences the user non-null (so a missing header errors).
func (r *queryResolver) Returns(ctx context.Context, first *int, orderBy *ReturnOrderInput, skip *int) (*ReturnConnection, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	conn, err := r.Store.ListReturns(ctx, nil, authFilterUserID(user), first, skip, returnAscending(orderBy))
	if err != nil {
		return nil, err
	}
	return toReturnConnection(conn), nil
}

// Order is the resolver for the order field.
//
// Mirrors Return.order(): a bare federated Order stub carrying only the id; the
// gateway resolves the rest from the order subgraph. No DB read.
func (r *returnResolver) Order(ctx context.Context, obj *Return) (*Order, error) {
	return &Order{ID: obj.OrderID}, nil
}

// ReturnedItems is the resolver for the returnedItems field.
//
// Mirrors Return.returnedItems(): an OrderItemConnection filtered by
// returnedWithId = this return's id. No authorizedUserFilter is applied (any
// caller who can see the Return sees its items).
func (r *returnResolver) ReturnedItems(ctx context.Context, obj *Return, first *int, orderBy *CommonOrderInput, skip *int) (*OrderItemConnection, error) {
	conn, err := r.Store.ListReturnedItems(ctx, obj.ID, first, skip, commonAscending(orderBy))
	if err != nil {
		return nil, err
	}
	return toOrderItemConnection(conn), nil
}

// Returns is the resolver for the returns field.
//
// Mirrors User.returns(): a ReturnConnection filtered by the target user's id
// (OrderEntity.userId = this.user.id) AND the connection's authorizedUserFilter
// (non-employees additionally restricted to their own order's userId — so a
// normal user querying another user's returns gets an empty connection). The
// user must be present (the original NPEs otherwise).
func (r *userResolver) Returns(ctx context.Context, obj *User, first *int, orderBy *ReturnOrderInput, skip *int) (*ReturnConnection, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	targetID := obj.ID
	conn, err := r.Store.ListReturns(ctx, &targetID, authFilterUserID(user), first, skip, returnAscending(orderBy))
	if err != nil {
		return nil, err
	}
	return toReturnConnection(conn), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// OrderItem returns OrderItemResolver implementation.
func (r *Resolver) OrderItem() OrderItemResolver { return &orderItemResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Return returns ReturnResolver implementation.
func (r *Resolver) Return() ReturnResolver { return &returnResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type (
	mutationResolver  struct{ *Resolver }
	orderItemResolver struct{ *Resolver }
	queryResolver     struct{ *Resolver }
	returnResolver    struct{ *Resolver }
	userResolver      struct{ *Resolver }
)
