package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"
)

// FindNotificationByID is the resolver for the findNotificationByID field.
func (r *entityResolver) FindNotificationByID(ctx context.Context, id uuid.UUID) (*Notification, error) {
	// Federation entity resolution goes through the same DB load as the query
	// (the original NotificationResolver used the data loader) but applies NO
	// auth check — this is a gateway-internal path. A nonexistent id errors.
	notification, err := r.Store.GetNotification(ctx, id)
	if err != nil {
		return nil, err
	}
	return toNotification(notification), nil
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	// The original UserResolver constructs a User directly from the id with NO
	// DB access and NO auth check: any UUID resolves, even for users never
	// registered locally.
	return &User{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
