// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// An object with an ID.
type Node interface {
	IsNode()
}

// Input for the createNotification mutation
type CreateNotificationInput struct {
	// body of the notification to create
	Body string `json:"body"`
	// title of the notification to create
	Title string `json:"title"`
	// id of the user the notification should be sent to
	UserID uuid.UUID `json:"userId"`
}

type Mutation struct {
}

// A notification.
type Notification struct {
	// The content of the notification
	Body string `json:"body"`
	// The date the notification was read
	DateRead *time.Time `json:"dateRead,omitempty"`
	// The date the notification was sent
	DateSent time.Time `json:"dateSent"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// Whether the notification has been read
	IsRead bool `json:"isRead"`
	// The title of the notification
	Title string `json:"title"`
	// The user this notification was sent to.
	User   *User     `json:"user"`
	UserID uuid.UUID `json:"-"`
}

func (Notification) IsNode() {}

func (Notification) IsEntity() {}

// A connection to a list of `Notification` values.
type NotificationConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []Notification `json:"nodes"`
	// The total amount of items in this connection
	TotalCount   int       `json:"totalCount"`
	Ascending    bool      `json:"-"`
	First        *int      `json:"-"`
	OrderColumns []string  `json:"-"`
	Skip         *int      `json:"-"`
	UserID       uuid.UUID `json:"-"`
}

// Notification order
type NotificationOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *NotificationOrderField `json:"field,omitempty"`
}

type Query struct {
}

// Input for the updateNotification mutation
type UpdateNotificationInput struct {
	// id of the notification to update
	ID uuid.UUID `json:"id"`
	// mark the notification as read/unread
	IsRead bool `json:"isRead"`
}

// A user.
type User struct {
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// Get all notifications the user received
	Notifications *NotificationConnection `json:"notifications"`
}

func (User) IsNode() {}

func (User) IsEntity() {}

// Notification order fields
type NotificationOrderField string

const (
	// Order notifications by their id
	NotificationOrderFieldID NotificationOrderField = "ID"
)

var AllNotificationOrderField = []NotificationOrderField{
	NotificationOrderFieldID,
}

func (e NotificationOrderField) IsValid() bool {
	switch e {
	case NotificationOrderFieldID:
		return true
	}
	return false
}

func (e NotificationOrderField) String() string {
	return string(e)
}

func (e *NotificationOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotificationOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotificationOrderField", str)
	}
	return nil
}

func (e NotificationOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NotificationOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NotificationOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Order direction
type OrderDirection string

const (
	// Ascending order
	OrderDirectionAsc OrderDirection = "ASC"
	// Descending order
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
