package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// CreateNotification is the resolver for the createNotification field.
func (r *mutationResolver) CreateNotification(ctx context.Context, input CreateNotificationInput) (*Notification, error) {
	// AuthZ first (checkIsEmployee before anything else): the recipient cannot
	// self-create; only employees/admins may.
	user, err := authorizedUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := checkIsEmployee(user); err != nil {
		return nil, err
	}

	// Validates the user exists (exact error "User with id <uuid> does not
	// exist") and inserts with dateSent = now(), dateRead = NULL, DB-generated
	// id — the exists-check and insert share one transaction. No event.
	notification, err := r.Store.CreateNotification(ctx, input.Title, input.Body, input.UserID, time.Now())
	if err != nil {
		return nil, err
	}
	return toNotification(notification), nil
}

// UpdateNotification is the resolver for the updateNotification field.
func (r *mutationResolver) UpdateNotification(ctx context.Context, input UpdateNotificationInput) (*Notification, error) {
	// Load first: a nonexistent id yields not-found even for non-owners
	// (not-found beats forbidden).
	notification, err := r.Store.GetNotification(ctx, input.ID)
	if err != nil {
		return nil, err
	}

	// AuthZ after load: owners may update their own; non-owners require ADMIN
	// (employee is NOT enough here, unlike the read paths).
	user, err := authorizedUser(ctx)
	if err != nil {
		return nil, err
	}
	if notification.UserID != user.ID {
		if err := checkIsAdmin(user); err != nil {
			return nil, err
		}
	}

	// Toggle read-state (only rewrites dateRead when the state actually flips);
	// the row is saved in both cases. No event.
	updated, err := r.Store.SetNotificationRead(ctx, notification.ID, notification.DateRead, input.IsRead)
	if err != nil {
		return nil, err
	}
	return toNotification(updated), nil
}

// IsRead is the resolver for the isRead field.
func (r *notificationResolver) IsRead(ctx context.Context, obj *Notification) (bool, error) {
	// Derived, never stored: isRead == (dateRead != null). No auth.
	return obj.DateRead != nil, nil
}

// User is the resolver for the user field.
func (r *notificationResolver) User(ctx context.Context, obj *Notification) (*User, error) {
	// The original resolves this via the User data loader to {id: userId}; the
	// FK guarantees the user exists, so it is behaviorally User{id: userId}. No
	// auth check on this field.
	return &User{ID: obj.UserID}, nil
}

// HasNextPage is the resolver for the hasNextPage field.
func (r *notificationConnectionResolver) HasNextPage(ctx context.Context, obj *NotificationConnection) (bool, error) {
	// Independent, lazily-evaluated query: first == nil always yields false.
	return r.Store.NotificationsHasNextPage(ctx, obj.UserID, obj.First, obj.Skip, obj.OrderColumns, obj.Ascending)
}

// Nodes is the resolver for the nodes field.
func (r *notificationConnectionResolver) Nodes(ctx context.Context, obj *NotificationConnection) ([]Notification, error) {
	// Independent, lazily-evaluated query for this page of notifications.
	rows, err := r.Store.ListNotifications(ctx, obj.UserID, obj.First, obj.Skip, obj.OrderColumns, obj.Ascending)
	if err != nil {
		return nil, err
	}
	nodes := make([]Notification, len(rows))
	for i, n := range rows {
		nodes[i] = *toNotification(n)
	}
	return nodes, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *notificationConnectionResolver) TotalCount(ctx context.Context, obj *NotificationConnection) (int, error) {
	// Independent, lazily-evaluated query: ignores first/skip.
	return r.Store.CountNotifications(ctx, obj.UserID)
}

// Notification is the resolver for the notification field.
func (r *queryResolver) Notification(ctx context.Context, id uuid.UUID) (*Notification, error) {
	// Load first, THEN authorize (load-then-authorize): a nonexistent id yields
	// not-found even for unauthorized callers.
	notification, err := r.Store.GetNotification(ctx, id)
	if err != nil {
		return nil, err
	}

	// The owner may read their own; employees/admins may read anyone's. A
	// missing/invalid header errors with "Unauthorized access" (accessing the
	// caller identity is required even on the owner path).
	user, err := authorizedUser(ctx)
	if err != nil {
		return nil, err
	}
	if notification.UserID != user.ID {
		if err := checkIsEmployee(user); err != nil {
			return nil, err
		}
	}
	return toNotification(notification), nil
}

// Notifications is the resolver for the notifications field.
func (r *userResolver) Notifications(ctx context.Context, obj *User, first *int, orderBy *NotificationOrderInput, skip *int) (*NotificationConnection, error) {
	// AuthZ first (authorize-first): self may read their own; non-self requires
	// employee-or-admin. A missing header errors with "Unauthorized access".
	// This is the effective guard for notifications reached via _entities(User).
	user, err := authorizedUser(ctx)
	if err != nil {
		return nil, err
	}
	if user.ID != obj.ID {
		if err := checkIsEmployee(user); err != nil {
			return nil, err
		}
	}

	// Carry the query parameters; each connection field runs its own query
	// lazily when selected.
	cols, asc := notificationOrder(orderBy)
	return &NotificationConnection{
		UserID:       obj.ID,
		First:        first,
		Skip:         skip,
		OrderColumns: cols,
		Ascending:    asc,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Notification returns NotificationResolver implementation.
func (r *Resolver) Notification() NotificationResolver { return &notificationResolver{r} }

// NotificationConnection returns NotificationConnectionResolver implementation.
func (r *Resolver) NotificationConnection() NotificationConnectionResolver {
	return &notificationConnectionResolver{r}
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type (
	mutationResolver               struct{ *Resolver }
	notificationResolver           struct{ *Resolver }
	notificationConnectionResolver struct{ *Resolver }
	queryResolver                  struct{ *Resolver }
	userResolver                   struct{ *Resolver }
)
