package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"misarch/shoppingcart/store"

	"github.com/google/uuid"
)

// FindShoppingCartItemByID is the resolver for the findShoppingCartItemByID
// field. Same lookup + projection as the shoppingcartItem query, but with NO
// authorization check: the gateway is trusted to have authorized the enclosing
// operation. Errors identically on not-found / projection failure.
func (r *entityResolver) FindShoppingCartItemByID(ctx context.Context, id uuid.UUID) (*ShoppingCartItem, error) {
	item, err := r.Store.FindItem(ctx, id)
	if err != nil {
		return nil, itemLookupError(id, err)
	}
	gqlItem := toCartItem(item)
	return &gqlItem, nil
}

// FindUserByID is the resolver for the findUserByID field. It loads the whole
// user document (including the embedded cart) with NO authorization check. A
// missing user yields a user-not-found error.
func (r *entityResolver) FindUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	cart, err := r.Store.FindUserCart(ctx, id)
	if err != nil {
		if errorsIs(err, store.ErrNotFound) {
			return nil, userNotFoundError(id)
		}
		return nil, err
	}
	return &User{
		ID:           id,
		Shoppingcart: toShoppingCart(cart),
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
