// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// Specifies the order of foreign types.
type CommonOrderInput struct {
	// Order direction of shoppingcarts.
	Direction *OrderDirection `json:"direction,omitempty"`
	// Field that shoppingcarts should be ordered by.
	Field *CommonOrderField `json:"field,omitempty"`
}

type CreateShoppingCartItemInput struct {
	// UUID of user owning the shopping cart.
	ID uuid.UUID `json:"id"`
	// shopping cart item in shopping cart to update
	ShoppingCartItem *ShoppingCartItemInput `json:"shoppingCartItem"`
}

type Mutation struct {
}

// Foreign type of a product variant.
type ProductVariant struct {
	// UUID of the product variant.
	ID uuid.UUID `json:"id"`
}

func (ProductVariant) IsEntity() {}

type Query struct {
}

// The shopping cart of a user.
type ShoppingCart struct {
	// Timestamp when shopping cart was last updated.
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`
	// Retrieves shoppingcart items in shopping cart.
	ShoppingcartItems *ShoppingCartItemConnection `json:"shoppingcartItems"`
	Items             []ShoppingCartItem          `json:"-"`
}

// Shopping cart item in a shopping cart of a user.
type ShoppingCartItem struct {
	// Shopping cart item UUID.
	ID uuid.UUID `json:"id"`
	// Count of items in basket.
	Count int `json:"count"`
	// Timestamp when shopping cart item was added.
	AddedAt time.Time `json:"addedAt"`
	// Product variant of shopping cart item.
	ProductVariant   *ProductVariant `json:"productVariant"`
	ProductVariantID uuid.UUID       `json:"-"`
}

func (ShoppingCartItem) IsEntity() {}

// A connection of shopping cart items.
type ShoppingCartItemConnection struct {
	// The resulting entities.
	Nodes []ShoppingCartItem `json:"nodes"`
	// Whether this connection has a next page.
	HasNextPage bool `json:"hasNextPage"`
	// The total amount of items in this connection.
	TotalCount int `json:"totalCount"`
}

type ShoppingCartItemInput struct {
	// Count of shopping cart items in cart.
	Count int `json:"count"`
	// UUID of product variant.
	ProductVariantID uuid.UUID `json:"productVariantId"`
}

type UpdateShoppingCartInput struct {
	// UUID of user owning shopping cart.
	ID uuid.UUID `json:"id"`
	// Shopping cart items of shopping cart to update.
	ShoppingCartItems []ShoppingCartItemInput `json:"shoppingCartItems,omitempty"`
}

type UpdateShoppingCartItemInput struct {
	// UUID of shoppingcart item to update.
	ID uuid.UUID `json:"id"`
	// Count of shopping cart items in cart.
	Count int `json:"count"`
}

// Type of a user owning shoppingcarts.
type User struct {
	// UUID of the user.
	ID uuid.UUID `json:"id"`
	// Shopping cart of the user.
	Shoppingcart *ShoppingCart `json:"shoppingcart"`
}

func (User) IsEntity() {}

// Describes the fields that a foreign types can be ordered by.
type CommonOrderField string

const (
	// Orders by "id".
	CommonOrderFieldID CommonOrderField = "ID"
)

var AllCommonOrderField = []CommonOrderField{
	CommonOrderFieldID,
}

func (e CommonOrderField) IsValid() bool {
	switch e {
	case CommonOrderFieldID:
		return true
	}
	return false
}

func (e CommonOrderField) String() string {
	return string(e)
}

func (e *CommonOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommonOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommonOrderField", str)
	}
	return nil
}

func (e CommonOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommonOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommonOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// GraphQL order direction.
type OrderDirection string

const (
	// Ascending order direction.
	OrderDirectionAsc OrderDirection = "ASC"
	// Descending order direction.
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
