package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"misarch/pkg/auth"
	"misarch/shoppingcart/store"
	"time"

	"github.com/google/uuid"
)

// UpdateShoppingcart replaces a cart's whole item list. Authorization is FIRST
// (owner = input.id). An absent shoppingCartItems list is a no-op that returns
// the current cart; a present list (even empty) validates every referenced
// product variant, validates the user, then overwrites the item set with fresh
// item ids + a single shared timestamp and bumps last_updated_at. Finally it
// re-queries and returns the cart.
func (r *mutationResolver) UpdateShoppingcart(ctx context.Context, input UpdateShoppingCartInput) (*ShoppingCart, error) {
	if _, err := auth.RequireSelfOrEmployee(ctx, input.ID); err != nil {
		return nil, err
	}

	// One timestamp captured once for the whole call (Rust DateTime::now()).
	now := time.Now().UTC()

	if input.ShoppingCartItems != nil {
		// De-duplicate identical {count, productVariantId} pairs, preserving
		// insertion order (Rust deserializes into a HashSet keyed on both
		// fields: fully identical entries collapse to one; same-variant/
		// different-count entries both persist). Item ids are freshly minted,
		// so order is not observable by clients.
		deduped := dedupItemInputs(input.ShoppingCartItems)

		variantIDs := make([]uuid.UUID, len(deduped))
		for i, it := range deduped {
			variantIDs[i] = it.ProductVariantID
		}

		// Validate all product variants exist (first missing id → error).
		missing, ok, err := r.Store.ProductVariantsExist(ctx, variantIDs)
		if err != nil {
			return nil, productVariantsQueryError()
		}
		if !ok {
			return nil, productVariantNotPresentError(missing)
		}

		// Validate the user exists.
		if _, err := r.Store.FindUser(ctx, input.ID); err != nil {
			if errorsIs(err, store.ErrNotFound) {
				return nil, userNotFoundError(input.ID)
			}
			return nil, err
		}

		// Build the brand-new item list: fresh _id per input, shared added_at.
		items := make([]store.CartItem, len(deduped))
		for i, it := range deduped {
			items[i] = store.CartItem{
				ID:               uuid.New(),
				Count:            it.Count,
				AddedAt:          now,
				ProductVariantID: it.ProductVariantID,
			}
		}

		if err := r.Store.ReplaceCartItems(ctx, input.ID, items, now); err != nil {
			return nil, replaceCartFailedError(input.ID)
		}
	}

	// Re-query the cart and return it.
	cart, err := r.Store.FindUserCart(ctx, input.ID)
	if err != nil {
		if errorsIs(err, store.ErrNotFound) {
			return nil, cartNotFoundError(input.ID)
		}
		return nil, err
	}
	return toShoppingCart(cart), nil
}

// CreateShoppingcartItem adds one item to a cart. Authorization is FIRST
// (owner = input.id). It validates the user, then the single product variant,
// then dedups by product variant: if the cart already has an item for that
// variant it returns that existing item UNCHANGED (no count increment, no
// timestamp change); otherwise it pushes a new item (fresh id + now) and
// returns it. This mutation never touches last_updated_at.
func (r *mutationResolver) CreateShoppingcartItem(ctx context.Context, input CreateShoppingCartItemInput) (*ShoppingCartItem, error) {
	if _, err := auth.RequireSelfOrEmployee(ctx, input.ID); err != nil {
		return nil, err
	}

	// Validate user exists.
	if _, err := r.Store.FindUser(ctx, input.ID); err != nil {
		if errorsIs(err, store.ErrNotFound) {
			return nil, userNotFoundError(input.ID)
		}
		return nil, err
	}

	variantID := input.ShoppingCartItem.ProductVariantID

	// Validate the single product variant exists.
	exists, err := r.Store.ProductVariantExists(ctx, variantID)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, productVariantNotPresentError(variantID)
	}

	// Dedup by product variant: return the existing line item if present.
	if existing, found, err := r.Store.FindItemByVariant(ctx, input.ID, variantID); err != nil {
		return nil, err
	} else if found {
		item := toCartItem(existing)
		return &item, nil
	}

	// Not present: create and push a new item.
	newItem := store.CartItem{
		ID:               uuid.New(),
		Count:            input.ShoppingCartItem.Count,
		AddedAt:          time.Now().UTC(),
		ProductVariantID: variantID,
	}
	if err := r.Store.PushItem(ctx, input.ID, newItem); err != nil {
		return nil, addItemFailedError(newItem.ID)
	}
	item := toCartItem(newItem)
	return &item, nil
}

// UpdateShoppingcartItem updates a single item's count. It looks up the owning
// user by the item id FIRST, then authorizes against that owner (existence
// leaks before auth), then sets the count via the positional operator and
// re-queries the item. It changes neither added_at nor last_updated_at.
func (r *mutationResolver) UpdateShoppingcartItem(ctx context.Context, input UpdateShoppingCartItemInput) (*ShoppingCartItem, error) {
	owner, _, err := r.Store.FindItemOwner(ctx, input.ID)
	if err != nil {
		return nil, itemLookupError(input.ID, err)
	}
	if _, err := auth.RequireSelfOrEmployee(ctx, owner); err != nil {
		return nil, err
	}
	if err := r.Store.UpdateItemCount(ctx, input.ID, input.Count); err != nil {
		return nil, updateCountFailedError(input.ID)
	}
	item, err := r.Store.FindItem(ctx, input.ID)
	if err != nil {
		return nil, itemLookupError(input.ID, err)
	}
	gqlItem := toCartItem(item)
	return &gqlItem, nil
}

// DeleteShoppingcartItem removes a single item. It looks up the owning user by
// the item id FIRST, then authorizes against that owner (existence leaks before
// auth), then pulls the item and returns true. It does not bump
// last_updated_at.
func (r *mutationResolver) DeleteShoppingcartItem(ctx context.Context, id uuid.UUID) (bool, error) {
	owner, _, err := r.Store.FindItemOwner(ctx, id)
	if err != nil {
		return false, itemLookupError(id, err)
	}
	if _, err := auth.RequireSelfOrEmployee(ctx, owner); err != nil {
		return false, err
	}
	if err := r.Store.PullItem(ctx, id); err != nil {
		return false, deleteItemFailedError(id)
	}
	return true, nil
}

// ShoppingcartItem is the resolver for the shoppingcartItem field. It looks up
// the item's owning user by the item id, then authorizes the caller against
// that owner, then returns the item. Authorization happens AFTER the lookup so
// an unauthorized caller can still distinguish "item does not exist" from
// "item exists but you can't see it" — this ordering is load-bearing.
func (r *queryResolver) ShoppingcartItem(ctx context.Context, id uuid.UUID) (*ShoppingCartItem, error) {
	owner, item, err := r.Store.FindItemOwner(ctx, id)
	if err != nil {
		return nil, itemLookupError(id, err)
	}
	if _, err := auth.RequireSelfOrEmployee(ctx, owner); err != nil {
		return nil, err
	}
	gqlItem := toCartItem(item)
	return &gqlItem, nil
}

// ShoppingcartItems is the resolver for the shoppingcartItems field. It
// paginates the cart's already-loaded item set in memory: sort by item UUID
// bytes (direction only), then skip/take. No DB call, no auth (the enclosing
// cart fetch was already authorized).
func (r *shoppingCartResolver) ShoppingcartItems(ctx context.Context, obj *ShoppingCart, first *int, skip *int, orderBy *CommonOrderInput) (*ShoppingCartItemConnection, error) {
	return paginateItems(obj.Items, first, skip, orderBy), nil
}

// ProductVariant is the resolver for the productVariant field. The item stores
// only the foreign variant id; this wraps it in the ProductVariant stub type.
func (r *shoppingCartItemResolver) ProductVariant(ctx context.Context, obj *ShoppingCartItem) (*ProductVariant, error) {
	return &ProductVariant{ID: obj.ProductVariantID}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// ShoppingCart returns ShoppingCartResolver implementation.
func (r *Resolver) ShoppingCart() ShoppingCartResolver { return &shoppingCartResolver{r} }

// ShoppingCartItem returns ShoppingCartItemResolver implementation.
func (r *Resolver) ShoppingCartItem() ShoppingCartItemResolver { return &shoppingCartItemResolver{r} }

type (
	mutationResolver         struct{ *Resolver }
	queryResolver            struct{ *Resolver }
	shoppingCartResolver     struct{ *Resolver }
	shoppingCartItemResolver struct{ *Resolver }
)
