package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"
)

// FindTaxRateByID is the resolver for the findTaxRateByID field.
func (r *entityResolver) FindTaxRateByID(ctx context.Context, id uuid.UUID) (*TaxRate, error) {
	// Federation entity resolvers perform no auth check (the original
	// FederatedTypePromiseResolver resolved via the data loader directly).
	taxRate, err := r.Store.GetTaxRate(ctx, id)
	if err != nil {
		return nil, err
	}
	return toTaxRate(taxRate), nil
}

// FindTaxRateVersionByID is the resolver for the findTaxRateVersionByID field.
func (r *entityResolver) FindTaxRateVersionByID(ctx context.Context, id uuid.UUID) (*TaxRateVersion, error) {
	version, err := r.Store.GetTaxRateVersion(ctx, id)
	if err != nil {
		return nil, err
	}
	return toTaxRateVersion(version), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
