// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// An object with an ID.
type Node interface {
	IsNode()
}

// Input for the createTaxRate mutation
type CreateTaxRateInput struct {
	// The description of the created TaxRate
	Description string `json:"description"`
	// The initial version of the created TaxRate
	InitialVersion *TaxRateVersionInput `json:"initialVersion"`
	// The name of the created TaxRate
	Name string `json:"name"`
}

// Input for the createTaxRateVersion mutation
type CreateTaxRateVersionInput struct {
	// The rate of the created TaxRateVersion
	Rate float64 `json:"rate"`
	// The id of the TaxRate the created TaxRateVersion belongs to
	TaxRateID uuid.UUID `json:"taxRateId"`
}

type Mutation struct {
}

type Query struct {
}

// A TaxRate.
type TaxRate struct {
	// The current version of the TaxRate.
	CurrentVersion *TaxRateVersion `json:"currentVersion"`
	// The description of the TaxRate
	Description string `json:"description"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The name of the TaxRate
	Name string `json:"name"`
	// Get all associated versions
	Versions         *TaxRateVersionConnection `json:"versions"`
	CurrentVersionID uuid.UUID                 `json:"-"`
}

func (TaxRate) IsNode() {}

func (TaxRate) IsEntity() {}

// A connection to a list of `TaxRate` values.
type TaxRateConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []TaxRate `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// TaxRate order
type TaxRateOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *TaxRateOrderField `json:"field,omitempty"`
}

// A TaxRateVersion.
type TaxRateVersion struct {
	// Time stamp when the TaxRateVersion was created
	CreatedAt time.Time `json:"createdAt"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The rate of the TaxRateVersion
	Rate float64 `json:"rate"`
	// The associated TaxRate.
	TaxRate *TaxRate `json:"taxRate"`
	// Version of the TaxRateVersion
	Version   int       `json:"version"`
	TaxRateID uuid.UUID `json:"-"`
}

func (TaxRateVersion) IsNode() {}

func (TaxRateVersion) IsEntity() {}

// A connection to a list of `TaxRateVersion` values.
type TaxRateVersionConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []TaxRateVersion `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// Input for creating a TaxRateVersion
type TaxRateVersionInput struct {
	// The rate of the created TaxRateVersion
	Rate float64 `json:"rate"`
}

// TaxRateVersion order
type TaxRateVersionOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *TaxRateVersionOrderField `json:"field,omitempty"`
}

// Input for the updateTaxRate mutation
type UpdateTaxRateInput struct {
	// If provided, the new description of the TaxRate
	Description *string `json:"description,omitempty"`
	// The id of the TaxRate to update
	ID uuid.UUID `json:"id"`
	// If provided, the new name of the TaxRate
	Name *string `json:"name,omitempty"`
}

// Order direction
type OrderDirection string

const (
	// Ascending order
	OrderDirectionAsc OrderDirection = "ASC"
	// Descending order
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// TaxRate order fields
type TaxRateOrderField string

const (
	// Order TaxRates by their id
	TaxRateOrderFieldID TaxRateOrderField = "ID"
	// Order TaxRates by their name
	TaxRateOrderFieldName TaxRateOrderField = "NAME"
)

var AllTaxRateOrderField = []TaxRateOrderField{
	TaxRateOrderFieldID,
	TaxRateOrderFieldName,
}

func (e TaxRateOrderField) IsValid() bool {
	switch e {
	case TaxRateOrderFieldID, TaxRateOrderFieldName:
		return true
	}
	return false
}

func (e TaxRateOrderField) String() string {
	return string(e)
}

func (e *TaxRateOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaxRateOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaxRateOrderField", str)
	}
	return nil
}

func (e TaxRateOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaxRateOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaxRateOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// TaxRateVersion order fields
type TaxRateVersionOrderField string

const (
	// Order TaxRateVersions by their creation date
	TaxRateVersionOrderFieldCreatedAt TaxRateVersionOrderField = "CREATED_AT"
	// Order TaxRateVersions by their id
	TaxRateVersionOrderFieldID TaxRateVersionOrderField = "ID"
	// Order TaxRateVersions by their version
	TaxRateVersionOrderFieldVersion TaxRateVersionOrderField = "VERSION"
)

var AllTaxRateVersionOrderField = []TaxRateVersionOrderField{
	TaxRateVersionOrderFieldCreatedAt,
	TaxRateVersionOrderFieldID,
	TaxRateVersionOrderFieldVersion,
}

func (e TaxRateVersionOrderField) IsValid() bool {
	switch e {
	case TaxRateVersionOrderFieldCreatedAt, TaxRateVersionOrderFieldID, TaxRateVersionOrderFieldVersion:
		return true
	}
	return false
}

func (e TaxRateVersionOrderField) String() string {
	return string(e)
}

func (e *TaxRateVersionOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaxRateVersionOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaxRateVersionOrderField", str)
	}
	return nil
}

func (e TaxRateVersionOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaxRateVersionOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaxRateVersionOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
