package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"time"

	"github.com/google/uuid"

	"misarch/pkg/auth"
	"misarch/tax/events"
	"misarch/tax/store"
)

// CreateTaxRate is the resolver for the createTaxRate field.
func (r *mutationResolver) CreateTaxRate(ctx context.Context, input CreateTaxRateInput) (*TaxRate, error) {
	if _, err := auth.RequireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}

	var rate float64
	if input.InitialVersion != nil {
		rate = input.InitialVersion.Rate
	}

	taxRate, version, err := r.Store.CreateTaxRate(
		ctx, input.Name, input.Description, rate, time.Now().UTC(),
	)
	if err != nil {
		return nil, err
	}

	// Publish after the write commits: the created tax rate, then its initial
	// version (order matches the original service).
	if err := events.PublishTaxRateCreated(ctx, r.Dapr, events.TaxRateCreated{
		ID:               taxRate.ID,
		Name:             taxRate.Name,
		Description:      taxRate.Description,
		CurrentVersionID: taxRate.CurrentVersionID,
	}); err != nil {
		return nil, err
	}
	if err := events.PublishTaxRateVersionCreated(ctx, r.Dapr, versionEvent(version)); err != nil {
		return nil, err
	}

	return toTaxRate(taxRate), nil
}

// CreateTaxRateVersion is the resolver for the createTaxRateVersion field.
func (r *mutationResolver) CreateTaxRateVersion(ctx context.Context, input CreateTaxRateVersionInput) (*TaxRateVersion, error) {
	if _, err := auth.RequireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}

	version, err := r.Store.CreateTaxRateVersion(ctx, input.TaxRateID, input.Rate, time.Now().UTC())
	if err != nil {
		return nil, err
	}

	if err := events.PublishTaxRateVersionCreated(ctx, r.Dapr, versionEvent(version)); err != nil {
		return nil, err
	}

	return toTaxRateVersion(version), nil
}

// UpdateTaxRate is the resolver for the updateTaxRate field.
func (r *mutationResolver) UpdateTaxRate(ctx context.Context, input UpdateTaxRateInput) (*TaxRate, error) {
	if _, err := auth.RequireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}

	// Partial update; no event is published (matching the original).
	taxRate, err := r.Store.UpdateTaxRate(ctx, input.ID, input.Name, input.Description)
	if err != nil {
		return nil, err
	}
	return toTaxRate(taxRate), nil
}

// TaxRate is the resolver for the taxRate field.
func (r *queryResolver) TaxRate(ctx context.Context, id uuid.UUID) (*TaxRate, error) {
	if _, err := auth.RequireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}
	taxRate, err := r.Store.GetTaxRate(ctx, id)
	if err != nil {
		return nil, err
	}
	return toTaxRate(taxRate), nil
}

// TaxRateVersion is the resolver for the taxRateVersion field.
func (r *queryResolver) TaxRateVersion(ctx context.Context, id uuid.UUID) (*TaxRateVersion, error) {
	if _, err := auth.RequireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}
	version, err := r.Store.GetTaxRateVersion(ctx, id)
	if err != nil {
		return nil, err
	}
	return toTaxRateVersion(version), nil
}

// TaxRates is the resolver for the taxRates field.
func (r *queryResolver) TaxRates(ctx context.Context, first *int, orderBy *TaxRateOrderInput, skip *int) (*TaxRateConnection, error) {
	if _, err := auth.RequireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}
	col, asc := taxRateOrder(orderBy)
	conn, err := r.Store.ListTaxRates(ctx, first, skip, col, asc)
	if err != nil {
		return nil, err
	}
	return toTaxRateConnection(conn), nil
}

// CurrentVersion is the resolver for the currentVersion field.
func (r *taxRateResolver) CurrentVersion(ctx context.Context, obj *TaxRate) (*TaxRateVersion, error) {
	// No auth check: the original resolved this via the shared data loader
	// without an employee check.
	version, err := r.Store.GetTaxRateVersion(ctx, obj.CurrentVersionID)
	if err != nil {
		return nil, err
	}
	return toTaxRateVersion(version), nil
}

// Versions is the resolver for the versions field.
func (r *taxRateResolver) Versions(ctx context.Context, obj *TaxRate, first *int, orderBy *TaxRateVersionOrderInput, skip *int) (*TaxRateVersionConnection, error) {
	if _, err := auth.RequireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}
	col, asc := taxRateVersionOrder(orderBy)
	conn, err := r.Store.ListTaxRateVersions(ctx, obj.ID, first, skip, col, asc)
	if err != nil {
		return nil, err
	}
	return toTaxRateVersionConnection(conn), nil
}

// TaxRate is the resolver for the taxRate field.
func (r *taxRateVersionResolver) TaxRate(ctx context.Context, obj *TaxRateVersion) (*TaxRate, error) {
	// No auth check: the original resolved this via the shared data loader.
	taxRate, err := r.Store.GetTaxRate(ctx, obj.TaxRateID)
	if err != nil {
		return nil, err
	}
	return toTaxRate(taxRate), nil
}

// versionEvent maps a stored version to its created-event payload, formatting
// createdAt as the ISO-8601 string the payload expects.
func versionEvent(v store.TaxRateVersion) events.TaxRateVersionCreated {
	return events.TaxRateVersionCreated{
		ID:        v.ID,
		Rate:      v.Rate,
		Version:   v.Version,
		CreatedAt: events.FormatCreatedAt(v.CreatedAt),
		TaxRateID: v.TaxRateID,
	}
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// TaxRate returns TaxRateResolver implementation.
func (r *Resolver) TaxRate() TaxRateResolver { return &taxRateResolver{r} }

// TaxRateVersion returns TaxRateVersionResolver implementation.
func (r *Resolver) TaxRateVersion() TaxRateVersionResolver { return &taxRateVersionResolver{r} }

type (
	mutationResolver       struct{ *Resolver }
	queryResolver          struct{ *Resolver }
	taxRateResolver        struct{ *Resolver }
	taxRateVersionResolver struct{ *Resolver }
)
