package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"
)

// FindMediaByID is the resolver for the findMediaByID field.
//
// The federation entity resolver performs ZERO I/O and NO auth check (matching
// the Rust `media_entity_resolver`, which just constructs `Media { id }`). The
// S3 lookup happens lazily only if the caller then selects `path` (see the
// Media.Path resolver). Returning a bare Media{ID} here is intentional.
func (r *entityResolver) FindMediaByID(ctx context.Context, id uuid.UUID) (*Media, error) {
	return &Media{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
