// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"github.com/google/uuid"
)

// Media object with associated path and id.
type Media struct {
	// Media UUID.
	ID uuid.UUID `json:"id"`
	// Pre-signed path for the media.
	Path string `json:"path"`
}

func (Media) IsEntity() {}

// A connection of medias.
type MediaConnection struct {
	// The resulting entities.
	Nodes []Media `json:"nodes"`
	// Whether this connection has a next page.
	HasNextPage bool `json:"hasNextPage"`
	// The total amount of items in this connection.
	TotalCount int `json:"totalCount"`
}

type Mutation struct {
}

type Query struct {
}
