package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"math"
	"misarch/media/events"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

// Path is the resolver for the path field.
//
// This performs the live S3 lookup + pre-sign, lazily, only when a client
// selects `path` (mirrors the Rust `Media::path` ComplexObject). There is NO
// auth check: any caller that can reach the field (including via _entities from
// another subgraph) gets a pre-signed path.
//
// Steps (faithful to the Rust):
//  1. List objects whose key starts with the media UUID (Prefix = id string).
//  2. Rust pops the last result page then the last object of that page; if
//     either is empty → "Media file of UUID: `<id>` not found." Here an empty
//     key list is the equivalent "not found" condition.
//  3. Pre-sign a GET URL for the (last) matching key with PATH_EXPIRATION_TIME
//     expiry, then rewrite it to PROXY_PATH + urlPath + "?" + query.
func (r *mediaResolver) Path(ctx context.Context, obj *Media) (string, error) {
	keys, err := r.Store.ListByPrefix(ctx, obj.ID.String())
	if err != nil {
		return "", err
	}
	if len(keys) == 0 {
		return "", fmt.Errorf("Media file of UUID: `%s` not found.", obj.ID)
	}
	// Rust takes the LAST object of the last page (`.pop()`); for keys sharing
	// the UUID prefix this is the last in S3 lexical order.
	key := keys[len(keys)-1]
	return r.Store.PresignedPath(ctx, key)
}

// UploadMedia is the resolver for the uploadMedia field.
//
// Uploads a file to MinIO under a new UUID and publishes media/media/created.
// Reproduces the Rust ordering and error strings exactly (see media spec §3.5 /
// §9), including the deliberate quirk that the created-event is published
// BEFORE the PutObject HTTP status is evaluated.
func (r *mutationResolver) UploadMedia(ctx context.Context, mediaFile graphql.Upload) (uuid.UUID, error) {
	if err := authorizeUser(ctx, nil); err != nil {
		return uuid.Nil, err
	}

	// The multipart part MUST carry a Content-Type header; the extension stored
	// in the object key is derived from the MIME SUBTYPE (not the filename).
	if mediaFile.ContentType == "" {
		return uuid.Nil, fmt.Errorf("Content type of file upload does not exist.")
	}
	subtype, err := mimeSubtype(mediaFile.ContentType)
	if err != nil {
		return uuid.Nil, err
	}

	// Read the ENTIRE file into an in-memory buffer (mirrors read_to_end; no
	// streaming multipart to S3).
	buffer, err := readAll(mediaFile)
	if err != nil {
		return uuid.Nil, err
	}

	mediaFileID := uuid.New()
	key := mediaFileID.String() + "." + subtype

	// PutObject first. A transport error propagates here with NO event
	// published (mirrors the Rust `put_object(...).await?` before the publish).
	status, err := r.Store.PutObject(ctx, key, buffer)
	if err != nil {
		return uuid.Nil, err
	}

	// Publish the created event BEFORE checking the PutObject status code
	// (deliberate Rust ordering: a non-200 S3 response still emits the event;
	// a publish transport error fails the mutation with the object already
	// stored — no rollback). See media spec §9.
	if err := events.PublishMediaCreated(ctx, r.Dapr, mediaFileID); err != nil {
		return uuid.Nil, err
	}

	if status != 200 {
		return uuid.Nil, fmt.Errorf("Media file could not be inserted into MinIO.")
	}
	return mediaFileID, nil
}

// GetMedias is the resolver for the getMedias field.
//
// Offset pagination (first/skip), NOT Relay cursor pagination. Requires an
// admin/employee caller. Lists ALL objects, counts them for totalCount, then
// applies skip/first and maps each key to a Media by parsing the UUID out of
// the key's file stem. Any key that fails to parse errors the whole query.
func (r *queryResolver) GetMedias(ctx context.Context, first *int, skip *int) (*MediaConnection, error) {
	if err := authorizeUser(ctx, nil); err != nil {
		return nil, err
	}
	// async-graphql binds first/skip to usize and rejects negatives at
	// coercion time (before the resolver). Match that: negatives are input
	// errors.
	if first != nil && *first < 0 {
		return nil, fmt.Errorf("Invalid value for argument \"first\", expected type \"Int\"")
	}
	if skip != nil && *skip < 0 {
		return nil, fmt.Errorf("Invalid value for argument \"skip\", expected type \"Int\"")
	}

	keys, err := r.Store.ListAll(ctx)
	if err != nil {
		return nil, err
	}

	// total_count = count of ALL objects (before skip/first).
	totalCount := len(keys)

	definitelySkip := 0
	if skip != nil {
		definitelySkip = *skip
	}
	// first omitted → everything after skip (usize::MAX in Rust).
	definitelyFirst := math.MaxInt
	if first != nil {
		definitelyFirst = *first
	}

	// contents.iter().skip(definitelySkip).take(definitelyFirst)
	nodes := make([]Media, 0)
	for i := definitelySkip; i < len(keys); i++ {
		if len(nodes) >= definitelyFirst {
			break
		}
		media, err := mediaFromKey(keys[i])
		if err != nil {
			// Any key that fails to parse errors the whole query.
			return nil, err
		}
		nodes = append(nodes, *media)
	}

	// has_next_page = total_count > len(nodes) + skip.
	hasNextPage := totalCount > len(nodes)+definitelySkip
	return toMediaConnection(nodes, hasNextPage, totalCount), nil
}

// Media returns MediaResolver implementation.
func (r *Resolver) Media() MediaResolver { return &mediaResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mediaResolver    struct{ *Resolver }
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
