package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"
)

// FindOrderByID is the resolver for the findOrderByID field.
func (r *entityResolver) FindOrderByID(ctx context.Context, id uuid.UUID) (*Order, error) {
	// Bare stub, no DB read (the order is owned by the order service).
	return &Order{ID: id}, nil
}

// FindOrderItemByID is the resolver for the findOrderItemByID field.
func (r *entityResolver) FindOrderItemByID(ctx context.Context, id uuid.UUID) (*OrderItem, error) {
	// Found → real order item (with sentWithId); NOT found → stub OrderItem
	// whose sentWith resolves to null (do NOT error). No auth.
	item, ok, err := r.Store.GetOrderItem(ctx, id)
	if err != nil {
		return nil, err
	}
	if !ok {
		return &OrderItem{ID: id}, nil
	}
	return toOrderItem(item), nil
}

// FindReturnByID is the resolver for the findReturnByID field.
func (r *entityResolver) FindReturnByID(ctx context.Context, id uuid.UUID) (*Return, error) {
	// Bare stub, no DB read (the return is owned by the return service).
	return &Return{ID: id}, nil
}

// FindShipmentByID is the resolver for the findShipmentByID field.
func (r *entityResolver) FindShipmentByID(ctx context.Context, id uuid.UUID) (*Shipment, error) {
	// Owned entity; a missing id → error (data-loader miss surfaced an error).
	shipment, err := r.Store.GetShipment(ctx, id)
	if err != nil {
		return nil, err
	}
	return toShipment(shipment), nil
}

// FindShipmentMethodByID is the resolver for the findShipmentMethodByID field.
func (r *entityResolver) FindShipmentMethodByID(ctx context.Context, id uuid.UUID) (*ShipmentMethod, error) {
	// Owned entity; a missing id → error.
	method, err := r.Store.GetShipmentMethod(ctx, id)
	if err != nil {
		return nil, err
	}
	return toShipmentMethod(method), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
