// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// An item in an order.
type Address interface {
	IsAddress()
}

// An object with an ID.
type Node interface {
	IsNode()
}

// Input for the archiveShipmentMethod mutation.
type ArchiveShipmentMethodInput struct {
	// The id of the shipment method to archive.
	ID uuid.UUID `json:"id"`
}

// Input for calculateShipmentFees query.
type CalculateShipmentFeesInput struct {
	// The items to calculate the shipment fees for.
	Items []ProductVariantVersionWithQuantityAndShipmentMethodInput `json:"items"`
}

// Input for the createShipmentMethod mutation.
type CreateShipmentMethodInput struct {
	// The base fees for the shipment method.
	BaseFees int `json:"baseFees"`
	// The description of the shipment method.
	Description string `json:"description"`
	// The reference of the shipment method used by the external shipment provider.
	ExternalReference string `json:"externalReference"`
	// The fees per item for the shipment method.
	FeesPerItem int `json:"feesPerItem"`
	// The fees per kg for the shipment method.
	FeesPerKg int `json:"feesPerKg"`
	// The name of the shipment method.
	Name string `json:"name"`
}

type Mutation struct {
}

// The Order of a user.
type Order struct {
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// Get all associated Shipments
	Shipments *ShipmentConnection `json:"shipments"`
}

func (Order) IsNode() {}

func (Order) IsEntity() {}

// An item in an order.
type OrderItem struct {
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The shipment this order item was originally sent with.
	SentWith   *Shipment  `json:"sentWith,omitempty"`
	SentWithID *uuid.UUID `json:"-"`
}

func (OrderItem) IsNode() {}

func (OrderItem) IsEntity() {}

// A connection to a list of `OrderItem` values.
type OrderItemConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []OrderItem `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// OrderItem order
type OrderItemOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *OrderItemOrderField `json:"field,omitempty"`
}

// Input for a product variant version with a quantity and shipment method.
type ProductVariantVersionWithQuantityAndShipmentMethodInput struct {
	// The product variant version id.
	ProductVariantVersionID uuid.UUID `json:"productVariantVersionId"`
	// The quantity of the product variant version.
	Quantity int `json:"quantity"`
	// The id of the shipment method.
	ShipmentMethodID uuid.UUID `json:"shipmentMethodId"`
}

// Input for a product variant version with a quantity.
type ProductVariantVersionWithQuantityInput struct {
	// The product variant version id.
	ProductVariantVersionID uuid.UUID `json:"productVariantVersionId"`
	// The quantity of the product variant version.
	Quantity int `json:"quantity"`
}

type Query struct {
}

// A return one or more OrderItems.
type Return struct {
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The associated Shipment
	Shipment *Shipment `json:"shipment"`
}

func (Return) IsNode() {}

func (Return) IsEntity() {}

// A shipment caused by either an order or a return.
type Shipment struct {
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The order creating this shipment.
	Order *Order `json:"order,omitempty"`
	// The product return causing this shipment.
	Return *Return `json:"return,omitempty"`
	// Get all OrderItems sent with this shipment
	SentItems *OrderItemConnection `json:"sentItems"`
	// The address this shipment is sent to.
	ShipmentAddress Address `json:"shipmentAddress"`
	// The shipment method this shipment uses.
	ShipmentMethod *ShipmentMethod `json:"shipmentMethod"`
	// The status of the shipment.
	Status            ShipmentStatus `json:"status"`
	OrderID           *uuid.UUID     `json:"-"`
	ReturnID          *uuid.UUID     `json:"-"`
	ShipmentAddressID uuid.UUID      `json:"-"`
	ShipmentMethodID  uuid.UUID      `json:"-"`
}

func (Shipment) IsNode() {}

func (Shipment) IsEntity() {}

// A connection to a list of `Shipment` values.
type ShipmentConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []Shipment `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// Shipment filter
type ShipmentFilterInput struct {
	// Filter shipments by their status
	Status *ShipmentStatus `json:"status,omitempty"`
}

// A shipment method supported by the external provider.
type ShipmentMethod struct {
	// If this shipment method is archived, the datetime it was archived.
	ArchivedAt *time.Time `json:"archivedAt,omitempty"`
	// The base fees for the shipment method.
	BaseFees int `json:"baseFees"`
	// Calculates the fees for a potential shipment.
	CalculateFees int `json:"calculateFees"`
	// The description of the shipment method.
	Description string `json:"description"`
	// The reference of the shipment method used by the external shipment provider.
	ExternalReference string `json:"externalReference"`
	// The fees per item for the shipment method.
	FeesPerItem int `json:"feesPerItem"`
	// The fees per kg for the shipment method.
	FeesPerKg int `json:"feesPerKg"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// If true, this shipment method is archived and can no longer be used.
	IsArchived bool `json:"isArchived"`
	// The name of the shipment method.
	Name        string `json:"name"`
	ExternalRef string `json:"-"`
}

func (ShipmentMethod) IsNode() {}

func (ShipmentMethod) IsEntity() {}

// A connection to a list of `ShipmentMethod` values.
type ShipmentMethodConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []ShipmentMethod `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// Shipment method filter
type ShipmentMethodFilterInput struct {
	// Filter shipment methods by their archived status
	IsArchived *bool `json:"isArchived,omitempty"`
}

// Shipment method order
type ShipmentMethodOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *ShipmentMethodOrderField `json:"field,omitempty"`
}

// Shipment  order
type ShipmentOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *ShipmentOrderField `json:"field,omitempty"`
}

// A address associated with a user.
type UserAddress struct {
	// The ID of the node.
	ID uuid.UUID `json:"id"`
}

func (UserAddress) IsAddress() {}

func (UserAddress) IsEntity() {}

// An address associated with the vendor.
type VendorAddress struct {
	// The ID of the node.
	ID uuid.UUID `json:"id"`
}

func (VendorAddress) IsAddress() {}

func (VendorAddress) IsEntity() {}

// Order direction
type OrderDirection string

const (
	// Ascending order
	OrderDirectionAsc OrderDirection = "ASC"
	// Descending order
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// OrderItem order fields
type OrderItemOrderField string

const (
	// Order order items by their id
	OrderItemOrderFieldID OrderItemOrderField = "ID"
)

var AllOrderItemOrderField = []OrderItemOrderField{
	OrderItemOrderFieldID,
}

func (e OrderItemOrderField) IsValid() bool {
	switch e {
	case OrderItemOrderFieldID:
		return true
	}
	return false
}

func (e OrderItemOrderField) String() string {
	return string(e)
}

func (e *OrderItemOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderItemOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderItemOrderField", str)
	}
	return nil
}

func (e OrderItemOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderItemOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderItemOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Shipment method order fields
type ShipmentMethodOrderField string

const (
	// Order shipment methods by their id
	ShipmentMethodOrderFieldID ShipmentMethodOrderField = "ID"
)

var AllShipmentMethodOrderField = []ShipmentMethodOrderField{
	ShipmentMethodOrderFieldID,
}

func (e ShipmentMethodOrderField) IsValid() bool {
	switch e {
	case ShipmentMethodOrderFieldID:
		return true
	}
	return false
}

func (e ShipmentMethodOrderField) String() string {
	return string(e)
}

func (e *ShipmentMethodOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ShipmentMethodOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ShipmentMethodOrderField", str)
	}
	return nil
}

func (e ShipmentMethodOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ShipmentMethodOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ShipmentMethodOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Shipment  order fields
type ShipmentOrderField string

const (
	// Order shipment s by their id
	ShipmentOrderFieldID ShipmentOrderField = "ID"
)

var AllShipmentOrderField = []ShipmentOrderField{
	ShipmentOrderFieldID,
}

func (e ShipmentOrderField) IsValid() bool {
	switch e {
	case ShipmentOrderFieldID:
		return true
	}
	return false
}

func (e ShipmentOrderField) String() string {
	return string(e)
}

func (e *ShipmentOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ShipmentOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ShipmentOrderField", str)
	}
	return nil
}

func (e ShipmentOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ShipmentOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ShipmentOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The status of a shipment.
type ShipmentStatus string

const (
	// The shipment has been delivered.
	ShipmentStatusDelivered ShipmentStatus = "DELIVERED"
	// The shipment has failed.
	ShipmentStatusFailed ShipmentStatus = "FAILED"
	// The shipment is in progress.
	ShipmentStatusInProgress ShipmentStatus = "IN_PROGRESS"
	// The shipment is pending.
	ShipmentStatusPending ShipmentStatus = "PENDING"
)

var AllShipmentStatus = []ShipmentStatus{
	ShipmentStatusDelivered,
	ShipmentStatusFailed,
	ShipmentStatusInProgress,
	ShipmentStatusPending,
}

func (e ShipmentStatus) IsValid() bool {
	switch e {
	case ShipmentStatusDelivered, ShipmentStatusFailed, ShipmentStatusInProgress, ShipmentStatusPending:
		return true
	}
	return false
}

func (e ShipmentStatus) String() string {
	return string(e)
}

func (e *ShipmentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ShipmentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ShipmentStatus", str)
	}
	return nil
}

func (e ShipmentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ShipmentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ShipmentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
