package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"time"

	"github.com/google/uuid"

	"misarch/shipment/events"
	"misarch/shipment/service"
	"misarch/shipment/store"
)

// ArchiveShipmentMethod is the resolver for the archiveShipmentMethod field.
func (r *mutationResolver) ArchiveShipmentMethod(ctx context.Context, input ArchiveShipmentMethodInput) (*ShipmentMethod, error) {
	if err := checkIsEmployee(ctx); err != nil {
		return nil, err
	}

	method, err := r.Store.ArchiveShipmentMethod(ctx, input.ID, time.Now())
	if err != nil {
		return nil, err
	}

	// Publish after the write; the archived event carries only the id.
	if err := events.PublishShipmentMethodArchived(ctx, r.Dapr, events.ShipmentMethodArchived{
		ID: method.ID,
	}); err != nil {
		return nil, err
	}

	return toShipmentMethod(method), nil
}

// CreateShipmentMethod is the resolver for the createShipmentMethod field.
func (r *mutationResolver) CreateShipmentMethod(ctx context.Context, input CreateShipmentMethodInput) (*ShipmentMethod, error) {
	if err := checkIsEmployee(ctx); err != nil {
		return nil, err
	}

	method, err := r.Store.CreateShipmentMethod(
		ctx, input.Name, input.Description, input.ExternalReference,
		input.BaseFees, input.FeesPerItem, input.FeesPerKg,
	)
	if err != nil {
		return nil, err
	}

	// Publish after the write commits (so the id is populated).
	if err := events.PublishShipmentMethodCreated(ctx, r.Dapr, events.ShipmentMethodCreated{
		ID:                method.ID,
		Name:              method.Name,
		Description:       method.Description,
		ExternalReference: method.ExternalReference,
		BaseFees:          method.BaseFees,
		FeesPerItem:       method.FeesPerItem,
		FeesPerKg:         method.FeesPerKg,
	}); err != nil {
		return nil, err
	}

	return toShipmentMethod(method), nil
}

// CalculateShipmentFees is the resolver for the calculateShipmentFees field.
func (r *queryResolver) CalculateShipmentFees(ctx context.Context, input CalculateShipmentFeesInput) (int, error) {
	// @inaccessible: internal-only via network policy; no auth in code.
	items := make([]service.ItemWithQuantityAndMethod, len(input.Items))
	for i, it := range input.Items {
		items[i] = service.ItemWithQuantityAndMethod{
			ProductVariantVersionID: it.ProductVariantVersionID,
			Quantity:                it.Quantity,
			ShipmentMethodID:        it.ShipmentMethodID,
		}
	}
	return r.Service.CalculateShipmentFees(ctx, items)
}

// ShipmentMethod is the resolver for the shipmentMethod field.
func (r *queryResolver) ShipmentMethod(ctx context.Context, id uuid.UUID) (*ShipmentMethod, error) {
	// No auth: the original resolved via a data loader, missing id → error.
	method, err := r.Store.GetShipmentMethod(ctx, id)
	if err != nil {
		return nil, err
	}
	return toShipmentMethod(method), nil
}

// ShipmentMethods is the resolver for the shipmentMethods field.
func (r *queryResolver) ShipmentMethods(ctx context.Context, filter *ShipmentMethodFilterInput, first *int, orderBy *ShipmentMethodOrderInput, skip *int) (*ShipmentMethodConnection, error) {
	// No auth enforced (authorizedUserFilter is null → anyone, even anonymous).
	col, asc := shipmentMethodOrder(orderBy)
	var isArchived *bool
	if filter != nil {
		isArchived = filter.IsArchived
	}
	conn, err := r.Store.ListShipmentMethods(ctx, first, skip, col, asc, isArchived)
	if err != nil {
		return nil, err
	}
	return toShipmentMethodConnection(conn), nil
}

// Shipments is the resolver for the shipments field.
func (r *orderResolver) Shipments(ctx context.Context, obj *Order, filter *ShipmentFilterInput, first *int, orderBy *ShipmentOrderInput, skip *int) (*ShipmentConnection, error) {
	col, asc := shipmentOrder(orderBy)
	var status *ShipmentStatus
	if filter != nil {
		status = filter.Status
	}
	conn, err := r.Store.ListShipmentsForOrder(ctx, obj.ID, first, skip, col, asc, shipmentStatusFilter(status))
	if err != nil {
		return nil, err
	}
	return toShipmentConnection(conn), nil
}

// SentWith is the resolver for the sentWith field.
func (r *orderItemResolver) SentWith(ctx context.Context, obj *OrderItem) (*Shipment, error) {
	// A stub OrderItem (unknown id via federation) has a nil SentWithID and
	// resolves to null; a local order item always has a real sentWithId.
	if obj.SentWithID == nil {
		return nil, nil
	}
	shipment, err := r.Store.GetShipment(ctx, *obj.SentWithID)
	if err != nil {
		return nil, err
	}
	return toShipment(shipment), nil
}

// Shipment is the resolver for the shipment field.
func (r *returnResolver) Shipment(ctx context.Context, obj *Return) (*Shipment, error) {
	// Derived query findByReturnId; no shipment for this return → error
	// (non-null field can't be null).
	shipment, err := r.Store.FindShipmentByReturnID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return toShipment(shipment), nil
}

// Order is the resolver for the order field.
func (r *shipmentResolver) Order(ctx context.Context, obj *Shipment) (*Order, error) {
	// Bare Order(id) stub (no DB read) or null if orderId is null.
	if obj.OrderID == nil {
		return nil, nil
	}
	return &Order{ID: *obj.OrderID}, nil
}

// Return is the resolver for the return field.
func (r *shipmentResolver) Return(ctx context.Context, obj *Shipment) (*Return, error) {
	// Bare Return(id) stub (no DB read) or null if returnId is null.
	if obj.ReturnID == nil {
		return nil, nil
	}
	return &Return{ID: *obj.ReturnID}, nil
}

// SentItems is the resolver for the sentItems field.
func (r *shipmentResolver) SentItems(ctx context.Context, obj *Shipment, first *int, orderBy *OrderItemOrderInput, skip *int) (*OrderItemConnection, error) {
	col, asc := orderItemOrder(orderBy)
	conn, err := r.Store.ListSentItems(ctx, obj.ID, first, skip, col, asc)
	if err != nil {
		return nil, err
	}
	return toOrderItemConnection(conn), nil
}

// ShipmentAddress is the resolver for the shipmentAddress field.
func (r *shipmentResolver) ShipmentAddress(ctx context.Context, obj *Shipment) (Address, error) {
	// Non-null field; a missing address id → error. Discriminated
	// UserAddress/VendorAddress by userId null-ness.
	address, err := r.Store.GetAddress(ctx, obj.ShipmentAddressID)
	if err != nil {
		return nil, err
	}
	return toAddress(address), nil
}

// ShipmentMethod is the resolver for the shipmentMethod field.
func (r *shipmentResolver) ShipmentMethod(ctx context.Context, obj *Shipment) (*ShipmentMethod, error) {
	// Non-null field; a missing method id → error.
	method, err := r.Store.GetShipmentMethod(ctx, obj.ShipmentMethodID)
	if err != nil {
		return nil, err
	}
	return toShipmentMethod(method), nil
}

// CalculateFees is the resolver for the calculateFees field.
func (r *shipmentMethodResolver) CalculateFees(ctx context.Context, obj *ShipmentMethod, items []ProductVariantVersionWithQuantityInput) (int, error) {
	// Public, no auth. Same validation as calculateQuantityAndWeight.
	withQty := make([]service.ItemWithQuantity, len(items))
	for i, it := range items {
		withQty[i] = service.ItemWithQuantity{
			ProductVariantVersionID: it.ProductVariantVersionID,
			Quantity:                it.Quantity,
		}
	}
	quantity, weight, err := r.Service.CalculateQuantityAndWeight(ctx, withQty)
	if err != nil {
		return 0, err
	}
	// baseFees + quantity*feesPerItem + int(weight*feesPerKg).
	return service.CalculateFees(store.ShipmentMethod{
		BaseFees:    obj.BaseFees,
		FeesPerItem: obj.FeesPerItem,
		FeesPerKg:   obj.FeesPerKg,
	}, quantity, weight), nil
}

// ExternalReference is the resolver for the externalReference field.
func (r *shipmentMethodResolver) ExternalReference(ctx context.Context, obj *ShipmentMethod) (string, error) {
	// Per-FIELD authorization: employee or admin only.
	if err := checkIsEmployee(ctx); err != nil {
		return "", err
	}
	return obj.ExternalRef, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

// OrderItem returns OrderItemResolver implementation.
func (r *Resolver) OrderItem() OrderItemResolver { return &orderItemResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Return returns ReturnResolver implementation.
func (r *Resolver) Return() ReturnResolver { return &returnResolver{r} }

// Shipment returns ShipmentResolver implementation.
func (r *Resolver) Shipment() ShipmentResolver { return &shipmentResolver{r} }

// ShipmentMethod returns ShipmentMethodResolver implementation.
func (r *Resolver) ShipmentMethod() ShipmentMethodResolver { return &shipmentMethodResolver{r} }

type (
	mutationResolver       struct{ *Resolver }
	orderResolver          struct{ *Resolver }
	orderItemResolver      struct{ *Resolver }
	queryResolver          struct{ *Resolver }
	returnResolver         struct{ *Resolver }
	shipmentResolver       struct{ *Resolver }
	shipmentMethodResolver struct{ *Resolver }
)
