package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"
)

// FindCategoryByID is the resolver for the findCategoryByID field.
func (r *entityResolver) FindCategoryByID(ctx context.Context, id uuid.UUID) (*Category, error) {
	// Foreign federated stub: resolved from the id only, no DB, no auth, never
	// fails (except UUID parse, handled by the scalar).
	return &Category{ID: id}, nil
}

// FindCouponByID is the resolver for the findCouponByID field.
func (r *entityResolver) FindCouponByID(ctx context.Context, id uuid.UUID) (*Coupon, error) {
	// Owned entity: loaded via the data loader; an unknown id yields a GraphQL
	// error (data null). No auth on entity resolution.
	c, err := r.Store.GetCoupon(ctx, id)
	if err != nil {
		return nil, err
	}
	return toCoupon(c), nil
}

// FindDiscountByID is the resolver for the findDiscountByID field.
func (r *entityResolver) FindDiscountByID(ctx context.Context, id uuid.UUID) (*Discount, error) {
	d, err := r.Store.GetDiscount(ctx, id)
	if err != nil {
		return nil, err
	}
	return toDiscount(d), nil
}

// FindDiscountUsageByID is the resolver for the findDiscountUsageByID field.
func (r *entityResolver) FindDiscountUsageByID(ctx context.Context, id uuid.UUID) (*DiscountUsage, error) {
	u, err := r.Store.GetDiscountUsage(ctx, id)
	if err != nil {
		return nil, err
	}
	return toDiscountUsage(u), nil
}

// FindProductByID is the resolver for the findProductByID field.
func (r *entityResolver) FindProductByID(ctx context.Context, id uuid.UUID) (*Product, error) {
	return &Product{ID: id}, nil
}

// FindProductVariantByID is the resolver for the findProductVariantByID field.
func (r *entityResolver) FindProductVariantByID(ctx context.Context, id uuid.UUID) (*ProductVariant, error) {
	return &ProductVariant{ID: id}, nil
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	return &User{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
