// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

// An object with an ID.
type Node interface {
	IsNode()
}

// A category
type Category struct {
	// Get all discounts which apply directly to this category
	Discounts *DiscountConnection `json:"discounts"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
}

func (Category) IsNode() {}

func (Category) IsEntity() {}

// A connection to a list of `Category` values.
type CategoryConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []Category `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// Discount order
type CommonOrderInput struct {
	// The direction to order by
	Direction graphql.Omittable[*OrderDirection] `json:"direction,omitempty"`
	// The field to order by
	Field graphql.Omittable[*CommonOrderField] `json:"field,omitempty"`
}

// A coupon
type Coupon struct {
	// The code of the coupon.
	Code string `json:"code"`
	// The discount granted by this coupon.
	Discount *Discount `json:"discount"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The maximum number of times the coupon can be used.
	MaxUsages *int `json:"maxUsages,omitempty"`
	// The number of times the coupon has been used.
	Usages int `json:"usages"`
	// Get all users who claimed this coupon.
	Users *UserConnection `json:"users"`
	// The date and time from which the coupon is valid.
	ValidFrom time.Time `json:"validFrom"`
	// The date and time until which the coupon is valid.
	ValidUntil     time.Time `json:"validUntil"`
	DiscountID     uuid.UUID `json:"-"`
	MaxUsagesValue *int      `json:"-"`
	UsagesValue    int       `json:"-"`
}

func (Coupon) IsNode() {}

func (Coupon) IsEntity() {}

// A connection to a list of `Coupon` values.
type CouponConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []Coupon `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// Coupon filter
type CouponFilterInput struct {
	// Filter weather the user with the provided id own the coupon, other users than the authenticated user require at least EMPLOYEE
	UserHasCoupon graphql.Omittable[*uuid.UUID] `json:"userHasCoupon,omitempty"`
}

// Coupon order
type CouponOrderInput struct {
	// The direction to order by
	Direction graphql.Omittable[*OrderDirection] `json:"direction,omitempty"`
	// The field to order by
	Field graphql.Omittable[*CouponOrderField] `json:"field,omitempty"`
}

// Input for the createCoupon mutation.
type CreateCouponInput struct {
	// The code of the coupon.
	Code string `json:"code"`
	// The id of the discount the coupon is for.
	DiscountID uuid.UUID `json:"discountId"`
	// The maximum number of times the coupon can be used.
	MaxUsages int `json:"maxUsages"`
	// The date and time from which the coupon is valid.
	ValidFrom time.Time `json:"validFrom"`
	// The date and time until which the coupon is valid.
	ValidUntil time.Time `json:"validUntil"`
}

// Input for the createDiscount mutation.
type CreateDiscountInput struct {
	// The discount applied to the order item.
	Discount float64 `json:"discount"`
	// The category ids to which the discount applies.
	DiscountAppliesToCategoryIds []uuid.UUID `json:"discountAppliesToCategoryIds"`
	// The product ids to which the discount applies.
	DiscountAppliesToProductIds []uuid.UUID `json:"discountAppliesToProductIds"`
	// The product variant ids to which the discount applies.
	DiscountAppliesToProductVariantIds []uuid.UUID `json:"discountAppliesToProductVariantIds"`
	// The maximum number of times a user can use this discount in bought ProductItems.
	MaxUsagesPerUser int `json:"maxUsagesPerUser"`
	// The minimum order amount required to use this discount.
	MinOrderAmount graphql.Omittable[*int] `json:"minOrderAmount,omitempty"`
	// The date and time from which the discount is valid.
	ValidFrom time.Time `json:"validFrom"`
	// The date and time until which the discount is valid.
	ValidUntil time.Time `json:"validUntil"`
}

// A discount.
// Multiple discounts are applied multiplicatively:
// discounted = original * (1 - discount1) * (1 - discount2) * ...
type Discount struct {
	// The discount applied to the order item, e.g. 0.2 meaning a 20% reduction in price.
	// Multiple discounts are applied multiplicatively:
	// discounted = original * (1 - discount1) * (1 - discount2) * ...
	Discount float64 `json:"discount"`
	// Get all categories to which this discount directly applies
	DiscountAppliesToCategories *CategoryConnection `json:"discountAppliesToCategories"`
	// Get all product variants to which this discount directly applies
	DiscountAppliesToProductVariants *ProductVariantConnection `json:"discountAppliesToProductVariants"`
	// Get all products to which this discount directly applies
	DiscountAppliesToProducts *ProductConnection `json:"discountAppliesToProducts"`
	// Get all product variants to which this discount directly applies
	DiscountRequiresCoupon *CouponConnection `json:"discountRequiresCoupon"`
	// Get all the usages of this discount by all users.
	DiscountUsages *DiscountUsageConnection `json:"discountUsages"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The maximum number of times a user can use this discount in bought ProductItems.
	MaxUsagesPerUser *int `json:"maxUsagesPerUser,omitempty"`
	// The minimum order amount required to use this discount.
	MinOrderAmount *int `json:"minOrderAmount,omitempty"`
	// The date and time from which the discount is valid.
	ValidFrom time.Time `json:"validFrom"`
	// The date and time until which the discount is valid.
	ValidUntil time.Time `json:"validUntil"`
}

func (Discount) IsNode() {}

func (Discount) IsEntity() {}

// A connection to a list of `Discount` values.
type DiscountConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []Discount `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// Discount order
type DiscountOrderInput struct {
	// The direction to order by
	Direction graphql.Omittable[*OrderDirection] `json:"direction,omitempty"`
	// The field to order by
	Field graphql.Omittable[*DiscountOrderField] `json:"field,omitempty"`
}

// Discount usage by a user.
type DiscountUsage struct {
	// The used discount.
	Discount *Discount `json:"discount"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The amount of items the user has used this discount for.
	Usages int `json:"usages"`
	// The user using the discount.
	User       *User     `json:"user"`
	DiscountID uuid.UUID `json:"-"`
	UserID     uuid.UUID `json:"-"`
}

func (DiscountUsage) IsNode() {}

func (DiscountUsage) IsEntity() {}

// A connection to a list of `DiscountUsage` values.
type DiscountUsageConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []DiscountUsage `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// DiscountUsage order
type DiscountUsageOrderInput struct {
	// The direction to order by
	Direction graphql.Omittable[*OrderDirection] `json:"direction,omitempty"`
	// The field to order by
	Field graphql.Omittable[*DiscountUsageOrderField] `json:"field,omitempty"`
}

// A list of discounts for a product variant (and count)
type DiscountsForProductVariant struct {
	// The number of items to which the discounts should be applied.
	Count int `json:"count"`
	// The list of applicable discounts
	Discounts []Discount `json:"discounts"`
	// The product variant id for which discounts should be computed.
	ProductVariantID uuid.UUID `json:"productVariantId"`
}

// Input for the findApplicableDiscounts query.
type FindApplicableDiscountsInput struct {
	// The order amount, used to filter applicable discounts.
	OrderAmount int `json:"orderAmount"`
	// The list of product variants for which discounts should be computed.
	ProductVariants []FindApplicableDiscountsProductVariantInput `json:"productVariants"`
	// The user id for which discounts should be computed.
	UserID uuid.UUID `json:"userId"`
}

// Triple of a product variant id, a count, and a list of coupon ids for which discounts should be computed
type FindApplicableDiscountsProductVariantInput struct {
	// The number of items to which the discounts should be applied.
	Count int `json:"count"`
	// The list of coupon ids for which discounts should be computed.
	CouponIds []uuid.UUID `json:"couponIds"`
	// The product variant id for which discounts should be computed.
	ProductVariantID uuid.UUID `json:"productVariantId"`
}

type Mutation struct {
}

// A product
type Product struct {
	// Get all discounts which apply directly to this product
	Discounts *DiscountConnection `json:"discounts"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
}

func (Product) IsNode() {}

func (Product) IsEntity() {}

// A connection to a list of `Product` values.
type ProductConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []Product `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// A product variant
type ProductVariant struct {
	// Get all discounts which apply to this product variant for the authenticated user
	ApplicableDiscounts *DiscountConnection `json:"applicableDiscounts"`
	// Get all discounts which apply directly to this product variant
	Discounts *DiscountConnection `json:"discounts"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
}

func (ProductVariant) IsNode() {}

func (ProductVariant) IsEntity() {}

// A connection to a list of `ProductVariant` values.
type ProductVariantConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []ProductVariant `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

type Query struct {
}

// Input for the registerCoupon mutation
type RegisterCouponInput struct {
	// The code of the coupon.
	Code string `json:"code"`
	// The user who wants to register the coupon.
	UserID uuid.UUID `json:"userId"`
}

// Input for the updateCoupon mutation.
type UpdateCouponInput struct {
	// The code of the coupon.
	Code graphql.Omittable[*string] `json:"code,omitempty"`
	// The id of the coupon to update.
	ID uuid.UUID `json:"id"`
	// The maximum number of times the coupon can be used.
	MaxUsages graphql.Omittable[*int] `json:"maxUsages,omitempty"`
	// The date and time from which the coupon is valid.
	ValidFrom graphql.Omittable[*time.Time] `json:"validFrom,omitempty"`
	// The date and time until which the coupon is valid.
	ValidUntil graphql.Omittable[*time.Time] `json:"validUntil,omitempty"`
}

// Input for the updateDiscount mutation.
type UpdateDiscountInput struct {
	// Added category ids to which the discount applies.
	AddedDiscountAppliesToCategoryIds graphql.Omittable[[]uuid.UUID] `json:"addedDiscountAppliesToCategoryIds,omitempty"`
	// Added product ids to which the discount applies.
	AddedDiscountAppliesToProductIds graphql.Omittable[[]uuid.UUID] `json:"addedDiscountAppliesToProductIds,omitempty"`
	// Added product variant ids to which the discount applies.
	AddedDiscountAppliesToProductVariantIds graphql.Omittable[[]uuid.UUID] `json:"addedDiscountAppliesToProductVariantIds,omitempty"`
	// The id of the discount to update.
	ID uuid.UUID `json:"id"`
	// The discount applied to the order item.
	MaxUsagesPerUser graphql.Omittable[*int] `json:"maxUsagesPerUser,omitempty"`
	// The minimum order amount required to use this discount.
	MinOrderAmount graphql.Omittable[*int] `json:"minOrderAmount,omitempty"`
	// Removed category ids to which the discount applies.
	RemovedDiscountAppliesToCategoryIds graphql.Omittable[[]uuid.UUID] `json:"removedDiscountAppliesToCategoryIds,omitempty"`
	// Removed product ids to which the discount applies.
	RemovedDiscountAppliesToProductIds graphql.Omittable[[]uuid.UUID] `json:"removedDiscountAppliesToProductIds,omitempty"`
	// Removed product variant ids to which the discount applies.
	RemovedDiscountAppliesToProductVariantIds graphql.Omittable[[]uuid.UUID] `json:"removedDiscountAppliesToProductVariantIds,omitempty"`
	// The date and time from which the discount is valid.
	ValidFrom graphql.Omittable[*time.Time] `json:"validFrom,omitempty"`
	// The date and time until which the discount is valid.
	ValidUntil graphql.Omittable[*time.Time] `json:"validUntil,omitempty"`
}

// A user.
type User struct {
	// Get all coupons this user has claimed
	Coupons *CouponConnection `json:"coupons"`
	// Get all the discount usages by this user
	DiscountUsages *DiscountUsageConnection `json:"discountUsages"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
}

func (User) IsNode() {}

func (User) IsEntity() {}

// A connection to a list of `User` values.
type UserConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []User `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// Common order fields
type CommonOrderField string

const (
	// Order entities by their id
	CommonOrderFieldID CommonOrderField = "ID"
)

var AllCommonOrderField = []CommonOrderField{
	CommonOrderFieldID,
}

func (e CommonOrderField) IsValid() bool {
	switch e {
	case CommonOrderFieldID:
		return true
	}
	return false
}

func (e CommonOrderField) String() string {
	return string(e)
}

func (e *CommonOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommonOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommonOrderField", str)
	}
	return nil
}

func (e CommonOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommonOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommonOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Coupon order fields
type CouponOrderField string

const (
	// Order coupons by their id
	CouponOrderFieldID CouponOrderField = "ID"
	// Order coupons by the valid from date
	CouponOrderFieldValidFrom CouponOrderField = "VALID_FROM"
	// Order coupons by the valid until date
	CouponOrderFieldValidUntil CouponOrderField = "VALID_UNTIL"
)

var AllCouponOrderField = []CouponOrderField{
	CouponOrderFieldID,
	CouponOrderFieldValidFrom,
	CouponOrderFieldValidUntil,
}

func (e CouponOrderField) IsValid() bool {
	switch e {
	case CouponOrderFieldID, CouponOrderFieldValidFrom, CouponOrderFieldValidUntil:
		return true
	}
	return false
}

func (e CouponOrderField) String() string {
	return string(e)
}

func (e *CouponOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CouponOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CouponOrderField", str)
	}
	return nil
}

func (e CouponOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CouponOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CouponOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Discount order fields
type DiscountOrderField string

const (
	// Order discounts by their id
	DiscountOrderFieldID DiscountOrderField = "ID"
	// Order discounts by the valid from date
	DiscountOrderFieldValidFrom DiscountOrderField = "VALID_FROM"
	// Order discounts by the valid until date
	DiscountOrderFieldValidUntil DiscountOrderField = "VALID_UNTIL"
)

var AllDiscountOrderField = []DiscountOrderField{
	DiscountOrderFieldID,
	DiscountOrderFieldValidFrom,
	DiscountOrderFieldValidUntil,
}

func (e DiscountOrderField) IsValid() bool {
	switch e {
	case DiscountOrderFieldID, DiscountOrderFieldValidFrom, DiscountOrderFieldValidUntil:
		return true
	}
	return false
}

func (e DiscountOrderField) String() string {
	return string(e)
}

func (e *DiscountOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiscountOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiscountOrderField", str)
	}
	return nil
}

func (e DiscountOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DiscountOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DiscountOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// DiscountUsage order fields
type DiscountUsageOrderField string

const (
	// Order discount usages by their id
	DiscountUsageOrderFieldID DiscountUsageOrderField = "ID"
	// Order discount usages by their usages
	DiscountUsageOrderFieldUsages DiscountUsageOrderField = "USAGES"
)

var AllDiscountUsageOrderField = []DiscountUsageOrderField{
	DiscountUsageOrderFieldID,
	DiscountUsageOrderFieldUsages,
}

func (e DiscountUsageOrderField) IsValid() bool {
	switch e {
	case DiscountUsageOrderFieldID, DiscountUsageOrderFieldUsages:
		return true
	}
	return false
}

func (e DiscountUsageOrderField) String() string {
	return string(e)
}

func (e *DiscountUsageOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiscountUsageOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiscountUsageOrderField", str)
	}
	return nil
}

func (e DiscountUsageOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DiscountUsageOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DiscountUsageOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Order direction
type OrderDirection string

const (
	// Ascending order
	OrderDirectionAsc OrderDirection = "ASC"
	// Descending order
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
