package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"time"

	"github.com/google/uuid"

	"misarch/discount/events"
	"misarch/discount/store"
)

// ---- Category (foreign entity) -------------------------------------------

// Discounts is the resolver for the discounts field.
func (r *categoryResolver) Discounts(ctx context.Context, obj *Category, first *int, orderBy *DiscountOrderInput, skip *int) (*DiscountConnection, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	cols, asc := discountOrder(orderBy)
	conn, err := r.Store.DiscountsByCategory(ctx, obj.ID, first, skip, cols, asc)
	if err != nil {
		return nil, err
	}
	return toDiscountConnection(conn), nil
}

// ---- Coupon (owned entity) -----------------------------------------------

// Discount is the resolver for the discount field.
func (r *couponResolver) Discount(ctx context.Context, obj *Coupon) (*Discount, error) {
	// No explicit auth (loaded via the data loader); the FK guarantees it exists.
	d, err := r.Store.GetDiscount(ctx, obj.DiscountID)
	if err != nil {
		return nil, err
	}
	return toDiscount(d), nil
}

// MaxUsages is the resolver for the maxUsages field.
func (r *couponResolver) MaxUsages(ctx context.Context, obj *Coupon) (*int, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	return obj.MaxUsagesValue, nil
}

// Usages is the resolver for the usages field.
func (r *couponResolver) Usages(ctx context.Context, obj *Coupon) (int, error) {
	if err := requireEmployee(ctx); err != nil {
		return 0, err
	}
	return obj.UsagesValue, nil
}

// Users is the resolver for the users field.
func (r *couponResolver) Users(ctx context.Context, obj *Coupon, first *int, orderBy *CommonOrderInput, skip *int) (*UserConnection, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	cols, asc := commonOrder(orderBy, store.UserOrderByID)
	conn, err := r.Store.UsersByCoupon(ctx, obj.ID, first, skip, cols, asc)
	if err != nil {
		return nil, err
	}
	return toUserConnection(conn), nil
}

// ---- Discount (owned entity) ---------------------------------------------

// DiscountAppliesToCategories is the resolver for the discountAppliesToCategories field.
func (r *discountResolver) DiscountAppliesToCategories(ctx context.Context, obj *Discount, first *int, orderBy *CommonOrderInput, skip *int) (*CategoryConnection, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	cols, asc := commonOrder(orderBy, store.CategoryOrderByID)
	conn, err := r.Store.CategoriesByDiscount(ctx, obj.ID, first, skip, cols, asc)
	if err != nil {
		return nil, err
	}
	return toCategoryConnection(conn), nil
}

// DiscountAppliesToProductVariants is the resolver for the discountAppliesToProductVariants field.
func (r *discountResolver) DiscountAppliesToProductVariants(ctx context.Context, obj *Discount, first *int, orderBy *CommonOrderInput, skip *int) (*ProductVariantConnection, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	cols, asc := commonOrder(orderBy, store.ProductVariantOrderByID)
	conn, err := r.Store.ProductVariantsByDiscount(ctx, obj.ID, first, skip, cols, asc)
	if err != nil {
		return nil, err
	}
	return toProductVariantConnection(conn), nil
}

// DiscountAppliesToProducts is the resolver for the discountAppliesToProducts field.
func (r *discountResolver) DiscountAppliesToProducts(ctx context.Context, obj *Discount, first *int, orderBy *CommonOrderInput, skip *int) (*ProductConnection, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	cols, asc := commonOrder(orderBy, store.ProductOrderByID)
	conn, err := r.Store.ProductsByDiscount(ctx, obj.ID, first, skip, cols, asc)
	if err != nil {
		return nil, err
	}
	return toProductConnection(conn), nil
}

// DiscountRequiresCoupon is the resolver for the discountRequiresCoupon field.
func (r *discountResolver) DiscountRequiresCoupon(ctx context.Context, obj *Discount, filter *CouponFilterInput, first *int, orderBy *CouponOrderInput, skip *int) (*CouponConnection, error) {
	// No explicit employee check here (unlike the sibling resolvers): the
	// CouponConnection's own user-scoped filter (§6) gates it — anonymous ->
	// empty, non-employee -> own coupons only, employee -> all. The filter's
	// auth (userHasCoupon) still applies.
	if err := applyCouponFilterAuth(ctx, filter); err != nil {
		return nil, err
	}
	cols, asc := couponOrder(orderBy)
	conn, err := r.Store.CouponsByDiscount(ctx, obj.ID, couponFilter(filter), authUser(ctx), first, skip, cols, asc)
	if err != nil {
		return nil, err
	}
	return toCouponConnection(conn), nil
}

// DiscountUsages is the resolver for the discountUsages field.
func (r *discountResolver) DiscountUsages(ctx context.Context, obj *Discount, first *int, orderBy *DiscountUsageOrderInput, skip *int) (*DiscountUsageConnection, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	cols, asc := discountUsageOrder(orderBy)
	conn, err := r.Store.DiscountUsagesByDiscount(ctx, obj.ID, first, skip, cols, asc)
	if err != nil {
		return nil, err
	}
	return toDiscountUsageConnection(conn), nil
}

// ---- DiscountUsage (owned entity) ----------------------------------------

// Discount is the resolver for the discount field.
func (r *discountUsageResolver) Discount(ctx context.Context, obj *DiscountUsage) (*Discount, error) {
	// No explicit auth on the field itself (gated by its entry point).
	d, err := r.Store.GetDiscount(ctx, obj.DiscountID)
	if err != nil {
		return nil, err
	}
	return toDiscount(d), nil
}

// User is the resolver for the user field.
func (r *discountUsageResolver) User(ctx context.Context, obj *DiscountUsage) (*User, error) {
	// The original loads the user via the data loader (a foreign stub keyed by
	// id); no DB lookup, no auth.
	return &User{ID: obj.UserID}, nil
}

// ---- Mutation ------------------------------------------------------------

// CreateCoupon is the resolver for the createCoupon field.
func (r *mutationResolver) CreateCoupon(ctx context.Context, input CreateCouponInput) (*Coupon, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	maxUsages := input.MaxUsages
	coupon, err := r.Store.CreateCoupon(ctx, store.CreateCouponParams{
		Code:       input.Code,
		DiscountID: input.DiscountID,
		MaxUsages:  &maxUsages,
		ValidFrom:  input.ValidFrom,
		ValidUntil: input.ValidUntil,
	})
	if err != nil {
		return nil, err
	}
	if err := events.PublishCouponCreated(ctx, r.Dapr, couponEvent(coupon)); err != nil {
		return nil, err
	}
	return toCoupon(coupon), nil
}

// CreateDiscount is the resolver for the createDiscount field.
func (r *mutationResolver) CreateDiscount(ctx context.Context, input CreateDiscountInput) (*Discount, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	maxUsagesPerUser := input.MaxUsagesPerUser
	discount, applies, err := r.Store.CreateDiscount(ctx, store.CreateDiscountParams{
		Discount:         input.Discount,
		MaxUsagesPerUser: &maxUsagesPerUser,
		// createDiscount's minOrderAmount is a plain nullable Int: null stores
		// NULL. .Value() (nil for absent-or-null) captures that.
		MinOrderAmount: input.MinOrderAmount.Value(),
		ValidFrom:      input.ValidFrom,
		ValidUntil:     input.ValidUntil,
		AppliesTo: store.AppliesTo{
			CategoryIDs:       input.DiscountAppliesToCategoryIds,
			ProductIDs:        input.DiscountAppliesToProductIds,
			ProductVariantIDs: input.DiscountAppliesToProductVariantIds,
		},
	})
	if err != nil {
		return nil, err
	}
	if err := events.PublishDiscountCreated(ctx, r.Dapr, discountEvent(discount, applies)); err != nil {
		return nil, err
	}
	return toDiscount(discount), nil
}

// RegisterCoupon is the resolver for the registerCoupon field.
func (r *mutationResolver) RegisterCoupon(ctx context.Context, input RegisterCouponInput) (*Coupon, error) {
	if err := requireSelfOrEmployee(ctx, input.UserID); err != nil {
		return nil, err
	}
	coupon, err := r.Store.RegisterCoupon(ctx, input.Code, input.UserID, time.Now().UTC())
	if err != nil {
		return nil, err
	}
	// No event published (matching the original).
	return toCoupon(coupon), nil
}

// UpdateCoupon is the resolver for the updateCoupon field.
func (r *mutationResolver) UpdateCoupon(ctx context.Context, input UpdateCouponInput) (*Coupon, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	coupon, err := r.Store.UpdateCoupon(ctx, store.UpdateCouponParams{
		ID:         input.ID,
		Code:       input.Code.Value(),
		ValidFrom:  input.ValidFrom.Value(),
		ValidUntil: input.ValidUntil.Value(),
		MaxUsages:  optionalInt(input.MaxUsages),
	})
	if err != nil {
		return nil, err
	}
	if err := events.PublishCouponUpdated(ctx, r.Dapr, couponEvent(coupon)); err != nil {
		return nil, err
	}
	return toCoupon(coupon), nil
}

// UpdateDiscount is the resolver for the updateDiscount field.
func (r *mutationResolver) UpdateDiscount(ctx context.Context, input UpdateDiscountInput) (*Discount, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	discount, applies, err := r.Store.UpdateDiscount(ctx, store.UpdateDiscountParams{
		ID:                       input.ID,
		MaxUsagesPerUser:         optionalInt(input.MaxUsagesPerUser),
		MinOrderAmount:           optionalInt(input.MinOrderAmount),
		ValidFrom:                input.ValidFrom.Value(),
		ValidUntil:               input.ValidUntil.Value(),
		AddedCategoryIDs:         input.AddedDiscountAppliesToCategoryIds.Value(),
		AddedProductIDs:          input.AddedDiscountAppliesToProductIds.Value(),
		AddedProductVariantIDs:   input.AddedDiscountAppliesToProductVariantIds.Value(),
		RemovedCategoryIDs:       input.RemovedDiscountAppliesToCategoryIds.Value(),
		RemovedProductIDs:        input.RemovedDiscountAppliesToProductIds.Value(),
		RemovedProductVariantIDs: input.RemovedDiscountAppliesToProductVariantIds.Value(),
	})
	if err != nil {
		return nil, err
	}
	if err := events.PublishDiscountUpdated(ctx, r.Dapr, discountEvent(discount, applies)); err != nil {
		return nil, err
	}
	return toDiscount(discount), nil
}

// ---- Product (foreign entity) --------------------------------------------

// Discounts is the resolver for the discounts field.
func (r *productResolver) Discounts(ctx context.Context, obj *Product, first *int, orderBy *DiscountOrderInput, skip *int) (*DiscountConnection, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	cols, asc := discountOrder(orderBy)
	conn, err := r.Store.DiscountsByProduct(ctx, obj.ID, first, skip, cols, asc)
	if err != nil {
		return nil, err
	}
	return toDiscountConnection(conn), nil
}

// ---- ProductVariant (foreign entity) -------------------------------------

// ApplicableDiscounts is the resolver for the applicableDiscounts field.
func (r *productVariantResolver) ApplicableDiscounts(ctx context.Context, obj *ProductVariant, first *int, orderBy *DiscountOrderInput, skip *int) (*DiscountConnection, error) {
	// NOT employee-gated (public-ish): uses authorizedUserOrNull; coupon-required
	// discounts are only shown if the user owns a coupon for them.
	cols, asc := discountOrder(orderBy)
	conn, err := r.Store.ApplicableDiscounts(ctx, obj.ID, authUser(ctx), time.Now().UTC(), first, skip, cols, asc)
	if err != nil {
		return nil, err
	}
	return toDiscountConnection(conn), nil
}

// Discounts is the resolver for the discounts field.
func (r *productVariantResolver) Discounts(ctx context.Context, obj *ProductVariant, first *int, orderBy *DiscountOrderInput, skip *int) (*DiscountConnection, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	cols, asc := discountOrder(orderBy)
	conn, err := r.Store.DiscountsByProductVariant(ctx, obj.ID, first, skip, cols, asc)
	if err != nil {
		return nil, err
	}
	return toDiscountConnection(conn), nil
}

// ---- Query ---------------------------------------------------------------

// Coupon is the resolver for the coupon field.
func (r *queryResolver) Coupon(ctx context.Context, id uuid.UUID) (*Coupon, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	c, err := r.Store.GetCoupon(ctx, id)
	if err != nil {
		return nil, err
	}
	return toCoupon(c), nil
}

// Discount is the resolver for the discount field.
func (r *queryResolver) Discount(ctx context.Context, id uuid.UUID) (*Discount, error) {
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	d, err := r.Store.GetDiscount(ctx, id)
	if err != nil {
		return nil, err
	}
	return toDiscount(d), nil
}

// FindApplicableDiscounts is the resolver for the findApplicableDiscounts field.
func (r *queryResolver) FindApplicableDiscounts(ctx context.Context, input FindApplicableDiscountsInput) ([]DiscountsForProductVariant, error) {
	// No auth check (internal @inaccessible query used by the order service).
	return r.findApplicableDiscounts(ctx, input)
}

// ---- User (foreign entity) -----------------------------------------------

// Coupons is the resolver for the coupons field.
func (r *userResolver) Coupons(ctx context.Context, obj *User, filter *CouponFilterInput, first *int, orderBy *CouponOrderInput, skip *int) (*CouponConnection, error) {
	// self OR employee (a user may see their own coupons).
	if err := requireSelfOrEmployee(ctx, obj.ID); err != nil {
		return nil, err
	}
	if err := applyCouponFilterAuth(ctx, filter); err != nil {
		return nil, err
	}
	cols, asc := couponOrder(orderBy)
	conn, err := r.Store.CouponsByUser(ctx, obj.ID, couponFilter(filter), authUser(ctx), first, skip, cols, asc)
	if err != nil {
		return nil, err
	}
	return toCouponConnection(conn), nil
}

// DiscountUsages is the resolver for the discountUsages field.
func (r *userResolver) DiscountUsages(ctx context.Context, obj *User, first *int, orderBy *DiscountUsageOrderInput, skip *int) (*DiscountUsageConnection, error) {
	// Always employee (even for your own usages).
	if err := requireEmployee(ctx); err != nil {
		return nil, err
	}
	cols, asc := discountUsageOrder(orderBy)
	conn, err := r.Store.DiscountUsagesByUser(ctx, obj.ID, first, skip, cols, asc)
	if err != nil {
		return nil, err
	}
	return toDiscountUsageConnection(conn), nil
}

// ---- resolver plumbing ---------------------------------------------------

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

// Coupon returns CouponResolver implementation.
func (r *Resolver) Coupon() CouponResolver { return &couponResolver{r} }

// Discount returns DiscountResolver implementation.
func (r *Resolver) Discount() DiscountResolver { return &discountResolver{r} }

// DiscountUsage returns DiscountUsageResolver implementation.
func (r *Resolver) DiscountUsage() DiscountUsageResolver { return &discountUsageResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

// ProductVariant returns ProductVariantResolver implementation.
func (r *Resolver) ProductVariant() ProductVariantResolver { return &productVariantResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type (
	categoryResolver       struct{ *Resolver }
	couponResolver         struct{ *Resolver }
	discountResolver       struct{ *Resolver }
	discountUsageResolver  struct{ *Resolver }
	mutationResolver       struct{ *Resolver }
	productResolver        struct{ *Resolver }
	productVariantResolver struct{ *Resolver }
	queryResolver          struct{ *Resolver }
	userResolver           struct{ *Resolver }
)
