package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"
)

// FindPaymentByID is the resolver for the findPaymentByID field. Federation
// reference resolution is unguarded (the gateway is trusted). Returns the full
// Payment or a GraphQL error if it does not exist.
func (r *entityResolver) FindPaymentByID(ctx context.Context, id uuid.UUID) (*Payment, error) {
	doc, err := r.Store.GetPayment(ctx, id.String())
	if err != nil {
		return nil, err
	}
	return toPayment(doc), nil
}

// FindPaymentInformationByID is the resolver for the findPaymentInformationByID
// field. Unguarded; returns the PaymentInformation or a GraphQL error when
// missing.
func (r *entityResolver) FindPaymentInformationByID(ctx context.Context, id uuid.UUID) (*PaymentInformation, error) {
	doc, err := r.Store.GetPaymentInformation(ctx, id.String())
	if err != nil {
		return nil, err
	}
	return toPaymentInformation(doc), nil
}

// FindUserByID is the resolver for the findUserByID field. User is a foreign
// entity: we own only the paymentInformations extension, so we return a bare
// stub carrying the key id (no DB lookup), exactly as the original
// __resolveReference did not fetch user data.
func (r *entityResolver) FindUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	return &User{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
