// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// All required informations to save an credit card
type CreateCreditCardInformationInput struct {
	// The card holders name
	CardHolder string `json:"cardHolder"`
	// The credit cards number
	CardNumber string `json:"cardNumber"`
	// The credit cards expiration date
	ExpirationDate string `json:"expirationDate"`
}

type Mutation struct {
}

// A payment of an invoice or return
type Payment struct {
	// The uuid identifier of the payment
	ID uuid.UUID `json:"id"`
	// Payment Amount in the smallest currency unit (e.g. cents)
	TotalAmount float64 `json:"totalAmount"`
	// Status of the payment
	Status PaymentStatus `json:"status"`
	// Used Payment Information
	PaymentInformation *PaymentInformation `json:"paymentInformation"`
	// Date of the payment
	PayedAt *time.Time `json:"payedAt,omitempty"`
	// Number of retries for the payment process
	NumberOfRetries      float64 `json:"numberOfRetries"`
	PaymentInformationID string  `json:"-"`
}

func (Payment) IsEntity() {}

// A connection of payments
type PaymentConnection struct {
	// The resulting items
	Nodes []Payment `json:"nodes,omitempty"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
}

// Filtering options for payments
type PaymentFilter struct {
	// Current payment status
	Status *PaymentStatus `json:"status,omitempty"`
	// Payment Information ID
	PaymentInformationID *string `json:"paymentInformationId,omitempty"`
	// Payment method
	PaymentMethod *PaymentMethod `json:"paymentMethod,omitempty"`
	// Timebox start for payment creation
	From *time.Time `json:"from,omitempty"`
	// Timebox end for payment creation
	To *time.Time `json:"to,omitempty"`
}

// A stored payment information of an user
type PaymentInformation struct {
	// The uuid identifier of the payment information
	ID uuid.UUID `json:"id"`
	// The corresponding payment method
	PaymentMethod PaymentMethod `json:"paymentMethod"`
	// The details for the User to identify the payment method
	PublicMethodDetails map[string]any `json:"publicMethodDetails,omitempty"`
	// The user who owns the payment information
	User *User `json:"user"`
	// A connection for an users payments made with a payment information.
	Payments *PaymentConnection `json:"payments,omitempty"`
	UserID   uuid.UUID          `json:"-"`
}

func (PaymentInformation) IsEntity() {}

// A connection of payment informations
type PaymentInformationConnection struct {
	// The resulting items
	Nodes []PaymentInformation `json:"nodes,omitempty"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
}

// Filtering options for payment informations
type PaymentInformationFilter struct {
	// Connected user id
	User *uuid.UUID `json:"user,omitempty"`
	// Linked payment method
	PaymentMethod *PaymentMethod `json:"paymentMethod,omitempty"`
}

// Ordering options for payment informations
type PaymentInformationOrder struct {
	// The field to order by
	Field *PaymentInformationOrderField `json:"field,omitempty"`
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
}

// Ordering options for payments
type PaymentOrder struct {
	// The field to order by
	Field *PaymentOrderField `json:"field,omitempty"`
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
}

type Query struct {
}

// Foreign type User
type User struct {
	// The uuid identifier of the user
	ID uuid.UUID `json:"id"`
	// A connection for an users payment informations.
	PaymentInformations *PaymentInformationConnection `json:"paymentInformations,omitempty"`
}

func (User) IsEntity() {}

// The direction to order a list of items by
type OrderDirection string

const (
	// Ascending Order
	OrderDirectionAsc OrderDirection = "ASC"
	// Decending Order
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The field to order payment informations by
type PaymentInformationOrderField string

const (
	// Order payment informations by their id
	PaymentInformationOrderFieldID PaymentInformationOrderField = "ID"
)

var AllPaymentInformationOrderField = []PaymentInformationOrderField{
	PaymentInformationOrderFieldID,
}

func (e PaymentInformationOrderField) IsValid() bool {
	switch e {
	case PaymentInformationOrderFieldID:
		return true
	}
	return false
}

func (e PaymentInformationOrderField) String() string {
	return string(e)
}

func (e *PaymentInformationOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentInformationOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentInformationOrderField", str)
	}
	return nil
}

func (e PaymentInformationOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentInformationOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentInformationOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The supported payment methods
type PaymentMethod string

const (
	// The user pays after ordering the product
	PaymentMethodInvoice PaymentMethod = "INVOICE"
	// The user pays before the product is shipped
	PaymentMethodPrepayment PaymentMethod = "PREPAYMENT"
	// The amount is charged to the users credit card
	PaymentMethodCreditCard PaymentMethod = "CREDIT_CARD"
)

var AllPaymentMethod = []PaymentMethod{
	PaymentMethodInvoice,
	PaymentMethodPrepayment,
	PaymentMethodCreditCard,
}

func (e PaymentMethod) IsValid() bool {
	switch e {
	case PaymentMethodInvoice, PaymentMethodPrepayment, PaymentMethodCreditCard:
		return true
	}
	return false
}

func (e PaymentMethod) String() string {
	return string(e)
}

func (e *PaymentMethod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentMethod", str)
	}
	return nil
}

func (e PaymentMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentMethod) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentMethod) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The field to order Payments by
type PaymentOrderField string

const (
	// Order Payments by their ID
	PaymentOrderFieldID PaymentOrderField = "ID"
)

var AllPaymentOrderField = []PaymentOrderField{
	PaymentOrderFieldID,
}

func (e PaymentOrderField) IsValid() bool {
	switch e {
	case PaymentOrderFieldID:
		return true
	}
	return false
}

func (e PaymentOrderField) String() string {
	return string(e)
}

func (e *PaymentOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentOrderField", str)
	}
	return nil
}

func (e PaymentOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The status of an payment of an invoice or return
type PaymentStatus string

const (
	// The payment was created but not yet processed
	PaymentStatusOpen PaymentStatus = "OPEN"
	// The payment is currently being processed
	PaymentStatusPending PaymentStatus = "PENDING"
	// The payment was successfully processed and the amount was transfered
	PaymentStatusSucceeded PaymentStatus = "SUCCEEDED"
	// The payment processing failed indefinetely
	PaymentStatusFailed PaymentStatus = "FAILED"
	// The payment was sold to external inkasso service
	PaymentStatusInkasso PaymentStatus = "INKASSO"
)

var AllPaymentStatus = []PaymentStatus{
	PaymentStatusOpen,
	PaymentStatusPending,
	PaymentStatusSucceeded,
	PaymentStatusFailed,
	PaymentStatusInkasso,
}

func (e PaymentStatus) IsValid() bool {
	switch e {
	case PaymentStatusOpen, PaymentStatusPending, PaymentStatusSucceeded, PaymentStatusFailed, PaymentStatusInkasso:
		return true
	}
	return false
}

func (e PaymentStatus) String() string {
	return string(e)
}

func (e *PaymentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentStatus", str)
	}
	return nil
}

func (e PaymentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
