package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"misarch/payment/store"
	"misarch/pkg/auth"

	"github.com/google/uuid"
)

// CreateCreditCardPaymentInformation is the resolver for the createCreditCardPaymentInformation field.
func (r *mutationResolver) CreateCreditCardPaymentInformation(ctx context.Context, input CreateCreditCardInformationInput) (*PaymentInformation, error) {
	// @Roles(BUYER): only buyers may register a credit card for themselves.
	user, err := auth.RequireRole(ctx, auth.RoleBuyer)
	if err != nil {
		return nil, err
	}

	// class-validator: @IsCreditCard() then @IsExpirationDate(); cardHolder
	// has no validation.
	if !isCreditCardValid(input.CardNumber) {
		return nil, fmt.Errorf("%s", errInvalidCardNumber)
	}
	if !isExpirationDateValid(input.ExpirationDate) {
		return nil, fmt.Errorf("%s", errInvalidExpiration)
	}

	// publicMethodDetails: masked card number; secretMethodDetails: raw input
	// (never exposed via GraphQL).
	doc := store.PaymentInformationDoc{
		ID:            uuid.NewString(),
		PaymentMethod: string(PaymentMethodCreditCard),
		PublicMethodDetails: map[string]any{
			"cardHolder":     input.CardHolder,
			"cardNumber":     maskCardNumber(input.CardNumber),
			"expirationDate": input.ExpirationDate,
		},
		SecretMethodDetails: map[string]any{
			"cardHolder":     input.CardHolder,
			"cardNumber":     input.CardNumber,
			"expirationDate": input.ExpirationDate,
		},
		User: store.UserRef{ID: user.ID.String()},
	}
	created, err := r.Store.CreatePaymentInformation(ctx, doc)
	if err != nil {
		return nil, err
	}
	return toPaymentInformation(created), nil
}

// DeletePaymentInformation is the resolver for the deletePaymentInformation field.
func (r *mutationResolver) DeletePaymentInformation(ctx context.Context, id uuid.UUID) (*PaymentInformation, error) {
	// @Roles(SITE_ADMIN, EMPLOYEE, BUYER).
	user, err := auth.RequireRole(ctx, auth.RoleAdmin, auth.RoleEmployee, auth.RoleBuyer)
	if err != nil {
		return nil, err
	}

	// Load first, to reproduce the exact not-found error path.
	if _, err := r.Store.GetPaymentInformation(ctx, id.String()); err != nil {
		return nil, err
	}

	// Ownership check. [BUG #3 — reproduced] the original compares the whole
	// `user` subdocument via .toString() → "[object Object]", which never
	// equals a UUID string, so a caller lacking EMPLOYEE/SITE_ADMIN (i.e. a
	// plain buyer) is ALWAYS denied — even for their own payment information.
	if !user.IsEmployeeOrAdmin() {
		return nil, fmt.Errorf(`User not authorized to delete Payment Information with id "%s"`, id.String())
	}

	deleted, err := r.Store.DeletePaymentInformation(ctx, id.String())
	if err != nil {
		return nil, err
	}
	return toPaymentInformation(deleted), nil
}

// DeletePayment is the resolver for the deletePayment field.
func (r *mutationResolver) DeletePayment(ctx context.Context, id uuid.UUID) (*Payment, error) {
	// @Roles(SITE_ADMIN) only.
	if _, err := auth.RequireRole(ctx, auth.RoleAdmin); err != nil {
		return nil, err
	}
	deleted, err := r.Store.DeletePayment(ctx, id.String())
	if err != nil {
		return nil, err
	}
	return toPayment(deleted), nil
}

// PaymentInformation is the resolver for the paymentInformation field. It joins
// the payment's paymentInformation string FK (the original `populate`), within
// an already-authorized parent selection.
func (r *paymentResolver) PaymentInformation(ctx context.Context, obj *Payment) (*PaymentInformation, error) {
	doc, err := r.Store.GetPaymentInformation(ctx, obj.PaymentInformationID)
	if err != nil {
		return nil, err
	}
	return toPaymentInformation(doc), nil
}

// User is the resolver for the user field. It re-projects the stored user id as
// a federation User stub for the gateway to resolve elsewhere; it does NOT fetch
// anything.
func (r *paymentInformationResolver) User(ctx context.Context, obj *PaymentInformation) (*User, error) {
	return &User{ID: obj.UserID}, nil
}

// Payments is the resolver for the payments field.
func (r *paymentInformationResolver) Payments(ctx context.Context, obj *PaymentInformation, skip *int, first *int, orderBy *PaymentOrder, filter *PaymentFilter) (*PaymentConnection, error) {
	// @Roles(BUYER, SITE_ADMIN, EMPLOYEE).
	user, err := auth.RequireRole(ctx, auth.RoleBuyer, auth.RoleAdmin, auth.RoleEmployee)
	if err != nil {
		return nil, err
	}
	// Ownership: non admin/employee callers may only see their own payments.
	// currentUser.id vs paymentInformation.user.id (both UUID strings — this
	// comparison works correctly, unlike the delete bug).
	if !user.IsEmployeeOrAdmin() && user.ID != obj.UserID {
		return nil, fmt.Errorf("User not authorized to access foreign Payments}")
	}
	if err := validatePagination(skip, first); err != nil {
		return nil, err
	}

	// Merge { ...args.filter, paymentInformationId: paymentInformation.id }.
	f := paymentFilterArgs(filter)
	if f == nil {
		f = &store.PaymentFilterArgs{}
	}
	piID := obj.ID.String()
	f.PaymentInformationID = &piID

	sortField, dir := paymentSortField(orderBy)
	conn, err := r.Store.ListPayments(ctx, f, first, skip, sortField, dir)
	if err != nil {
		return nil, err
	}
	return toPaymentConnection(conn), nil
}

// PaymentInformations is the resolver for the paymentInformations field.
func (r *queryResolver) PaymentInformations(ctx context.Context, skip *int, first *int, orderBy *PaymentInformationOrder, filter *PaymentInformationFilter) (*PaymentInformationConnection, error) {
	// @Roles(SITE_ADMIN, EMPLOYEE): buyers cannot call the top-level query.
	if _, err := auth.RequireRole(ctx, auth.RoleAdmin, auth.RoleEmployee); err != nil {
		return nil, err
	}
	if err := validatePagination(skip, first); err != nil {
		return nil, err
	}

	// Top-level query filter is passed straight to Mongo. [BUG #4 — reproduced]
	// filter.user is a scalar UUID → { user: "<uuid>" }, which never matches
	// the stored subdocument { id: "<uuid>" }, so filtering by user returns 0
	// rows. The nested-object form that works is only used by
	// User.paymentInformations.
	f := &store.PaymentInformationFilterArgs{}
	if filter != nil {
		if filter.User != nil {
			s := filter.User.String()
			f.UserScalar = &s
		}
		if filter.PaymentMethod != nil {
			m := string(*filter.PaymentMethod)
			f.PaymentMethod = &m
		}
	}

	sortField, dir := paymentInformationSortField(orderBy)
	conn, err := r.Store.ListPaymentInformations(ctx, f, first, skip, sortField, dir)
	if err != nil {
		return nil, err
	}
	return toPaymentInformationConnection(conn), nil
}

// Payments is the resolver for the payments field.
func (r *queryResolver) Payments(ctx context.Context, skip *int, first *int, orderBy *PaymentOrder, filter *PaymentFilter) (*PaymentConnection, error) {
	// @Roles(SITE_ADMIN, EMPLOYEE).
	if _, err := auth.RequireRole(ctx, auth.RoleAdmin, auth.RoleEmployee); err != nil {
		return nil, err
	}
	if err := validatePagination(skip, first); err != nil {
		return nil, err
	}

	sortField, dir := paymentSortField(orderBy)
	conn, err := r.Store.ListPayments(ctx, paymentFilterArgs(filter), first, skip, sortField, dir)
	if err != nil {
		return nil, err
	}
	return toPaymentConnection(conn), nil
}

// PaymentInformations is the resolver for the paymentInformations field (on the
// foreign User entity).
func (r *userResolver) PaymentInformations(ctx context.Context, obj *User, skip *int, first *int, orderBy *PaymentInformationOrder, filter *PaymentInformationFilter) (*PaymentInformationConnection, error) {
	// @Roles(BUYER, SITE_ADMIN, EMPLOYEE).
	user, err := auth.RequireRole(ctx, auth.RoleBuyer, auth.RoleAdmin, auth.RoleEmployee)
	if err != nil {
		return nil, err
	}
	// Ownership: non admin/employee callers may only see their own informations.
	if !user.IsEmployeeOrAdmin() && user.ID != obj.ID {
		return nil, fmt.Errorf("User not authorized to access foreign Payment Informations}")
	}
	if err := validatePagination(skip, first); err != nil {
		return nil, err
	}

	// filter = { ...args.filter, user: { id: user.id } } — the nested-object
	// form that correctly matches the stored { id } subdocument.
	f := &store.PaymentInformationFilterArgs{}
	if filter != nil && filter.PaymentMethod != nil {
		m := string(*filter.PaymentMethod)
		f.PaymentMethod = &m
	}
	subID := obj.ID.String()
	f.UserSubID = &subID

	sortField, dir := paymentInformationSortField(orderBy)
	conn, err := r.Store.ListPaymentInformations(ctx, f, first, skip, sortField, dir)
	if err != nil {
		return nil, err
	}
	return toPaymentInformationConnection(conn), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Payment returns PaymentResolver implementation.
func (r *Resolver) Payment() PaymentResolver { return &paymentResolver{r} }

// PaymentInformation returns PaymentInformationResolver implementation.
func (r *Resolver) PaymentInformation() PaymentInformationResolver {
	return &paymentInformationResolver{r}
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type (
	mutationResolver           struct{ *Resolver }
	paymentResolver            struct{ *Resolver }
	paymentInformationResolver struct{ *Resolver }
	queryResolver              struct{ *Resolver }
	userResolver               struct{ *Resolver }
)
