package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"
)

// Federation entity resolvers perform NO auth or visibility checks (the
// original FederatedTypePromiseResolvers resolved via the data loaders
// directly). A hidden Product resolves fine here; only its guarded fields (e.g.
// internalName) still enforce auth. gqlgen parses the required "id" key into a
// uuid.UUID before invoking these, so a missing key never reaches the resolver.

// FindCategoricalCategoryCharacteristicByID is the resolver for the findCategoricalCategoryCharacteristicByID field.
func (r *entityResolver) FindCategoricalCategoryCharacteristicByID(ctx context.Context, id uuid.UUID) (*CategoricalCategoryCharacteristic, error) {
	// The original's typed loader cast the row to CategoricalCategoryCharacteristic;
	// a numerical id would raise a ClassCastException — GetCategoricalCharacteristic
	// enforces the discriminator and errors otherwise.
	c, err := r.Store.GetCategoricalCharacteristic(ctx, id)
	if err != nil {
		return nil, err
	}
	return toCharacteristic(c).(*CategoricalCategoryCharacteristic), nil
}

// FindCategoryByID is the resolver for the findCategoryByID field.
func (r *entityResolver) FindCategoryByID(ctx context.Context, id uuid.UUID) (*Category, error) {
	category, err := r.Store.GetCategory(ctx, id)
	if err != nil {
		return nil, err
	}
	return toCategory(category), nil
}

// FindNumericalCategoryCharacteristicByID is the resolver for the findNumericalCategoryCharacteristicByID field.
func (r *entityResolver) FindNumericalCategoryCharacteristicByID(ctx context.Context, id uuid.UUID) (*NumericalCategoryCharacteristic, error) {
	c, err := r.Store.GetNumericalCharacteristic(ctx, id)
	if err != nil {
		return nil, err
	}
	return toCharacteristic(c).(*NumericalCategoryCharacteristic), nil
}

// FindProductByID is the resolver for the findProductByID field.
func (r *entityResolver) FindProductByID(ctx context.Context, id uuid.UUID) (*Product, error) {
	product, err := r.Store.GetProduct(ctx, id)
	if err != nil {
		return nil, err
	}
	return toProduct(product), nil
}

// FindProductVariantByID is the resolver for the findProductVariantByID field.
func (r *entityResolver) FindProductVariantByID(ctx context.Context, id uuid.UUID) (*ProductVariant, error) {
	variant, err := r.Store.GetProductVariant(ctx, id)
	if err != nil {
		return nil, err
	}
	return toProductVariant(variant), nil
}

// FindProductVariantVersionByID is the resolver for the findProductVariantVersionByID field.
func (r *entityResolver) FindProductVariantVersionByID(ctx context.Context, id uuid.UUID) (*ProductVariantVersion, error) {
	version, err := r.Store.GetProductVariantVersion(ctx, id)
	if err != nil {
		return nil, err
	}
	return toProductVariantVersion(version), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
