// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// A characteristic of a Category.
type CategoryCharacteristic interface {
	IsNode()
	IsCategoryCharacteristic()
}

// A value for a CategoryCharacteristic.
type CategoryCharacteristicValue interface {
	IsCategoryCharacteristicValue()
}

// An object with an ID.
type Node interface {
	IsNode()
}

// A categorical characteristic of a category.
type CategoricalCategoryCharacteristic struct {
	// The Category this item belongs to.
	Category *Category `json:"category"`
	// The description of the CategoryCharacteristic.
	Description string `json:"description"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The name of the CategoryCharacteristic.
	Name string `json:"name"`
	// Get all associated values
	Values     *CategoricalCategoryCharacteristicValueConnection `json:"values"`
	CategoryID uuid.UUID                                         `json:"-"`
}

func (CategoricalCategoryCharacteristic) IsCategoryCharacteristic() {}

func (CategoricalCategoryCharacteristic) IsNode() {}

func (CategoricalCategoryCharacteristic) IsEntity() {}

// Input to create a CategoricalCategoryCharacteristic for a Category
type CategoricalCategoryCharacteristicInput struct {
	// The description of the CategoricalCategoryCharacteristic
	Description string `json:"description"`
	// The name of the CategoricalCategoryCharacteristic
	Name string `json:"name"`
}

// A possible value for a categorical characteristic.
type CategoricalCategoryCharacteristicValue struct {
	// The associated CategoryCharacteristic this is a value of.
	Characteristic CategoryCharacteristic `json:"characteristic"`
	// The value of the characteristic.
	Value            string    `json:"value"`
	CharacteristicID uuid.UUID `json:"-"`
}

func (CategoricalCategoryCharacteristicValue) IsCategoryCharacteristicValue() {}

// A connection to a list of `CategoricalCategoryCharacteristicValue` values.
type CategoricalCategoryCharacteristicValueConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []CategoricalCategoryCharacteristicValue `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// Input for creating a CategoricalCategoryCharacteristicValue.
type CategoricalCategoryCharacteristicValueInput struct {
	// The id of the CategoryCharacteristic.
	CharacteristicID uuid.UUID `json:"characteristicId"`
	// The value of the CategoricalCategoryCharacteristicValue.
	Value string `json:"value"`
}

// CategoricalCategoryCharacteristicValue order
type CategoricalCategoryCharacteristicValueOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *CategoricalCategoryCharacteristicValueOrderField `json:"field,omitempty"`
}

// A category
type Category struct {
	// Get characteristics for the category
	Characteristics *CategoryCharacteristicConnection `json:"characteristics"`
	// The description of the category.
	Description string `json:"description"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The name of the category.
	Name string `json:"name"`
	// Get all associated products
	Products *ProductConnection `json:"products"`
}

func (Category) IsNode() {}

func (Category) IsEntity() {}

// A connection to a list of `CategoryCharacteristic` values.
type CategoryCharacteristicConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []CategoryCharacteristic `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// CategoryCharacteristic order
type CategoryCharacteristicOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *CategoryCharacteristicOrderField `json:"field,omitempty"`
}

// A connection to a list of `CategoryCharacteristicValue` values.
type CategoryCharacteristicValueConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []CategoryCharacteristicValue `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// CategoryCharacteristicValue order
type CategoryCharacteristicValueOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *CategoryCharacteristicValueOrderField `json:"field,omitempty"`
}

// A connection to a list of `Category` values.
type CategoryConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []Category `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// Category order
type CategoryOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *CategoryOrderField `json:"field,omitempty"`
}

// Discount order
type CommonOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *CommonOrderField `json:"field,omitempty"`
}

// Input for the createCategoricalCategoryCharacteristic mutation
type CreateCategoricalCategoryCharacteristicInput struct {
	// The Category that the CategoricalCategoryCharacteristicI belongs to
	CategoryID uuid.UUID `json:"categoryId"`
	// The description of the CategoricalCategoryCharacteristic
	Description string `json:"description"`
	// The name of the CategoricalCategoryCharacteristic
	Name string `json:"name"`
}

// Input for the createCategory mutation
type CreateCategoryInput struct {
	// The CategoricalCategoryCharacteristics of the Category
	CategoricalCharacteristics []CategoricalCategoryCharacteristicInput `json:"categoricalCharacteristics"`
	// The description of the Category
	Description string `json:"description"`
	// The name of the Category
	Name string `json:"name"`
	// The NumericalCategoryCharacteristics of the Category
	NumericalCharacteristics []NumericalCategoryCharacteristicInput `json:"numericalCharacteristics"`
}

// Input for the createNumericalCategoryCharacteristic mutation
type CreateNumericalCategoryCharacteristicInput struct {
	// The Category that the NumericalCategoryCharacteristic belongs to
	CategoryID uuid.UUID `json:"categoryId"`
	// The description of the NumericalCategoryCharacteristic
	Description string `json:"description"`
	// The name of the NumericalCategoryCharacteristic
	Name string `json:"name"`
	// The unit of the NumericalCategoryCharacteristic
	Unit string `json:"unit"`
}

// Input for the createProduct mutation
type CreateProductInput struct {
	// The Categories this product is associated with.
	CategoryIds []uuid.UUID `json:"categoryIds"`
	// The default ProductVariant of the Product.
	DefaultVariant *ProductVariantInput `json:"defaultVariant"`
	// An internal name to identify the Product, not visible to customers.
	InternalName string `json:"internalName"`
	// If true, the Product is visible to customers.
	IsPubliclyVisible bool `json:"isPubliclyVisible"`
}

// Input for the createProductVariant mutation
type CreateProductVariantInput struct {
	// The initial ProductVariantVersion of the ProductVariant.
	InitialVersion *ProductVariantVersionInput `json:"initialVersion"`
	// If true, the ProductVariant is visible to customers.
	IsPubliclyVisible bool `json:"isPubliclyVisible"`
	// The id of the Product this ProductVariant belongs to.
	ProductID uuid.UUID `json:"productId"`
}

// Input for the createProductVariantVersion mutation
type CreateProductVariantVersionInput struct {
	// The amount of days for which an instance of the ProductVariant can be returned after purchase, if null can be returned indefinitely.
	CanBeReturnedForDays *int `json:"canBeReturnedForDays,omitempty"`
	// The CategoricalCategoryCharacteristicValues of the ProductVariant, must be compatible with the Categories of the associated Product.
	CategoricalCharacteristicValues []CategoricalCategoryCharacteristicValueInput `json:"categoricalCharacteristicValues"`
	// The description of the ProductVariant.
	Description string `json:"description"`
	// The associated Media files.
	MediaIds []uuid.UUID `json:"mediaIds"`
	// The name of the ProductVariant.
	Name string `json:"name"`
	// The NumericalCategoryCharacteristicValues of the ProductVariant, must be compatible with the Categories of the associated Product.
	NumericalCharacteristicValues []NumericalCategoryCharacteristicValueInput `json:"numericalCharacteristicValues"`
	// The id of the ProductVariant this ProductVariantVersion belongs to.
	ProductVariantID uuid.UUID `json:"productVariantId"`
	// The retail price of the ProductVariant.
	RetailPrice int `json:"retailPrice"`
	// The associated TaxRate
	TaxRateID uuid.UUID `json:"taxRateId"`
	// The weight of a single instance of the ProductVariant.
	Weight float64 `json:"weight"`
}

// A Media file.
type Media struct {
	// The ID of the node.
	ID uuid.UUID `json:"id"`
}

func (Media) IsNode() {}

func (Media) IsEntity() {}

// A connection to a list of `Media` values.
type MediaConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []Media `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

type Mutation struct {
}

// A numerical characteristic of a Category.
type NumericalCategoryCharacteristic struct {
	// The Category this item belongs to.
	Category *Category `json:"category"`
	// The description of the CategoryCharacteristic.
	Description string `json:"description"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The name of the CategoryCharacteristic.
	Name string `json:"name"`
	// The unit of the NumericalCategoryCharacteristic.
	Unit       string    `json:"unit"`
	CategoryID uuid.UUID `json:"-"`
}

func (NumericalCategoryCharacteristic) IsCategoryCharacteristic() {}

func (NumericalCategoryCharacteristic) IsNode() {}

func (NumericalCategoryCharacteristic) IsEntity() {}

// Input to create a characteristic whose values have arithmetic meaning, i.e. '8GB'
type NumericalCategoryCharacteristicInput struct {
	// The description of the NumericalCategoryCharacteristic
	Description string `json:"description"`
	// The name of the NumericalCategoryCharacteristic
	Name string `json:"name"`
	// The unit of the NumericalCategoryCharacteristic
	Unit string `json:"unit"`
}

// A numerical value of a NumericalCategoryCharacteristic.
type NumericalCategoryCharacteristicValue struct {
	// The associated CategoryCharacteristic this is a value of.
	Characteristic CategoryCharacteristic `json:"characteristic"`
	// The value of the NumericalCategoryCharacteristic.
	Value            float64   `json:"value"`
	CharacteristicID uuid.UUID `json:"-"`
}

func (NumericalCategoryCharacteristicValue) IsCategoryCharacteristicValue() {}

// Input for creating a NumericalCategoryCharacteristicValue.
type NumericalCategoryCharacteristicValueInput struct {
	// The id of the CategoryCharacteristic.
	CharacteristicID uuid.UUID `json:"characteristicId"`
	// The value of the NumericalCategoryCharacteristicValue.
	Value float64 `json:"value"`
}

// A product.
type Product struct {
	// Get all associated Categories
	Categories *CategoryConnection `json:"categories"`
	// The default variant of the product.
	DefaultVariant *ProductVariant `json:"defaultVariant"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// An internal name to identify the Product, not visible to customers.
	InternalName string `json:"internalName"`
	// If true, the Product is visible to customers.
	IsPubliclyVisible bool `json:"isPubliclyVisible"`
	// Get all associated ProductVariants
	Variants         *ProductVariantConnection `json:"variants"`
	DefaultVariantID uuid.UUID                 `json:"-"`
}

func (Product) IsNode() {}

func (Product) IsEntity() {}

// A connection to a list of `Product` values.
type ProductConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []Product `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// Product filter
type ProductFilterInput struct {
	IsPubliclyVisible *bool `json:"isPubliclyVisible,omitempty"`
}

// Product order
type ProductOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *ProductOrderField `json:"field,omitempty"`
}

// A variant of a Product.
type ProductVariant struct {
	// The current version of the ProductVariant.
	CurrentVersion *ProductVariantVersion `json:"currentVersion"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// If true, the ProductVariant is visible to customers.
	IsPubliclyVisible bool `json:"isPubliclyVisible"`
	// The Product belonging to this variant.
	Product *Product `json:"product"`
	// Get all associated versions
	Versions         *ProductVariantVersionConnection `json:"versions"`
	CurrentVersionID uuid.UUID                        `json:"-"`
	ProductID        uuid.UUID                        `json:"-"`
}

func (ProductVariant) IsNode() {}

func (ProductVariant) IsEntity() {}

// A connection to a list of `ProductVariant` values.
type ProductVariantConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []ProductVariant `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// Product variant filter
type ProductVariantFilterInput struct {
	IsPubliclyVisible *bool `json:"isPubliclyVisible,omitempty"`
}

// Input for creating a product variant
type ProductVariantInput struct {
	// The initial ProductVariantVersion of the ProductVariant.
	InitialVersion *ProductVariantVersionInput `json:"initialVersion"`
	// If true, the ProductVariant is visible to customers.
	IsPubliclyVisible bool `json:"isPubliclyVisible"`
}

// ProductVariant order
type ProductVariantOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *ProductVariantOrderField `json:"field,omitempty"`
}

// A version of a ProductVariant.
type ProductVariantVersion struct {
	// The amount of days for which an instance of the ProductVariantVersion can be returned after purchase, if null can be returned indefinitely.
	CanBeReturnedForDays *int `json:"canBeReturnedForDays,omitempty"`
	// Get all associated CategoryCharacteristicValues
	CharacteristicValues *CategoryCharacteristicValueConnection `json:"characteristicValues"`
	// The date when the ProductVariantVersion version was created.
	CreatedAt time.Time `json:"createdAt"`
	// The description of the ProductVariantVersion.
	Description string `json:"description"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// Get all associated Medias
	Medias *MediaConnection `json:"medias"`
	// The name of the ProductVariantVersion.
	Name string `json:"name"`
	// The ProductVariant this is a version of.
	ProductVariant *ProductVariant `json:"productVariant"`
	// The retail price of the ProductVariantVersion.
	RetailPrice int `json:"retailPrice"`
	// The associated TaxRate.
	TaxRate *TaxRate `json:"taxRate"`
	// The version of the ProductVariantVersion.
	Version int `json:"version"`
	// The weight of the ProductVariantVersion.
	Weight           float64   `json:"weight"`
	ProductVariantID uuid.UUID `json:"-"`
	TaxRateID        uuid.UUID `json:"-"`
}

func (ProductVariantVersion) IsNode() {}

func (ProductVariantVersion) IsEntity() {}

// A connection to a list of `ProductVariantVersion` values.
type ProductVariantVersionConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []ProductVariantVersion `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// Input for creating a ProductVariantVersion.
type ProductVariantVersionInput struct {
	// The amount of days for which an instance of the ProductVariant can be returned after purchase, if null can be returned indefinitely.
	CanBeReturnedForDays *int `json:"canBeReturnedForDays,omitempty"`
	// The CategoricalCategoryCharacteristicValues of the ProductVariant, must be compatible with the Categories of the associated Product.
	CategoricalCharacteristicValues []CategoricalCategoryCharacteristicValueInput `json:"categoricalCharacteristicValues"`
	// The description of the ProductVariant.
	Description string `json:"description"`
	// The associated Media files.
	MediaIds []uuid.UUID `json:"mediaIds"`
	// The name of the ProductVariant.
	Name string `json:"name"`
	// The NumericalCategoryCharacteristicValues of the ProductVariant, must be compatible with the Categories of the associated Product.
	NumericalCharacteristicValues []NumericalCategoryCharacteristicValueInput `json:"numericalCharacteristicValues"`
	// The retail price of the ProductVariant.
	RetailPrice int `json:"retailPrice"`
	// The associated TaxRate
	TaxRateID uuid.UUID `json:"taxRateId"`
	// The weight of a single instance of the ProductVariant.
	Weight float64 `json:"weight"`
}

// ProductVariantVersion order
type ProductVariantVersionOrderInput struct {
	// The direction to order by
	Direction *OrderDirection `json:"direction,omitempty"`
	// The field to order by
	Field *ProductVariantVersionOrderField `json:"field,omitempty"`
}

type Query struct {
}

// A TaxRate.
type TaxRate struct {
	// The ID of the node.
	ID uuid.UUID `json:"id"`
}

func (TaxRate) IsNode() {}

func (TaxRate) IsEntity() {}

// Input for the updateProduct mutation.
type UpdateProductInput struct {
	// If present, new value for defaultVariantId
	DefaultVariantID *uuid.UUID `json:"defaultVariantId,omitempty"`
	// UUID of the product to be updated
	ID uuid.UUID `json:"id"`
	// If present, new value for internalName
	InternalName *string `json:"internalName,omitempty"`
	// If present, new value for isPubliclyVisible
	IsPubliclyVisible *bool `json:"isPubliclyVisible,omitempty"`
}

// Input for the updateProductVariant mutation.
type UpdateProductVariantInput struct {
	// UUID of the product variant to be updated
	ID uuid.UUID `json:"id"`
	// If present, new value for isPubliclyVisible
	IsPubliclyVisible *bool `json:"isPubliclyVisible,omitempty"`
}

// CategoricalCategoryCharacteristicValue order fields
type CategoricalCategoryCharacteristicValueOrderField string

const (
	// Order CategoricalCategoryCharacteristicValue by their id
	CategoricalCategoryCharacteristicValueOrderFieldValue CategoricalCategoryCharacteristicValueOrderField = "VALUE"
)

var AllCategoricalCategoryCharacteristicValueOrderField = []CategoricalCategoryCharacteristicValueOrderField{
	CategoricalCategoryCharacteristicValueOrderFieldValue,
}

func (e CategoricalCategoryCharacteristicValueOrderField) IsValid() bool {
	switch e {
	case CategoricalCategoryCharacteristicValueOrderFieldValue:
		return true
	}
	return false
}

func (e CategoricalCategoryCharacteristicValueOrderField) String() string {
	return string(e)
}

func (e *CategoricalCategoryCharacteristicValueOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CategoricalCategoryCharacteristicValueOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CategoricalCategoryCharacteristicValueOrderField", str)
	}
	return nil
}

func (e CategoricalCategoryCharacteristicValueOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CategoricalCategoryCharacteristicValueOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CategoricalCategoryCharacteristicValueOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// CategoryCharacteristic order fields
type CategoryCharacteristicOrderField string

const (
	// Order categoryCharacteristics by their id
	CategoryCharacteristicOrderFieldID CategoryCharacteristicOrderField = "ID"
)

var AllCategoryCharacteristicOrderField = []CategoryCharacteristicOrderField{
	CategoryCharacteristicOrderFieldID,
}

func (e CategoryCharacteristicOrderField) IsValid() bool {
	switch e {
	case CategoryCharacteristicOrderFieldID:
		return true
	}
	return false
}

func (e CategoryCharacteristicOrderField) String() string {
	return string(e)
}

func (e *CategoryCharacteristicOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CategoryCharacteristicOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CategoryCharacteristicOrderField", str)
	}
	return nil
}

func (e CategoryCharacteristicOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CategoryCharacteristicOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CategoryCharacteristicOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// CategoryCharacteristicValue order fields
type CategoryCharacteristicValueOrderField string

const (
	// Order categoryCharacteristicValues by their id
	CategoryCharacteristicValueOrderFieldID CategoryCharacteristicValueOrderField = "ID"
)

var AllCategoryCharacteristicValueOrderField = []CategoryCharacteristicValueOrderField{
	CategoryCharacteristicValueOrderFieldID,
}

func (e CategoryCharacteristicValueOrderField) IsValid() bool {
	switch e {
	case CategoryCharacteristicValueOrderFieldID:
		return true
	}
	return false
}

func (e CategoryCharacteristicValueOrderField) String() string {
	return string(e)
}

func (e *CategoryCharacteristicValueOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CategoryCharacteristicValueOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CategoryCharacteristicValueOrderField", str)
	}
	return nil
}

func (e CategoryCharacteristicValueOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CategoryCharacteristicValueOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CategoryCharacteristicValueOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Category order fields
type CategoryOrderField string

const (
	// Order categories by their id
	CategoryOrderFieldID CategoryOrderField = "ID"
	// Order categories by their name
	CategoryOrderFieldName CategoryOrderField = "NAME"
)

var AllCategoryOrderField = []CategoryOrderField{
	CategoryOrderFieldID,
	CategoryOrderFieldName,
}

func (e CategoryOrderField) IsValid() bool {
	switch e {
	case CategoryOrderFieldID, CategoryOrderFieldName:
		return true
	}
	return false
}

func (e CategoryOrderField) String() string {
	return string(e)
}

func (e *CategoryOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CategoryOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CategoryOrderField", str)
	}
	return nil
}

func (e CategoryOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CategoryOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CategoryOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Common order fields
type CommonOrderField string

const (
	// Order entities by their id
	CommonOrderFieldID CommonOrderField = "ID"
)

var AllCommonOrderField = []CommonOrderField{
	CommonOrderFieldID,
}

func (e CommonOrderField) IsValid() bool {
	switch e {
	case CommonOrderFieldID:
		return true
	}
	return false
}

func (e CommonOrderField) String() string {
	return string(e)
}

func (e *CommonOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommonOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommonOrderField", str)
	}
	return nil
}

func (e CommonOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommonOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommonOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Order direction
type OrderDirection string

const (
	// Ascending order
	OrderDirectionAsc OrderDirection = "ASC"
	// Descending order
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Product order fields
type ProductOrderField string

const (
	// Order products by their id
	ProductOrderFieldID ProductOrderField = "ID"
	// Order products by their internal name
	ProductOrderFieldInternalName ProductOrderField = "INTERNAL_NAME"
)

var AllProductOrderField = []ProductOrderField{
	ProductOrderFieldID,
	ProductOrderFieldInternalName,
}

func (e ProductOrderField) IsValid() bool {
	switch e {
	case ProductOrderFieldID, ProductOrderFieldInternalName:
		return true
	}
	return false
}

func (e ProductOrderField) String() string {
	return string(e)
}

func (e *ProductOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductOrderField", str)
	}
	return nil
}

func (e ProductOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProductOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProductOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// ProductVariant order fields
type ProductVariantOrderField string

const (
	// Order productVariants by their id
	ProductVariantOrderFieldID ProductVariantOrderField = "ID"
)

var AllProductVariantOrderField = []ProductVariantOrderField{
	ProductVariantOrderFieldID,
}

func (e ProductVariantOrderField) IsValid() bool {
	switch e {
	case ProductVariantOrderFieldID:
		return true
	}
	return false
}

func (e ProductVariantOrderField) String() string {
	return string(e)
}

func (e *ProductVariantOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductVariantOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductVariantOrderField", str)
	}
	return nil
}

func (e ProductVariantOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProductVariantOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProductVariantOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// ProductVariantVersion order fields
type ProductVariantVersionOrderField string

const (
	// Order productVariantVersions by their creation date
	ProductVariantVersionOrderFieldCreatedAt ProductVariantVersionOrderField = "CREATED_AT"
	// Order productVariantVersions by their id
	ProductVariantVersionOrderFieldID ProductVariantVersionOrderField = "ID"
	// Order productVariantVersions by their version
	ProductVariantVersionOrderFieldVersion ProductVariantVersionOrderField = "VERSION"
)

var AllProductVariantVersionOrderField = []ProductVariantVersionOrderField{
	ProductVariantVersionOrderFieldCreatedAt,
	ProductVariantVersionOrderFieldID,
	ProductVariantVersionOrderFieldVersion,
}

func (e ProductVariantVersionOrderField) IsValid() bool {
	switch e {
	case ProductVariantVersionOrderFieldCreatedAt, ProductVariantVersionOrderFieldID, ProductVariantVersionOrderFieldVersion:
		return true
	}
	return false
}

func (e ProductVariantVersionOrderField) String() string {
	return string(e)
}

func (e *ProductVariantVersionOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductVariantVersionOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductVariantVersionOrderField", str)
	}
	return nil
}

func (e ProductVariantVersionOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProductVariantVersionOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProductVariantVersionOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
