package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"time"

	"github.com/google/uuid"

	"misarch/catalog/events"
	"misarch/catalog/store"
)

// Category is the resolver for the category field.
func (r *categoricalCategoryCharacteristicResolver) Category(ctx context.Context, obj *CategoricalCategoryCharacteristic) (*Category, error) {
	// No auth (the original resolved category via the shared data loader).
	category, err := r.Store.GetCategory(ctx, obj.CategoryID)
	if err != nil {
		return nil, err
	}
	return toCategory(category), nil
}

// Values is the resolver for the values field.
func (r *categoricalCategoryCharacteristicResolver) Values(ctx context.Context, obj *CategoricalCategoryCharacteristic, first *int, orderBy *CategoricalCategoryCharacteristicValueOrderInput, skip *int) (*CategoricalCategoryCharacteristicValueConnection, error) {
	// Distinct-string-values projection; no auth, no visibility filter.
	col, asc := categoricalValueOrder(orderBy)
	conn, err := r.Store.ListCategoricalValues(ctx, store.NewListArgs(first, skip, col, asc), obj.ID)
	if err != nil {
		return nil, err
	}
	return toCategoricalValueConnection(conn), nil
}

// Characteristic is the resolver for the characteristic field.
func (r *categoricalCategoryCharacteristicValueResolver) Characteristic(ctx context.Context, obj *CategoricalCategoryCharacteristicValue) (CategoryCharacteristic, error) {
	// No auth (data-loader lookup by characteristic id).
	c, err := r.Store.GetCharacteristic(ctx, obj.CharacteristicID)
	if err != nil {
		return nil, err
	}
	return toCharacteristic(c), nil
}

// Characteristics is the resolver for the characteristics field.
func (r *categoryResolver) Characteristics(ctx context.Context, obj *Category, first *int, orderBy *CategoryCharacteristicOrderInput, skip *int) (*CategoryCharacteristicConnection, error) {
	// No auth.
	col, asc := characteristicOrder(orderBy)
	conn, err := r.Store.ListCharacteristics(ctx, store.NewListArgs(first, skip, col, asc), obj.ID)
	if err != nil {
		return nil, err
	}
	return toCharacteristicConnection(conn), nil
}

// Products is the resolver for the products field.
func (r *categoryResolver) Products(ctx context.Context, obj *Category, filter *ProductFilterInput, first *int, orderBy *ProductOrderInput, skip *int) (*ProductConnection, error) {
	// No auth check on Category.products; the visibility filter still applies to
	// non-employees. Join producttocategory on productid; predicate categoryid.
	col, asc := productOrder(orderBy)
	join := " INNER JOIN producttocategoryentity ON producttocategoryentity.productid = productentity.id"
	conn, err := r.Store.ListProducts(
		ctx, store.NewListArgs(first, skip, col, asc),
		join, "producttocategoryentity.categoryid = $1", []any{obj.ID},
		filterVisible(filter), isEmployee(ctx),
	)
	if err != nil {
		return nil, err
	}
	return toProductConnection(conn), nil
}

// CreateCategoricalCategoryCharacteristic is the resolver for the createCategoricalCategoryCharacteristic field.
func (r *mutationResolver) CreateCategoricalCategoryCharacteristic(ctx context.Context, input CreateCategoricalCategoryCharacteristicInput) (*CategoricalCategoryCharacteristic, error) {
	if err := checkIsEmployee(ctx); err != nil {
		return nil, err
	}
	// No event published for this mutation.
	c, err := r.Store.CreateCategoricalCharacteristic(ctx, input.CategoryID, input.Name, input.Description)
	if err != nil {
		return nil, err
	}
	return toCharacteristic(c).(*CategoricalCategoryCharacteristic), nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input CreateCategoryInput) (*Category, error) {
	if err := checkIsEmployee(ctx); err != nil {
		return nil, err
	}
	category, err := r.Store.CreateCategory(
		ctx, input.Name, input.Description,
		toNamedInputs(input.CategoricalCharacteristics), toNumericalNamedInputs(input.NumericalCharacteristics),
	)
	if err != nil {
		return nil, err
	}
	if err := events.PublishCategoryCreated(ctx, r.Dapr, events.Category{
		ID: category.ID, Name: category.Name, Description: category.Description,
	}); err != nil {
		return nil, err
	}
	return toCategory(category), nil
}

// CreateNumericalCategoryCharacteristic is the resolver for the createNumericalCategoryCharacteristic field.
func (r *mutationResolver) CreateNumericalCategoryCharacteristic(ctx context.Context, input CreateNumericalCategoryCharacteristicInput) (*NumericalCategoryCharacteristic, error) {
	if err := checkIsEmployee(ctx); err != nil {
		return nil, err
	}
	// No event published for this mutation.
	c, err := r.Store.CreateNumericalCharacteristic(ctx, input.CategoryID, input.Name, input.Description, input.Unit)
	if err != nil {
		return nil, err
	}
	return toCharacteristic(c).(*NumericalCategoryCharacteristic), nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input CreateProductInput) (*Product, error) {
	if err := checkIsEmployee(ctx); err != nil {
		return nil, err
	}
	product, variant, created, categoryIDs, err := r.Store.CreateProduct(
		ctx, input.InternalName, input.IsPubliclyVisible, input.CategoryIds,
		toVariantInput(input.DefaultVariant), time.Now().UTC(),
	)
	if err != nil {
		return nil, err
	}

	// Publish in order: product/created, product-variant/created, product-variant-version/created.
	if err := events.PublishProductCreated(ctx, r.Dapr, events.Product{
		ID:                product.ID,
		InternalName:      product.InternalName,
		IsPubliclyVisible: product.IsPubliclyVisible,
		DefaultVariantID:  product.DefaultVariantID,
		CategoryIDs:       categoryIDs,
	}); err != nil {
		return nil, err
	}
	if err := events.PublishProductVariantCreated(ctx, r.Dapr, variantCreatedEvent(variant)); err != nil {
		return nil, err
	}
	if err := events.PublishProductVariantVersionCreated(ctx, r.Dapr, versionCreatedEvent(created)); err != nil {
		return nil, err
	}
	return toProduct(product), nil
}

// CreateProductVariant is the resolver for the createProductVariant field.
func (r *mutationResolver) CreateProductVariant(ctx context.Context, input CreateProductVariantInput) (*ProductVariant, error) {
	if err := checkIsEmployee(ctx); err != nil {
		return nil, err
	}
	variant, created, err := r.Store.CreateProductVariant(
		ctx, input.ProductID,
		store.VariantInput{IsPubliclyVisible: input.IsPubliclyVisible, InitialVersion: toVersionInput(input.InitialVersion)},
		time.Now().UTC(),
	)
	if err != nil {
		return nil, err
	}
	// Publish product-variant/created then product-variant-version/created. The
	// product's defaultVariant is not changed and no product/updated fires.
	if err := events.PublishProductVariantCreated(ctx, r.Dapr, variantCreatedEvent(variant)); err != nil {
		return nil, err
	}
	if err := events.PublishProductVariantVersionCreated(ctx, r.Dapr, versionCreatedEvent(created)); err != nil {
		return nil, err
	}
	return toProductVariant(variant), nil
}

// CreateProductVariantVersion is the resolver for the createProductVariantVersion field.
func (r *mutationResolver) CreateProductVariantVersion(ctx context.Context, input CreateProductVariantVersionInput) (*ProductVariantVersion, error) {
	if err := checkIsEmployee(ctx); err != nil {
		return nil, err
	}
	created, err := r.Store.CreateProductVariantVersion(
		ctx, input.ProductVariantID, toVersionInputFromCreate(input), time.Now().UTC(),
	)
	if err != nil {
		return nil, err
	}
	// Repoints currentVersion (handled in the store); only the version event fires.
	if err := events.PublishProductVariantVersionCreated(ctx, r.Dapr, versionCreatedEvent(created)); err != nil {
		return nil, err
	}
	return toProductVariantVersion(created.Version), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input UpdateProductInput) (*Product, error) {
	if err := checkIsEmployee(ctx); err != nil {
		return nil, err
	}
	product, categoryIDs, err := r.Store.UpdateProduct(ctx, input.ID, input.IsPubliclyVisible, input.InternalName, input.DefaultVariantID)
	if err != nil {
		return nil, err
	}
	// Always publishes product/updated with the full ProductDTO, even for a no-op.
	if err := events.PublishProductUpdated(ctx, r.Dapr, events.Product{
		ID:                product.ID,
		InternalName:      product.InternalName,
		IsPubliclyVisible: product.IsPubliclyVisible,
		DefaultVariantID:  product.DefaultVariantID,
		CategoryIDs:       categoryIDs,
	}); err != nil {
		return nil, err
	}
	return toProduct(product), nil
}

// UpdateProductVariant is the resolver for the updateProductVariant field.
func (r *mutationResolver) UpdateProductVariant(ctx context.Context, input UpdateProductVariantInput) (*ProductVariant, error) {
	if err := checkIsEmployee(ctx); err != nil {
		return nil, err
	}
	variant, err := r.Store.UpdateProductVariant(ctx, input.ID, input.IsPubliclyVisible)
	if err != nil {
		return nil, err
	}
	// Always publishes product-variant/updated {id, isPubliclyVisible}.
	if err := events.PublishProductVariantUpdated(ctx, r.Dapr, events.UpdatedProductVariant{
		ID: variant.ID, IsPubliclyVisible: variant.IsPubliclyVisible,
	}); err != nil {
		return nil, err
	}
	return toProductVariant(variant), nil
}

// Category is the resolver for the category field.
func (r *numericalCategoryCharacteristicResolver) Category(ctx context.Context, obj *NumericalCategoryCharacteristic) (*Category, error) {
	// No auth.
	category, err := r.Store.GetCategory(ctx, obj.CategoryID)
	if err != nil {
		return nil, err
	}
	return toCategory(category), nil
}

// Characteristic is the resolver for the characteristic field.
func (r *numericalCategoryCharacteristicValueResolver) Characteristic(ctx context.Context, obj *NumericalCategoryCharacteristicValue) (CategoryCharacteristic, error) {
	// No auth.
	c, err := r.Store.GetCharacteristic(ctx, obj.CharacteristicID)
	if err != nil {
		return nil, err
	}
	return toCharacteristic(c), nil
}

// Categories is the resolver for the categories field.
func (r *productResolver) Categories(ctx context.Context, obj *Product, first *int, orderBy *CategoryOrderInput, skip *int) (*CategoryConnection, error) {
	// No auth check (reachable via federation even on hidden products).
	col, asc := categoryOrder(orderBy)
	join := " INNER JOIN producttocategoryentity ON producttocategoryentity.categoryid = categoryentity.id"
	conn, err := r.Store.ListCategories(
		ctx, store.NewListArgs(first, skip, col, asc),
		join, "producttocategoryentity.productid = $1", []any{obj.ID},
	)
	if err != nil {
		return nil, err
	}
	return toCategoryConnection(conn), nil
}

// DefaultVariant is the resolver for the defaultVariant field.
func (r *productResolver) DefaultVariant(ctx context.Context, obj *Product) (*ProductVariant, error) {
	// Gates on the PRODUCT's visibility, not the variant's.
	if !obj.IsPubliclyVisible {
		if err := checkIsEmployee(ctx); err != nil {
			return nil, err
		}
	}
	variant, err := r.Store.GetProductVariant(ctx, obj.DefaultVariantID)
	if err != nil {
		return nil, err
	}
	return toProductVariant(variant), nil
}

// InternalName is the resolver for the internalName field.
func (r *productResolver) InternalName(ctx context.Context, obj *Product) (string, error) {
	// Requires employee even for publicly visible products.
	if err := checkIsEmployee(ctx); err != nil {
		return "", err
	}
	return obj.InternalName, nil
}

// Variants is the resolver for the variants field.
func (r *productResolver) Variants(ctx context.Context, obj *Product, filter *ProductVariantFilterInput, first *int, orderBy *ProductVariantOrderInput, skip *int) (*ProductVariantConnection, error) {
	// If the product is not publicly visible, requires employee; the variant-level
	// visibility filter still applies to non-employees.
	if !obj.IsPubliclyVisible {
		if err := checkIsEmployee(ctx); err != nil {
			return nil, err
		}
	}
	col, asc := productVariantOrder(orderBy)
	conn, err := r.Store.ListProductVariants(
		ctx, store.NewListArgs(first, skip, col, asc), obj.ID, variantFilterVisible(filter), isEmployee(ctx),
	)
	if err != nil {
		return nil, err
	}
	return toProductVariantConnection(conn), nil
}

// CurrentVersion is the resolver for the currentVersion field.
func (r *productVariantResolver) CurrentVersion(ctx context.Context, obj *ProductVariant) (*ProductVariantVersion, error) {
	// Gates on the VARIANT's visibility.
	if !obj.IsPubliclyVisible {
		if err := checkIsEmployee(ctx); err != nil {
			return nil, err
		}
	}
	version, err := r.Store.GetProductVariantVersion(ctx, obj.CurrentVersionID)
	if err != nil {
		return nil, err
	}
	return toProductVariantVersion(version), nil
}

// Product is the resolver for the product field.
func (r *productVariantResolver) Product(ctx context.Context, obj *ProductVariant) (*Product, error) {
	// No auth.
	product, err := r.Store.GetProduct(ctx, obj.ProductID)
	if err != nil {
		return nil, err
	}
	return toProduct(product), nil
}

// Versions is the resolver for the versions field.
func (r *productVariantResolver) Versions(ctx context.Context, obj *ProductVariant, first *int, orderBy *ProductVariantVersionOrderInput, skip *int) (*ProductVariantVersionConnection, error) {
	// Always requires employee, regardless of visibility.
	if err := checkIsEmployee(ctx); err != nil {
		return nil, err
	}
	col, asc := productVariantVersionOrder(orderBy)
	conn, err := r.Store.ListProductVariantVersions(ctx, store.NewListArgs(first, skip, col, asc), obj.ID)
	if err != nil {
		return nil, err
	}
	return toProductVariantVersionConnection(conn), nil
}

// CharacteristicValues is the resolver for the characteristicValues field.
func (r *productVariantVersionResolver) CharacteristicValues(ctx context.Context, obj *ProductVariantVersion, first *int, orderBy *CategoryCharacteristicValueOrderInput, skip *int) (*CategoryCharacteristicValueConnection, error) {
	// No auth.
	col, asc := characteristicValueOrder(orderBy)
	conn, err := r.Store.ListCharacteristicValues(ctx, store.NewListArgs(first, skip, col, asc), obj.ID)
	if err != nil {
		return nil, err
	}
	return toCharacteristicValueConnection(conn), nil
}

// Medias is the resolver for the medias field.
func (r *productVariantVersionResolver) Medias(ctx context.Context, obj *ProductVariantVersion, first *int, orderBy *CommonOrderInput, skip *int) (*MediaConnection, error) {
	// No auth.
	col, asc := commonOrder(orderBy)
	conn, err := r.Store.ListMedias(ctx, store.NewListArgs(first, skip, col, asc), obj.ID)
	if err != nil {
		return nil, err
	}
	return toMediaConnection(conn), nil
}

// ProductVariant is the resolver for the productVariant field.
func (r *productVariantVersionResolver) ProductVariant(ctx context.Context, obj *ProductVariantVersion) (*ProductVariant, error) {
	// No auth.
	variant, err := r.Store.GetProductVariant(ctx, obj.ProductVariantID)
	if err != nil {
		return nil, err
	}
	return toProductVariant(variant), nil
}

// TaxRate is the resolver for the taxRate field.
func (r *productVariantVersionResolver) TaxRate(ctx context.Context, obj *ProductVariantVersion) (*TaxRate, error) {
	// No auth; the local taxrateentity stub returns just {id}. The FK guarantees
	// the row exists, but resolve defensively.
	rate, err := r.Store.GetTaxRateStub(ctx, obj.TaxRateID)
	if err != nil {
		return nil, err
	}
	return toTaxRate(rate), nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, first *int, orderBy *CategoryOrderInput, skip *int) (*CategoryConnection, error) {
	// No predicate, no filter, no auth.
	col, asc := categoryOrder(orderBy)
	conn, err := r.Store.ListCategories(ctx, store.NewListArgs(first, skip, col, asc), "", "", nil)
	if err != nil {
		return nil, err
	}
	return toCategoryConnection(conn), nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id uuid.UUID) (*Category, error) {
	// No auth.
	category, err := r.Store.GetCategory(ctx, id)
	if err != nil {
		return nil, err
	}
	return toCategory(category), nil
}

// CategoryCharacteristic is the resolver for the categoryCharacteristic field.
func (r *queryResolver) CategoryCharacteristic(ctx context.Context, id uuid.UUID) (CategoryCharacteristic, error) {
	// No auth; concrete type resolved from the discriminator.
	c, err := r.Store.GetCharacteristic(ctx, id)
	if err != nil {
		return nil, err
	}
	return toCharacteristic(c), nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id uuid.UUID) (*Product, error) {
	// Load first; if the product is not publicly visible, require employee.
	product, err := r.Store.GetProduct(ctx, id)
	if err != nil {
		return nil, err
	}
	if !product.IsPubliclyVisible {
		if err := checkIsEmployee(ctx); err != nil {
			return nil, err
		}
	}
	return toProduct(product), nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, filter *ProductFilterInput, first *int, orderBy *ProductOrderInput, skip *int) (*ProductConnection, error) {
	// No predicate; visibility filter for non-employees; anonymous allowed.
	col, asc := productOrder(orderBy)
	conn, err := r.Store.ListProducts(
		ctx, store.NewListArgs(first, skip, col, asc), "", "", nil,
		filterVisible(filter), isEmployee(ctx),
	)
	if err != nil {
		return nil, err
	}
	return toProductConnection(conn), nil
}

// CategoricalCategoryCharacteristic returns CategoricalCategoryCharacteristicResolver implementation.
func (r *Resolver) CategoricalCategoryCharacteristic() CategoricalCategoryCharacteristicResolver {
	return &categoricalCategoryCharacteristicResolver{r}
}

// CategoricalCategoryCharacteristicValue returns CategoricalCategoryCharacteristicValueResolver implementation.
func (r *Resolver) CategoricalCategoryCharacteristicValue() CategoricalCategoryCharacteristicValueResolver {
	return &categoricalCategoryCharacteristicValueResolver{r}
}

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// NumericalCategoryCharacteristic returns NumericalCategoryCharacteristicResolver implementation.
func (r *Resolver) NumericalCategoryCharacteristic() NumericalCategoryCharacteristicResolver {
	return &numericalCategoryCharacteristicResolver{r}
}

// NumericalCategoryCharacteristicValue returns NumericalCategoryCharacteristicValueResolver implementation.
func (r *Resolver) NumericalCategoryCharacteristicValue() NumericalCategoryCharacteristicValueResolver {
	return &numericalCategoryCharacteristicValueResolver{r}
}

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

// ProductVariant returns ProductVariantResolver implementation.
func (r *Resolver) ProductVariant() ProductVariantResolver { return &productVariantResolver{r} }

// ProductVariantVersion returns ProductVariantVersionResolver implementation.
func (r *Resolver) ProductVariantVersion() ProductVariantVersionResolver {
	return &productVariantVersionResolver{r}
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	categoricalCategoryCharacteristicResolver      struct{ *Resolver }
	categoricalCategoryCharacteristicValueResolver struct{ *Resolver }
	categoryResolver                               struct{ *Resolver }
	mutationResolver                               struct{ *Resolver }
	numericalCategoryCharacteristicResolver        struct{ *Resolver }
	numericalCategoryCharacteristicValueResolver   struct{ *Resolver }
	productResolver                                struct{ *Resolver }
	productVariantResolver                         struct{ *Resolver }
	productVariantVersionResolver                  struct{ *Resolver }
	queryResolver                                  struct{ *Resolver }
)
