package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/google/uuid"
)

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	// Federation entity resolvers perform no auth check (the original
	// FederatedTypePromiseResolver resolved via the data loader directly). A
	// representation without an id resolved to null.
	if id == uuid.Nil {
		return nil, nil
	}
	user, err := r.Store.GetUser(ctx, id)
	if err != nil {
		return nil, err
	}
	return toUser(user), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
