// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"misarch/pkg/scalars"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

// An object with an ID.
type Node interface {
	IsNode()
}

type Mutation struct {
}

// A name consisting of a firstName and lastName.
type Name struct {
	// The first name of the user
	FirstName string `json:"firstName"`
	// The last name of the user
	LastName string `json:"lastName"`
}

type Query struct {
}

// Input for the updateUser mutation
type UpdateUserInput struct {
	// The new birthday of the user
	Birthday graphql.Omittable[*scalars.Date] `json:"birthday,omitempty"`
	// The new first name of the user
	FirstName graphql.Omittable[*string] `json:"firstName,omitempty"`
	// The new gender of the user
	Gender graphql.Omittable[*Gender] `json:"gender,omitempty"`
	// The id of the user to update
	ID uuid.UUID `json:"id"`
	// The new last name of the user
	LastName graphql.Omittable[*string] `json:"lastName,omitempty"`
}

// A user.
type User struct {
	// The birthday of the user
	Birthday *scalars.Date `json:"birthday,omitempty"`
	// The date when the user joined
	DateJoined time.Time `json:"dateJoined"`
	// The gender of the user
	Gender *Gender `json:"gender,omitempty"`
	// The ID of the node.
	ID uuid.UUID `json:"id"`
	// The name of the user
	Name *Name `json:"name"`
	// The username of the user
	Username string `json:"username"`
}

func (User) IsNode() {}

func (User) IsEntity() {}

// A connection to a list of `User` values.
type UserConnection struct {
	// Whether this connection has a next page
	HasNextPage bool `json:"hasNextPage"`
	// The resulting items.
	Nodes []User `json:"nodes"`
	// The total amount of items in this connection
	TotalCount int `json:"totalCount"`
}

// User order
type UserOrderInput struct {
	// The direction to order by
	Direction graphql.Omittable[*OrderDirection] `json:"direction,omitempty"`
	// The field to order by
	Field graphql.Omittable[*UserOrderField] `json:"field,omitempty"`
}

// The gender of a user
type Gender string

const (
	// Diverse gender
	GenderDiverse Gender = "DIVERSE"
	// Female gender
	GenderFemale Gender = "FEMALE"
	// Male gender
	GenderMale Gender = "MALE"
	// Other gender
	GenderOther Gender = "OTHER"
)

var AllGender = []Gender{
	GenderDiverse,
	GenderFemale,
	GenderMale,
	GenderOther,
}

func (e Gender) IsValid() bool {
	switch e {
	case GenderDiverse, GenderFemale, GenderMale, GenderOther:
		return true
	}
	return false
}

func (e Gender) String() string {
	return string(e)
}

func (e *Gender) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Gender(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Gender", str)
	}
	return nil
}

func (e Gender) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Gender) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Gender) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Order direction
type OrderDirection string

const (
	// Ascending order
	OrderDirectionAsc OrderDirection = "ASC"
	// Descending order
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// User order fields
type UserOrderField string

const (
	// Order users by their id
	UserOrderFieldID UserOrderField = "ID"
	// Order users by their username
	UserOrderFieldUsername UserOrderField = "USERNAME"
)

var AllUserOrderField = []UserOrderField{
	UserOrderFieldID,
	UserOrderFieldUsername,
}

func (e UserOrderField) IsValid() bool {
	switch e {
	case UserOrderFieldID, UserOrderFieldUsername:
		return true
	}
	return false
}

func (e UserOrderField) String() string {
	return string(e)
}

func (e *UserOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserOrderField", str)
	}
	return nil
}

func (e UserOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
