package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"time"

	"github.com/google/uuid"

	"misarch/pkg/auth"
	"misarch/pkg/scalars"
)

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input UpdateUserInput) (*User, error) {
	// Authenticated; self (input.id) OR employee/admin.
	if _, err := auth.RequireSelfOrEmployee(ctx, input.ID); err != nil {
		return nil, err
	}

	// firstName/lastName are plain-nullable: apply only a set, non-nil value
	// (a JSON null, like omission, leaves the column unchanged).
	firstName := input.FirstName.Value()
	lastName := input.LastName.Value()

	// birthday/gender are tri-state: IsSet() distinguishes "present" from
	// "omitted"; a present nil value clears the column to NULL. A present
	// birthday is stored at UTC midnight so it round-trips with the Date read.
	birthdaySet := input.Birthday.IsSet()
	var birthday *time.Time
	if birthdaySet {
		if d := input.Birthday.Value(); d != nil {
			bd := time.Date(d.Year(), d.Month(), d.Day(), 0, 0, 0, 0, time.UTC)
			birthday = &bd
		}
	}

	genderSet := input.Gender.IsSet()
	var gender *string
	if genderSet {
		if g := input.Gender.Value(); g != nil {
			s := string(*g)
			gender = &s
		}
	}

	// Partial update; no event is published (matching the original).
	user, err := r.Store.UpdateUser(ctx, input.ID, firstName, lastName, birthdaySet, birthday, genderSet, gender)
	if err != nil {
		return nil, err
	}
	return toUser(user), nil
}

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*User, error) {
	// No auth required: anonymous requests return null. When authenticated, the
	// row is loaded by id; a missing row is an error (the original awaitSingle
	// threw), which in practice never happens because the user was created via
	// the inbound event.
	u := auth.FromContext(ctx)
	if u == nil {
		return nil, nil
	}
	user, err := r.Store.GetUser(ctx, u.ID)
	if err != nil {
		return nil, err
	}
	return toUser(user), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uuid.UUID) (*User, error) {
	// Authenticated; self OR employee/admin.
	if _, err := auth.RequireSelfOrEmployee(ctx, id); err != nil {
		return nil, err
	}
	user, err := r.Store.GetUser(ctx, id)
	if err != nil {
		return nil, err
	}
	return toUser(user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, first *int, orderBy *UserOrderInput, skip *int) (*UserConnection, error) {
	// Employee/admin required for the whole query.
	if _, err := auth.RequireEmployeeOrAdmin(ctx); err != nil {
		return nil, err
	}
	col, asc := userOrder(orderBy)
	conn, err := r.Store.ListUsers(ctx, first, skip, col, asc)
	if err != nil {
		return nil, err
	}
	return toUserConnection(conn), nil
}

// Birthday is the resolver for the birthday field.
func (r *userResolver) Birthday(ctx context.Context, obj *User) (*scalars.Date, error) {
	// Per-field auth: self (the user being read) OR employee/admin.
	if _, err := auth.RequireSelfOrEmployee(ctx, obj.ID); err != nil {
		return nil, err
	}
	return obj.Birthday, nil
}

// DateJoined is the resolver for the dateJoined field.
func (r *userResolver) DateJoined(ctx context.Context, obj *User) (*time.Time, error) {
	// Per-field auth: self OR employee/admin. dateJoined is non-null, so an
	// unauthorized selection errors the whole User (matching the original).
	if _, err := auth.RequireSelfOrEmployee(ctx, obj.ID); err != nil {
		return nil, err
	}
	return &obj.DateJoined, nil
}

// Gender is the resolver for the gender field.
func (r *userResolver) Gender(ctx context.Context, obj *User) (*Gender, error) {
	// Per-field auth: self OR employee/admin.
	if _, err := auth.RequireSelfOrEmployee(ctx, obj.ID); err != nil {
		return nil, err
	}
	return obj.Gender, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	userResolver     struct{ *Resolver }
)
